/* ============================================================
   Chapitre Bonus 7 · 谈爱好和运动 — Loisirs et sports
   Adapté du support « Talking about Hobbies and Sports ».
   Chaque leçon part d'un dialogue à comprendre et à rejouer.
   ============================================================ */
registerChapter({
  group:"bonus", id:"07-hobbies", badge:"★7", star:true,
  hanzi:"谈爱好和运动", title:"Bonus 7 · Loisirs et sports",
  desc:"Dire ce que l'on aime, ce que l'on fait souvent, son niveau et ses projets — 12 leçons",
  intro:"Douze leçons progressives pour discuter naturellement de vos loisirs, de vos sports et de vos projets. Chaque mot du support est utilisé dans une phrase utile, puis réemployé dans une réponse personnelle ou un dialogue.",
  lessons:[

  {num:1,hanzi:"爱好",title:"Dire ce que vous aimez",desc:"爱好 · 喜欢 · 看书 · 听音乐",
    build(){return[
  N("Leçon 1. Écoutez le dialogue cible. À la fin, vous saurez demander le loisir de quelqu'un et donner le vôtre."),
  C("你的爱好是什么？","Nǐ de àihào shì shénme?","Quel est ton loisir ?",.62),
  C("我喜欢看书和听音乐。","Wǒ xǐhuan kàn shū hé tīng yīnyuè.","J'aime lire et écouter de la musique.",.62),
  N("[[爱好|àihào]] est un loisir ou un centre d'intérêt. On ne le récite pas seul : écoutez plusieurs réponses naturelles."),
  ...teach2("我的爱好是看书。","Wǒ de àihào shì kàn shū.","Mon loisir, c'est lire."),
  ...teach2("我喜欢听音乐，也喜欢看电影。","Wǒ xǐhuan tīng yīnyuè, yě xǐhuan kàn diànyǐng.","J'aime écouter de la musique et aussi regarder des films."),
  ...teach2("她喜欢上网看电影。","Tā xǐhuan shàng wǎng kàn diànyǐng.","Elle aime aller sur Internet pour regarder des films."),
  N("Demandez à votre interlocuteur quel est son loisir."),TH(),
  C("你的爱好是什么？","Nǐ de àihào shì shénme?","Quel est ton loisir ?",.66),HOLD(),
  N("Répondez : j'aime lire et écouter de la musique."),TH(),
  C("我喜欢看书和听音乐。","Wǒ xǐhuan kàn shū hé tīng yīnyuè.","J'aime lire et écouter de la musique.",.66),HOLD(),
  N("Rejouez le dialogue cible. Vous posez la question. Dites : quel est ton loisir ?"),TH(),
  C("你的爱好是什么？","Nǐ de àihào shì shénme?","Quel est ton loisir ?",.66),HOLD(),
  N("Vous répondez. Dites : j'aime lire et écouter de la musique."),TH(),
  C("我喜欢看书和听音乐。","Wǒ xǐhuan kàn shū hé tīng yīnyuè.","J'aime lire et écouter de la musique.",.66),HOLD(),
    ];}},

  {num:2,hanzi:"经常",title:"Dire ce que vous faites souvent",desc:"经常 · 有时候 · 从来不",
    build(){return[
  N("Leçon 2. Écoutez le dialogue cible. Vous allez dire si vous faites une activité souvent, parfois ou jamais."),
  C("你经常看电影吗？","Nǐ jīngcháng kàn diànyǐng ma?","Est-ce que tu regardes souvent des films ?",.62),
  C("我有时候看电影。","Wǒ yǒushíhou kàn diànyǐng.","Je regarde parfois des films.",.62),
  N("[[经常|jīngcháng]] veut dire souvent et [[有时候|yǒushíhou]] parfois. Les deux se placent avant l'activité."),
  ...teach2("我经常听音乐。","Wǒ jīngcháng tīng yīnyuè.","J'écoute souvent de la musique."),
  ...teach2("周末我有时候上网。","Zhōumò wǒ yǒushíhou shàng wǎng.","Le week-end, je vais parfois sur Internet."),
  N("Pour dire jamais, utilisez [[从来不|cóngláibù]] avant le verbe."),
  ...teach2("我从来不跳舞。","Wǒ cóngláibù tiàowǔ.","Je ne danse jamais."),
  ...teach2("他经常画画儿，但是从来不唱歌。","Tā jīngcháng huà huàr, dànshì cóngláibù chàng gē.","Il dessine souvent, mais ne chante jamais."),
  N("Demandez : est-ce que tu regardes souvent des films ?"),TH(),
  C("你经常看电影吗？","Nǐ jīngcháng kàn diànyǐng ma?","Est-ce que tu regardes souvent des films ?",.66),HOLD(),
  N("Répondez : je regarde parfois des films."),TH(),
  C("我有时候看电影。","Wǒ yǒushíhou kàn diànyǐng.","Je regarde parfois des films.",.66),HOLD(),
  N("Dites : je ne danse jamais."),TH(),
  C("我从来不跳舞。","Wǒ cóngláibù tiàowǔ.","Je ne danse jamais.",.66),HOLD(),
    ];}},

  {num:3,hanzi:"画画儿",title:"Parler d’activités créatives",desc:"画画儿 · 摄影 · 弹钢琴 · 唱歌 · 跳舞",
    build(){return[
  N("Leçon 3. Voici le dialogue cible. À la fin, vous saurez dire ce que vous faites comme activité créative."),
  C("你喜欢摄影吗？","Nǐ xǐhuan shèyǐng ma?","Est-ce que tu aimes la photographie ?",.62),
  C("喜欢，我也喜欢画画儿。","Xǐhuan, wǒ yě xǐhuan huà huàr.","Oui. J'aime aussi dessiner.",.62),
  N("Les loisirs se présentent dans des phrases courtes et personnelles."),
  ...teach2("她喜欢弹钢琴，也喜欢唱歌。","Tā xǐhuan tán gāngqín, yě xǐhuan chàng gē.","Elle aime jouer du piano et aussi chanter."),
  ...teach2("我不会弹钢琴，但是我喜欢听钢琴音乐。","Wǒ bú huì tán gāngqín, dànshì wǒ xǐhuan tīng gāngqín yīnyuè.","Je ne sais pas jouer du piano, mais j'aime écouter de la musique au piano."),
  ...teach2("周末我们一起跳舞，拍照片。","Zhōumò wǒmen yìqǐ tiàowǔ, pāi zhàopiàn.","Le week-end, nous dansons et prenons des photos ensemble."),
  N("Demandez : est-ce que tu aimes la photographie ?"),TH(),
  C("你喜欢摄影吗？","Nǐ xǐhuan shèyǐng ma?","Est-ce que tu aimes la photographie ?",.66),HOLD(),
  N("Répondez : oui, et j'aime aussi dessiner."),TH(),
  C("喜欢，我也喜欢画画儿。","Xǐhuan, wǒ yě xǐhuan huà huàr.","Oui. J'aime aussi dessiner.",.66),HOLD(),
  N("Dites : elle aime jouer du piano et chanter."),TH(),
  C("她喜欢弹钢琴，也喜欢唱歌。","Tā xǐhuan tán gāngqín, yě xǐhuan chàng gē.","Elle aime jouer du piano et aussi chanter.",.66),HOLD(),
    ];}},

  {num:4,hanzi:"喜欢运动",title:"Dire quels sports vous aimez",desc:"运动 · 最喜欢 · 还喜欢 · 跑步 · 游泳",
    build(){return[
  N("Leçon 4. Écoutez le dialogue cible. Vous allez dire votre sport préféré et ajouter un autre sport que vous aimez."),
  C("你喜欢什么运动？","Nǐ xǐhuan shénme yùndòng?","Quels sports aimes-tu ?",.62),
  C("我最喜欢跑步，还喜欢游泳。","Wǒ zuì xǐhuan pǎobù, hái xǐhuan yóuyǒng.","J'aime surtout courir, et j'aime aussi nager.",.62),
  N("[[最喜欢|zuì xǐhuan]] marque votre préférence principale. [[还喜欢|hái xǐhuan]] permet d'ajouter une autre activité."),
  ...teach2("我最喜欢打篮球，还喜欢踢足球。","Wǒ zuì xǐhuan dǎ lánqiú, hái xǐhuan tī zúqiú.","J'aime surtout jouer au basket, et j'aime aussi jouer au football."),
  ...teach2("她最喜欢打网球，但是不喜欢游泳。","Tā zuì xǐhuan dǎ wǎngqiú, dànshì bù xǐhuan yóuyǒng.","Elle préfère le tennis, mais n'aime pas nager."),
  ...teach2("我的爱好很多，运动是其中一个。","Wǒ de àihào hěn duō, yùndòng shì qízhōng yí ge.","J'ai beaucoup de loisirs ; le sport en est un."),
  N("Demandez : quels sports aimes-tu ?"),TH(),
  C("你喜欢什么运动？","Nǐ xǐhuan shénme yùndòng?","Quels sports aimes-tu ?",.66),HOLD(),
  N("Répondez : j'aime surtout courir, et j'aime aussi nager."),TH(),
  C("我最喜欢跑步，还喜欢游泳。","Wǒ zuì xǐhuan pǎobù, hái xǐhuan yóuyǒng.","J'aime surtout courir, et j'aime aussi nager.",.66),HOLD(),
  N("Dites : elle préfère le tennis, mais n'aime pas nager."),TH(),
  C("她最喜欢打网球，但是不喜欢游泳。","Tā zuì xǐhuan dǎ wǎngqiú, dànshì bù xǐhuan yóuyǒng.","Elle préfère le tennis, mais n'aime pas nager.",.66),HOLD(),
    ];}},

  {num:5,hanzi:"打得很好",title:"Dire à quel point quelqu’un est bon",desc:"V + 得 + degré + adjectif",
    build(){return[
  N("Leçon 5. Écoutez le dialogue cible. Vous allez décrire le niveau de quelqu'un dans un sport."),
  C("她打篮球打得怎么样？","Tā dǎ lánqiú dǎ de zěnmeyàng?","Comment joue-t-elle au basket ?",.62),
  C("她打得特别好。","Tā dǎ de tèbié hǎo.","Elle joue particulièrement bien.",.62),
  N("Après une activité, [[得|de]] introduit la manière de faire. On peut éviter de répéter l'objet : 她打篮球打得特别好 devient 她打得特别好."),
  ...teach2("他跑得很快。","Tā pǎo de hěn kuài.","Il court très vite."),
  ...teach2("我游泳游得不太好。","Wǒ yóuyǒng yóu de bú tài hǎo.","Je ne nage pas très bien."),
  ...teach2("她唱歌唱得很好，我们都喜欢听。","Tā chàng gē chàng de hěn hǎo, wǒmen dōu xǐhuan tīng.","Elle chante très bien ; nous aimons tous l'écouter."),
  ...teach2("你弹钢琴弹得怎么样？","Nǐ tán gāngqín tán de zěnmeyàng?","Comment joues-tu du piano ?"),
  N("Demandez : comment joue-t-elle au basket ?"),TH(),
  C("她打篮球打得怎么样？","Tā dǎ lánqiú dǎ de zěnmeyàng?","Comment joue-t-elle au basket ?",.66),HOLD(),
  N("Répondez : elle joue particulièrement bien."),TH(),
  C("她打得特别好。","Tā dǎ de tèbié hǎo.","Elle joue particulièrement bien.",.66),HOLD(),
  N("Dites : il court très vite."),TH(),
  C("他跑得很快。","Tā pǎo de hěn kuài.","Il court très vite.",.66),HOLD(),
    ];}},

  {num:6,hanzi:"去操场跑步",title:"Dire où vous allez faire une activité",desc:"要 · 去 + lieu + verbe · 操场",
    build(){return[
  N("Leçon 6. Écoutez le dialogue cible. Vous allez dire ce que vous allez faire et où vous allez le faire."),
  C("你要去哪儿？","Nǐ yào qù nǎr?","Où vas-tu ?",.62),
  C("我去操场跑步。","Wǒ qù cāochǎng pǎobù.","Je vais courir sur le terrain de sport.",.62),
  N("En chinois, le lieu arrive avant l'activité : aller au terrain de sport, puis courir."),
  ...teach2("下午我要去健身房健身。","Xiàwǔ wǒ yào qù jiànshēnfáng jiànshēn.","Cet après-midi, je vais aller à la salle de sport pour m'entraîner."),
  ...teach2("周末我们去公园跑步。","Zhōumò wǒmen qù gōngyuán pǎobù.","Le week-end, nous allons courir au parc."),
  ...teach2("她要去游泳馆游泳。","Tā yào qù yóuyǒngguǎn yóuyǒng.","Elle va aller nager à la piscine."),
  N("Demandez : où vas-tu ?"),TH(),
  C("你要去哪儿？","Nǐ yào qù nǎr?","Où vas-tu ?",.66),HOLD(),
  N("Répondez : je vais courir sur le terrain de sport."),TH(),
  C("我去操场跑步。","Wǒ qù cāochǎng pǎobù.","Je vais courir sur le terrain de sport.",.66),HOLD(),
  N("Dites : cet après-midi, je vais m'entraîner à la salle de sport."),TH(),
  C("下午我要去健身房健身。","Xiàwǔ wǒ yào qù jiànshēnfáng jiànshēn.","Cet après-midi, je vais aller à la salle de sport pour m'entraîner.",.66),HOLD(),
    ];}},

  {num:7,hanzi:"正在健身",title:"Dire ce qui est en cours",desc:"正在 / 在 / 正 + action + 呢",
    build(){return[
  N("Leçon 7. Écoutez le dialogue cible. Vous allez demander ce que quelqu'un est en train de faire."),
  C("你正在做什么呢？","Nǐ zhèngzài zuò shénme ne?","Qu'est-ce que tu es en train de faire ?",.62),
  C("我正在健身呢。","Wǒ zhèngzài jiànshēn ne.","Je suis en train de m'entraîner.",.62),
  N("[[正在|zhèngzài]] ou [[在|zài]] placent l'action en cours. La particule 呢 donne un ton vivant à la réponse."),
  ...teach2("他在操场跑步呢。","Tā zài cāochǎng pǎobù ne.","Il est en train de courir sur le terrain de sport."),
  ...teach2("她正在看书，不想看电影。","Tā zhèngzài kàn shū, bù xiǎng kàn diànyǐng.","Elle est en train de lire ; elle ne veut pas regarder de film."),
  ...teach2("我们正听音乐呢。","Wǒmen zhèng tīng yīnyuè ne.","Nous sommes en train d'écouter de la musique."),
  N("Demandez : qu'est-ce que tu es en train de faire ?"),TH(),
  C("你正在做什么呢？","Nǐ zhèngzài zuò shénme ne?","Qu'est-ce que tu es en train de faire ?",.66),HOLD(),
  N("Répondez : je suis en train de m'entraîner."),TH(),
  C("我正在健身呢。","Wǒ zhèngzài jiànshēn ne.","Je suis en train de m'entraîner.",.66),HOLD(),
  N("Dites : il est en train de courir sur le terrain de sport."),TH(),
  C("他在操场跑步呢。","Tā zài cāochǎng pǎobù ne.","Il est en train de courir sur le terrain de sport.",.66),HOLD(),
    ];}},

  {num:8,hanzi:"去唱歌",title:"Inviter un ami à chanter",desc:"一起 · 以后 · 好吗 · 正想",
    build(){return[
  N("Leçon 8. Écoutez le dialogue cible. Vous allez proposer une sortie simple et répondre naturellement."),
  C("明天晚上一起去唱歌，好吗？","Míngtiān wǎnshang yìqǐ qù chàng gē, hǎo ma?","On va chanter ensemble demain soir ?",.62),
  C("好啊，我正想唱歌呢。","Hǎo a, wǒ zhèng xiǎng chàng gē ne.","Oui, justement, j'avais envie de chanter.",.62),
  N("[[一起|yìqǐ]] signifie ensemble. Pour inviter avec douceur, terminez par [[好吗|hǎo ma]], « ça te va ? »."),
  ...teach2("周末我们一起去看电影，好吗？","Zhōumò wǒmen yìqǐ qù kàn diànyǐng, hǎo ma?","On va voir un film ensemble ce week-end ?"),
  ...teach2("下课以后一起去喝咖啡吧。","Xià kè yǐhòu yìqǐ qù hē kāfēi ba.","Allons prendre un café ensemble après le cours."),
  ...teach2("我正想听音乐，你也喜欢吗？","Wǒ zhèng xiǎng tīng yīnyuè, nǐ yě xǐhuan ma?","J'avais justement envie d'écouter de la musique ; toi aussi, tu aimes ça ?"),
  N("Proposez : on va chanter ensemble demain soir ?"),TH(),
  C("明天晚上一起去唱歌，好吗？","Míngtiān wǎnshang yìqǐ qù chàng gē, hǎo ma?","On va chanter ensemble demain soir ?",.66),HOLD(),
  N("Acceptez. Dites : oui, justement, j'avais envie de chanter."),TH(),
  C("好啊，我正想唱歌呢。","Hǎo a, wǒ zhèng xiǎng chàng gē ne.","Oui, justement, j'avais envie de chanter.",.66),HOLD(),
  N("Invitez votre ami à voir un film ensemble ce week-end."),TH(),
  C("周末我们一起去看电影，好吗？","Zhōumò wǒmen yìqǐ qù kàn diànyǐng, hǎo ma?","On va voir un film ensemble ce week-end ?",.66),HOLD(),
    ];}},

  {num:9,hanzi:"太极拳",title:"Apprendre une activité avec quelqu’un",desc:"学习 · 太极拳 · 可以 · 参加",
    build(){return[
  N("Leçon 9. Écoutez le dialogue cible. Vous allez rejoindre quelqu'un qui apprend une activité."),
  C("你去哪儿？","Nǐ qù nǎr?","Où vas-tu ?",.62),
  C("我去操场打太极拳。","Wǒ qù cāochǎng dǎ tàijíquán.","Je vais faire du taiji sur le terrain de sport.",.62),
  C("你是不是正在学习太极拳？","Nǐ shì bu shì zhèngzài xuéxí tàijíquán?","Est-ce que tu es en train d'apprendre le taiji ?",.62),
  C("是啊。你也参加，怎么样？","Shì a. Nǐ yě cānjiā, zěnmeyàng?","Oui. Tu veux te joindre à nous ?",.62),
  N("[[学习|xuéxí]] est apprendre et [[参加|cānjiā]] est participer. Les deux servent ici à proposer une activité réelle."),
  ...teach2("我想学习打太极拳。","Wǒ xiǎng xuéxí dǎ tàijíquán.","Je voudrais apprendre le taiji."),
  ...teach2("我们可以一起学。","Wǒmen kěyǐ yìqǐ xué.","Nous pouvons apprendre ensemble."),
  ...teach2("你也参加，怎么样？","Nǐ yě cānjiā, zěnmeyàng?","Tu veux te joindre à nous ?"),
  N("Demandez : est-ce que tu es en train d'apprendre le taiji ?"),TH(),
  C("你是不是正在学习太极拳？","Nǐ shì bu shì zhèngzài xuéxí tàijíquán?","Est-ce que tu es en train d'apprendre le taiji ?",.66),HOLD(),
  N("Répondez : oui, tu veux te joindre à nous ?"),TH(),
  C("是啊。你也参加，怎么样？","Shì a. Nǐ yě cānjiā, zěnmeyàng?","Oui. Tu veux te joindre à nous ?",.66),HOLD(),
  N("Dites : nous pouvons apprendre ensemble."),TH(),
  C("我们可以一起学。","Wǒmen kěyǐ yìqǐ xué.","Nous pouvons apprendre ensemble.",.66),HOLD(),
    ];}},

  {num:10,hanzi:"爱好明星",title:"Présenter le talent d’un ami",desc:"最有名 · 明星 · 说得很好",
    build(){return[
  N("Leçon 10. Écoutez le dialogue cible. Vous allez présenter une personne connue pour son talent, comme dans les activités du support."),
  C("你们班的运动明星是谁？","Nǐmen bān de yùndòng míngxīng shì shéi?","Qui est la vedette sportive de votre classe ?",.62),
  C("是李伟。他跑得特别快。","Shì Lǐ Wěi. Tā pǎo de tèbié kuài.","C'est Li Wei. Il court particulièrement vite.",.62),
  N("[[明星|míngxīng]] désigne une star ou la personne remarquable dans un groupe. Le talent suit avec la structure déjà vue : verbe plus 得."),
  ...teach2("我们班最有名的运动员是王老师。","Wǒmen bān zuì yǒumíng de yùndòngyuán shì Wáng lǎoshī.","L'athlète le plus connu de notre classe est le professeur Wang."),
  ...teach2("她说汉语说得很好。","Tā shuō Hànyǔ shuō de hěn hǎo.","Elle parle très bien chinois."),
  ...teach2("我的朋友喜欢摄影，照片拍得特别好。","Wǒ de péngyou xǐhuan shèyǐng, zhàopiàn pāi de tèbié hǎo.","Mon ami aime la photographie et prend des photos particulièrement réussies."),
  N("Demandez : qui est la vedette sportive de votre classe ?"),TH(),
  C("你们班的运动明星是谁？","Nǐmen bān de yùndòng míngxīng shì shéi?","Qui est la vedette sportive de votre classe ?",.66),HOLD(),
  N("Répondez : c'est Li Wei. Il court particulièrement vite."),TH(),
  C("是李伟。他跑得特别快。","Shì Lǐ Wěi. Tā pǎo de tèbié kuài.","C'est Li Wei. Il court particulièrement vite.",.66),HOLD(),
  N("Dites : elle parle très bien chinois."),TH(),
  C("她说汉语说得很好。","Tā shuō Hànyǔ shuō de hěn hǎo.","Elle parle très bien chinois.",.66),HOLD(),
    ];}},

  {num:11,hanzi:"聊爱好",title:"Conversation guidée sur les loisirs",desc:"Questionner, répondre, comparer et proposer",
    build(){return[
  N("Leçon 11. Écoutez le dialogue cible en entier. Vous allez jouer les deux personnes après avoir travaillé chaque réplique."),
  C("你的爱好是什么？","Nǐ de àihào shì shénme?","Quel est ton loisir ?",.62),
  C("我喜欢看书和摄影。你呢？","Wǒ xǐhuan kàn shū hé shèyǐng. Nǐ ne?","J'aime lire et faire de la photographie. Et toi ?",.62),
  C("我最喜欢跑步，还喜欢听音乐。","Wǒ zuì xǐhuan pǎobù, hái xǐhuan tīng yīnyuè.","J'aime surtout courir, et j'aime aussi écouter de la musique.",.62),
  C("周末一起去跑步，好吗？","Zhōumò yìqǐ qù pǎobù, hǎo ma?","On va courir ensemble ce week-end ?",.62),
  C("好啊。","Hǎo a.","Bonne idée !",.62),
  N("Jouez la première personne. Dites : quel est ton loisir ?"),TH(),
  C("你的爱好是什么？","Nǐ de àihào shì shénme?","Quel est ton loisir ?",.66),HOLD(),
  N("Répondez : j'aime lire et faire de la photographie. Et toi ?"),TH(),
  C("我喜欢看书和摄影。你呢？","Wǒ xǐhuan kàn shū hé shèyǐng. Nǐ ne?","J'aime lire et faire de la photographie. Et toi ?",.66),HOLD(),
  N("Dites : j'aime surtout courir, et j'aime aussi écouter de la musique."),TH(),
  C("我最喜欢跑步，还喜欢听音乐。","Wǒ zuì xǐhuan pǎobù, hái xǐhuan tīng yīnyuè.","J'aime surtout courir, et j'aime aussi écouter de la musique.",.66),HOLD(),
  N("Proposez : on va courir ensemble ce week-end ?"),TH(),
  C("周末一起去跑步，好吗？","Zhōumò yìqǐ qù pǎobù, hǎo ma?","On va courir ensemble ce week-end ?",.66),HOLD(),
  N("Acceptez. Dites : bonne idée !"),TH(),
  C("好啊。","Hǎo a.","Bonne idée !",.66),HOLD(),
    ];}},

  {num:12,hanzi:"总复习",title:"Mission finale : parler de vos loisirs",desc:"Entretien complet : loisir, fréquence, sport, niveau et projet",
    build(){return[
  N("Mission finale. Écoutez l'entretien cible. Vous allez pouvoir l'adapter à votre propre vie, sans traduire mot à mot."),
  C("你的爱好是什么？","Nǐ de àihào shì shénme?","Quel est ton loisir ?",.62),
  C("我喜欢看书，也喜欢听音乐。","Wǒ xǐhuan kàn shū, yě xǐhuan tīng yīnyuè.","J'aime lire et aussi écouter de la musique.",.62),
  C("你经常跑步吗？","Nǐ jīngcháng pǎobù ma?","Est-ce que tu cours souvent ?",.62),
  C("我有时候跑步。周末我要去操场跑步。","Wǒ yǒushíhou pǎobù. Zhōumò wǒ yào qù cāochǎng pǎobù.","Je cours parfois. Ce week-end, je vais courir sur le terrain de sport.",.62),
  C("你跑得怎么样？","Nǐ pǎo de zěnmeyàng?","Comment cours-tu ?",.62),
  C("我跑得不太快，但是我很喜欢。","Wǒ pǎo de bú tài kuài, dànshì wǒ hěn xǐhuan.","Je ne cours pas très vite, mais j'aime beaucoup ça.",.62),
  N("Jouez l'interlocuteur. Dites : quel est ton loisir ?"),TH(),
  C("你的爱好是什么？","Nǐ de àihào shì shénme?","Quel est ton loisir ?",.66),HOLD(),
  N("Répondez : j'aime lire et aussi écouter de la musique."),TH(),
  C("我喜欢看书，也喜欢听音乐。","Wǒ xǐhuan kàn shū, yě xǐhuan tīng yīnyuè.","J'aime lire et aussi écouter de la musique.",.66),HOLD(),
  N("Demandez : est-ce que tu cours souvent ?"),TH(),
  C("你经常跑步吗？","Nǐ jīngcháng pǎobù ma?","Est-ce que tu cours souvent ?",.66),HOLD(),
  N("Répondez : je cours parfois. Ce week-end, je vais courir sur le terrain de sport."),TH(),
  C("我有时候跑步。周末我要去操场跑步。","Wǒ yǒushíhou pǎobù. Zhōumò wǒ yào qù cāochǎng pǎobù.","Je cours parfois. Ce week-end, je vais courir sur le terrain de sport.",.66),HOLD(),
  N("Demandez : comment cours-tu ?"),TH(),
  C("你跑得怎么样？","Nǐ pǎo de zěnmeyàng?","Comment cours-tu ?",.66),HOLD(),
  N("Répondez : je ne cours pas très vite, mais j'aime beaucoup ça."),TH(),
  C("我跑得不太快，但是我很喜欢。","Wǒ pǎo de bú tài kuài, dànshì wǒ hěn xǐhuan.","Je ne cours pas très vite, mais j'aime beaucoup ça.",.66),HOLD(),
  N("Bravo. Rejouez demain les dialogues des leçons 11 et 12 en remplaçant les activités par celles que vous aimez vraiment."),
  C("再见！","Zàijiàn!","Au revoir !",.66),
    ];}}
  ]
});
