/* ============================================================
   Chapitre Bonus 8 · 谈天气和季节 — La météo et les saisons
   Adapté du support « 谈天气 ». Chaque mot est introduit dans
   une situation utile, puis réemployé dans un dialogue.
   ============================================================ */
registerChapter({
  group:"bonus", id:"08-weather", badge:"★8", star:true,
  hanzi:"谈天气和季节", title:"Bonus 8 · La météo et les saisons",
  desc:"Saisons, prévisions, température et projets selon le temps — 12 leçons",
  intro:"Douze leçons pour parler naturellement du temps qu'il fait, comprendre une prévision, prévoir une sortie et réagir quand le temps change. Chaque leçon commence par un dialogue à comprendre et à rejouer.",
  lessons:[

  {num:1,hanzi:"春天暖和",title:"Nommer les saisons",desc:"春天 · 夏天 · 秋天 · 冬天 · 暖和",
    build(){return[
  N("Leçon 1. Écoutez le dialogue cible. Vous allez pouvoir demander la saison et décrire le printemps."),
  C("现在是什么季节？","Xiànzài shì shénme jìjié?","Quelle saison est-ce en ce moment ?",.62),
  C("现在是春天，天气很暖和。","Xiànzài shì chūntiān, tiānqì hěn nuǎnhuo.","C'est le printemps ; il fait doux.",.62),
  N("[[季节|jìjié]] est une saison. En chinois, on donne naturellement la saison, puis on décrit le temps."),
  ...teach2("春天常常很暖和。","Chūntiān chángcháng hěn nuǎnhuo.","Au printemps, il fait souvent doux."),
  ...teach2("春天到了，公园里的花开了。","Chūntiān dào le, gōngyuán lǐ de huā kāi le.","Le printemps est arrivé ; les fleurs du parc ont éclos."),
  ...teach2("今天暖和，我们去公园散步吧。","Jīntiān nuǎnhuo, wǒmen qù gōngyuán sànbù ba.","Il fait doux aujourd'hui ; allons nous promener au parc."),
  N("Demandez : quelle saison est-ce en ce moment ?"),TH(),
  C("现在是什么季节？","Xiànzài shì shénme jìjié?","Quelle saison est-ce en ce moment ?",.66),HOLD(),
  N("Répondez : c'est le printemps ; il fait doux."),TH(),
  C("现在是春天，天气很暖和。","Xiànzài shì chūntiān, tiānqì hěn nuǎnhuo.","C'est le printemps ; il fait doux.",.66),HOLD(),
  N("Dites : il fait doux aujourd'hui, allons nous promener au parc."),TH(),
  C("今天暖和，我们去公园散步吧。","Jīntiān nuǎnhuo, wǒmen qù gōngyuán sànbù ba.","Il fait doux aujourd'hui ; allons nous promener au parc.",.66),HOLD(),
    ];}},

  {num:2,hanzi:"夏天很热",title:"Décrire le temps selon la saison",desc:"热 · 凉快 · 冷 · 常常",
    build(){return[
  N("Leçon 2. Écoutez le dialogue cible. Vous allez comparer naturellement l'été et l'hiver."),
  C("夏天天气怎么样？","Xiàtiān tiānqì zěnmeyàng?","Quel temps fait-il en été ?",.62),
  C("夏天很热，冬天很冷。","Xiàtiān hěn rè, dōngtiān hěn lěng.","En été, il fait chaud ; en hiver, il fait froid.",.62),
  N("[[热|rè]] est chaud et [[冷|lěng]] est froid. Pour l'automne, on emploie souvent [[凉快|liángkuai]], agréablement frais."),
  ...teach2("秋天很凉快，不冷也不热。","Qiūtiān hěn liángkuai, bù lěng yě bù rè.","En automne, il fait agréablement frais, ni froid ni chaud."),
  ...teach2("夏天常常有三十多度。","Xiàtiān chángcháng yǒu sānshí duō dù.","En été, il fait souvent plus de trente degrés."),
  ...teach2("冬天太冷了，我想在家喝热茶。","Dōngtiān tài lěng le, wǒ xiǎng zài jiā hē rè chá.","Il fait trop froid en hiver ; j'ai envie de boire du thé chaud à la maison."),
  N("Demandez quel temps il fait en été."),TH(),
  C("夏天天气怎么样？","Xiàtiān tiānqì zěnmeyàng?","Quel temps fait-il en été ?",.66),HOLD(),
  N("Répondez : en été il fait chaud, en hiver il fait froid."),TH(),
  C("夏天很热，冬天很冷。","Xiàtiān hěn rè, dōngtiān hěn lěng.","En été, il fait chaud ; en hiver, il fait froid.",.66),HOLD(),
  N("Dites : en automne, il fait agréablement frais, ni froid ni chaud."),TH(),
  C("秋天很凉快，不冷也不热。","Qiūtiān hěn liángkuai, bù lěng yě bù rè.","En automne, il fait agréablement frais, ni froid ni chaud.",.66),HOLD(),
    ];}},

  {num:3,hanzi:"晴天阴天",title:"Dire le temps qu’il fait",desc:"晴 · 阴 · 多云 · 天气怎么样",
    build(){return[
  N("Leçon 3. Voici le dialogue cible. Vous allez reconnaître et décrire un temps ensoleillé, couvert ou nuageux."),
  C("今天天气怎么样？","Jīntiān tiānqì zěnmeyàng?","Quel temps fait-il aujourd'hui ?",.62),
  C("今天是晴天，不过有点儿多云。","Jīntiān shì qíngtiān, búguò yǒudiǎnr duōyún.","Il fait beau aujourd'hui, mais le ciel est un peu nuageux.",.62),
  N("[[晴|qíng]] signifie beau, ensoleillé. [[阴|yīn]] signifie couvert. [[多云|duōyún]] veut dire nuageux, sans dire qu'il pleut."),
  ...teach2("上午是晴天，下午可能多云。","Shàngwǔ shì qíngtiān, xiàwǔ kěnéng duōyún.","Le matin sera ensoleillé ; l'après-midi, il sera peut-être nuageux."),
  ...teach2("天阴了，房间里有点儿暗。","Tiān yīn le, fángjiān lǐ yǒudiǎnr àn.","Le ciel s'est couvert ; la pièce est un peu sombre."),
  ...teach2("虽然多云，但是不下雨。","Suīrán duōyún, dànshì bù xiàyǔ.","Même s'il y a des nuages, il ne pleut pas."),
  N("Demandez : quel temps fait-il aujourd'hui ?"),TH(),
  C("今天天气怎么样？","Jīntiān tiānqì zěnmeyàng?","Quel temps fait-il aujourd'hui ?",.66),HOLD(),
  N("Répondez : il fait beau, mais le ciel est un peu nuageux."),TH(),
  C("今天是晴天，不过有点儿多云。","Jīntiān shì qíngtiān, búguò yǒudiǎnr duōyún.","Il fait beau aujourd'hui, mais le ciel est un peu nuageux.",.66),HOLD(),
  N("Dites : le ciel s'est couvert ; la pièce est un peu sombre."),TH(),
  C("天阴了，房间里有点儿暗。","Tiān yīn le, fángjiān lǐ yǒudiǎnr àn.","Le ciel s'est couvert ; la pièce est un peu sombre.",.66),HOLD(),
    ];}},

  {num:4,hanzi:"下雨下雪",title:"Parler de pluie, neige et vent",desc:"下雨 · 下雪 · 刮风 · 大雨",
    build(){return[
  N("Leçon 4. Écoutez le dialogue cible. Vous allez dire qu'il pleut et proposer une solution simple."),
  C("外面下雨了吗？","Wàimiàn xiàyǔ le ma?","Est-ce qu'il pleut dehors ?",.62),
  C("下大雨了，别忘了带伞。","Xià dà yǔ le, bié wàng le dài sǎn.","Il pleut fort ; n'oublie pas de prendre un parapluie.",.62),
  N("Avec [[下|xià]], on dit [[下雨|xiàyǔ]], pleuvoir, et [[下雪|xiàxuě]], neiger. Pour le vent, on dit [[刮风|guāfēng]]."),
  ...teach2("昨天晚上下了一场大雨。","Zuótiān wǎnshang xià le yì chǎng dà yǔ.","Hier soir, il y a eu une forte pluie."),
  ...teach2("北京冬天有时候下雪。","Běijīng dōngtiān yǒushíhou xiàxuě.","À Pékin, il neige parfois en hiver."),
  ...teach2("今天风很大，出去的时候多穿一点儿。","Jīntiān fēng hěn dà, chūqù de shíhou duō chuān yìdiǎnr.","Il y a beaucoup de vent aujourd'hui ; habille-toi un peu plus chaudement en sortant."),
  N("Demandez : est-ce qu'il pleut dehors ?"),TH(),
  C("外面下雨了吗？","Wàimiàn xiàyǔ le ma?","Est-ce qu'il pleut dehors ?",.66),HOLD(),
  N("Répondez : il pleut fort, n'oublie pas de prendre un parapluie."),TH(),
  C("下大雨了，别忘了带伞。","Xià dà yǔ le, bié wàng le dài sǎn.","Il pleut fort ; n'oublie pas de prendre un parapluie.",.66),HOLD(),
  N("Dites : à Pékin, il neige parfois en hiver."),TH(),
  C("北京冬天有时候下雪。","Běijīng dōngtiān yǒushíhou xiàxuě.","À Pékin, il neige parfois en hiver.",.66),HOLD(),
    ];}},

  {num:5,hanzi:"明天会下雨吗",title:"Comprendre une prévision simple",desc:"明天 · 后天 · 会 · 天气预报",
    build(){return[
  N("Leçon 5. Écoutez le dialogue cible. Vous allez demander le temps de demain et citer une prévision."),
  C("明天会下雨吗？","Míngtiān huì xiàyǔ ma?","Est-ce qu'il va pleuvoir demain ?",.62),
  C("天气预报说，明天会下雨。","Tiānqì yùbào shuō, míngtiān huì xiàyǔ.","La météo annonce qu'il va pleuvoir demain.",.62),
  N("[[会|huì]] sert ici à annoncer ce qui devrait arriver. [[天气预报|tiānqì yùbào]] est le bulletin météo ou la météo."),
  ...teach2("后天是晴天，适合去爬山。","Hòutiān shì qíngtiān, shìhé qù páshān.","Après-demain, il fera beau : ce sera bien pour aller faire de la randonnée."),
  ...teach2("大后天可能降温。","Dàhòutiān kěnéng jiàngwēn.","Dans trois jours, la température pourrait baisser."),
  ...teach2("天气预报说下午有风，你带一件外套吧。","Tiānqì yùbào shuō xiàwǔ yǒu fēng, nǐ dài yí jiàn wàitào ba.","La météo annonce du vent l'après-midi ; prends une veste."),
  N("Demandez : est-ce qu'il va pleuvoir demain ?"),TH(),
  C("明天会下雨吗？","Míngtiān huì xiàyǔ ma?","Est-ce qu'il va pleuvoir demain ?",.66),HOLD(),
  N("Répondez : la météo annonce qu'il va pleuvoir demain."),TH(),
  C("天气预报说，明天会下雨。","Tiānqì yùbào shuō, míngtiān huì xiàyǔ.","La météo annonce qu'il va pleuvoir demain.",.66),HOLD(),
  N("Dites : après-demain il fera beau, ce sera bien pour aller faire de la randonnée."),TH(),
  C("后天是晴天，适合去爬山。","Hòutiān shì qíngtiān, shìhé qù páshān.","Après-demain, il fera beau : ce sera bien pour aller faire de la randonnée.",.66),HOLD(),
    ];}},

  {num:6,hanzi:"三十六度",title:"Parler de température",desc:"度 · 气温 · 最高 · 最低",
    build(){return[
  N("Leçon 6. Écoutez le dialogue cible. Vous allez comprendre une température et demander s'il fera chaud."),
  C("明天最高气温多少度？","Míngtiān zuìgāo qìwēn duōshao dù?","Quelle sera la température maximale demain ?",.62),
  C("最高三十六度，天气会很热。","Zuìgāo sānshíliù dù, tiānqì huì hěn rè.","Elle sera de trente-six degrés au maximum ; il fera très chaud.",.62),
  N("[[度|dù]] est le degré. [[气温|qìwēn]] est la température ; [[最高|zuìgāo]] et [[最低|zuìdī]] indiquent le maximum et le minimum."),
  ...teach2("今天的气温是二十度左右。","Jīntiān de qìwēn shì èrshí dù zuǒyòu.","La température est d'environ vingt degrés aujourd'hui."),
  ...teach2("晚上最低气温只有五度。","Wǎnshang zuìdī qìwēn zhǐyǒu wǔ dù.","La température minimale ne sera que de cinq degrés ce soir."),
  ...teach2("白天和晚上温差很大。","Báitiān hé wǎnshang wēnchā hěn dà.","L'écart de température entre le jour et la nuit est important."),
  N("Demandez quelle sera la température maximale demain."),TH(),
  C("明天最高气温多少度？","Míngtiān zuìgāo qìwēn duōshao dù?","Quelle sera la température maximale demain ?",.66),HOLD(),
  N("Répondez : trente-six degrés au maximum, il fera très chaud."),TH(),
  C("最高三十六度，天气会很热。","Zuìgāo sānshíliù dù, tiānqì huì hěn rè.","Elle sera de trente-six degrés au maximum ; il fera très chaud.",.66),HOLD(),
  N("Dites : ce soir, la température minimale ne sera que de cinq degrés."),TH(),
  C("晚上最低气温只有五度。","Wǎnshang zuìdī qìwēn zhǐyǒu wǔ dù.","La température minimale ne sera que de cinq degrés ce soir.",.66),HOLD(),
    ];}},

  {num:7,hanzi:"好像要下雨",title:"Exprimer une impression",desc:"好像 · 要 · 变天",
    build(){return[
  N("Leçon 7. Écoutez le dialogue cible. Vous allez dire ce que les nuages vous font penser."),
  C("天阴了，好像要下雨。","Tiān yīn le, hǎoxiàng yào xiàyǔ.","Le ciel s'est couvert ; on dirait qu'il va pleuvoir.",.62),
  C("那我先回家拿伞。","Nà wǒ xiān huí jiā ná sǎn.","Alors, je vais d'abord rentrer chercher un parapluie.",.62),
  N("[[好像|hǎoxiàng]] veut dire « on dirait » ou « il semble que ». Il exprime une impression, pas une certitude."),
  ...teach2("外面好像很冷，你穿暖和一点儿吧。","Wàimiàn hǎoxiàng hěn lěng, nǐ chuān nuǎnhuo yìdiǎnr ba.","Il semble qu'il fasse froid dehors ; habille-toi un peu plus chaudement."),
  ...teach2("风越来越大了，好像要变天。","Fēng yuèláiyuè dà le, hǎoxiàng yào biàntiān.","Le vent devient de plus en plus fort ; on dirait que le temps va changer."),
  ...teach2("看那边的云，马上要下雨了。","Kàn nàbiān de yún, mǎshàng yào xiàyǔ le.","Regarde les nuages là-bas : il va bientôt pleuvoir."),
  N("Dites : le ciel s'est couvert, on dirait qu'il va pleuvoir."),TH(),
  C("天阴了，好像要下雨。","Tiān yīn le, hǎoxiàng yào xiàyǔ.","Le ciel s'est couvert ; on dirait qu'il va pleuvoir.",.66),HOLD(),
  N("Répondez : alors je vais d'abord rentrer chercher un parapluie."),TH(),
  C("那我先回家拿伞。","Nà wǒ xiān huí jiā ná sǎn.","Alors, je vais d'abord rentrer chercher un parapluie.",.66),HOLD(),
  N("Dites : le vent devient de plus en plus fort, on dirait que le temps va changer."),TH(),
  C("风越来越大了，好像要变天。","Fēng yuèláiyuè dà le, hǎoxiàng yào biàntiān.","Le vent devient de plus en plus fort ; on dirait que le temps va changer.",.66),HOLD(),
    ];}},

  {num:8,hanzi:"一会儿晴一会儿雨",title:"Décrire un temps changeant",desc:"一会儿…一会儿… · 突然 · 常常",
    build(){return[
  N("Leçon 8. Écoutez le dialogue cible. Vous allez décrire un temps qui change sans arrêt."),
  C("今天天气真奇怪。","Jīntiān tiānqì zhēn qíguài.","Le temps est vraiment bizarre aujourd'hui.",.62),
  C("一会儿晴，一会儿下雨。","Yíhuǐr qíng, yíhuǐr xiàyǔ.","Un moment il fait beau, un moment il pleut.",.62),
  N("La structure [[一会儿…一会儿…|yíhuǐr…yíhuǐr…]] alterne deux situations : un moment ceci, un moment cela."),
  ...teach2("春天的天气常常一会儿冷，一会儿暖和。","Chūntiān de tiānqì chángcháng yíhuǐr lěng, yíhuǐr nuǎnhuo.","Au printemps, le temps est souvent tantôt froid, tantôt doux."),
  ...teach2("刚才还是晴天，突然下起雨来了。","Gāngcái háishi qíngtiān, tūrán xià qǐ yǔ lái le.","Il faisait encore beau il y a un instant, puis il s'est soudain mis à pleuvoir."),
  ...teach2("天气变化太快了，出门最好带伞。","Tiānqì biànhuà tài kuài le, chūmén zuìhǎo dài sǎn.","Le temps change trop vite ; il vaut mieux prendre un parapluie en sortant."),
  N("Dites : un moment il fait beau, un moment il pleut."),TH(),
  C("一会儿晴，一会儿下雨。","Yíhuǐr qíng, yíhuǐr xiàyǔ.","Un moment il fait beau, un moment il pleut.",.66),HOLD(),
  N("Dites : il faisait encore beau il y a un instant, puis il s'est soudain mis à pleuvoir."),TH(),
  C("刚才还是晴天，突然下起雨来了。","Gāngcái háishi qíngtiān, tūrán xià qǐ yǔ lái le.","Il faisait encore beau il y a un instant, puis il s'est soudain mis à pleuvoir.",.66),HOLD(),
  N("Conseil à votre ami : le temps change trop vite, il vaut mieux prendre un parapluie en sortant."),TH(),
  C("天气变化太快了，出门最好带伞。","Tiānqì biànhuà tài kuài le, chūmén zuìhǎo dài sǎn.","Le temps change trop vite ; il vaut mieux prendre un parapluie en sortant.",.66),HOLD(),
    ];}},

  {num:9,hanzi:"下雨怎么办",title:"Adapter un projet à la météo",desc:"打算 · 如果 · 就 · 改天",
    build(){return[
  N("Leçon 9. Écoutez le dialogue cible. Vous allez maintenir ou reporter une sortie selon la météo."),
  C("明天你打算去爬山吗？","Míngtiān nǐ dǎsuàn qù páshān ma?","Tu prévois d'aller faire de la randonnée demain ?",.62),
  C("如果不下雨，我就去。","Rúguǒ bù xiàyǔ, wǒ jiù qù.","S'il ne pleut pas, j'irai.",.62),
  N("[[打算|dǎsuàn]] signifie prévoir. La structure [[如果…就…|rúguǒ…jiù…]] relie une condition et sa conséquence."),
  ...teach2("如果明天是晴天，我们就去公园野餐。","Rúguǒ míngtiān shì qíngtiān, wǒmen jiù qù gōngyuán yěcān.","S'il fait beau demain, nous irons pique-niquer au parc."),
  ...teach2("如果下大雨，我们改天再去吧。","Rúguǒ xià dà yǔ, wǒmen gǎitiān zài qù ba.","S'il pleut fort, remettons cela à un autre jour."),
  ...teach2("天气太热了，我打算晚上再出去跑步。","Tiānqì tài rè le, wǒ dǎsuàn wǎnshang zài chūqù pǎobù.","Il fait trop chaud ; je prévois de sortir courir seulement ce soir."),
  N("Demandez : tu prévois d'aller faire de la randonnée demain ?"),TH(),
  C("明天你打算去爬山吗？","Míngtiān nǐ dǎsuàn qù páshān ma?","Tu prévois d'aller faire de la randonnée demain ?",.66),HOLD(),
  N("Répondez : s'il ne pleut pas, j'irai."),TH(),
  C("如果不下雨，我就去。","Rúguǒ bù xiàyǔ, wǒ jiù qù.","S'il ne pleut pas, j'irai.",.66),HOLD(),
  N("Dites : s'il pleut fort, remettons cela à un autre jour."),TH(),
  C("如果下大雨，我们改天再去吧。","Rúguǒ xià dà yǔ, wǒmen gǎitiān zài qù ba.","S'il pleut fort, remettons cela à un autre jour.",.66),HOLD(),
    ];}},

  {num:10,hanzi:"北京和上海",title:"Comparer deux villes",desc:"比 · 更 · 温差 · 湿",
    build(){return[
  N("Leçon 10. Écoutez le dialogue cible. Vous allez comparer le temps de deux villes."),
  C("北京比上海冷吗？","Běijīng bǐ Shànghǎi lěng ma?","Pékin est-il plus froid que Shanghai ?",.62),
  C("冬天北京更冷，也更干。","Dōngtiān Běijīng gèng lěng, yě gèng gān.","En hiver, Pékin est plus froid et aussi plus sec.",.62),
  N("[[比|bǐ]] compare : A 比 B plus adjectif. [[更|gèng]] signifie encore plus. On peut comparer la température, le vent ou l'humidité."),
  ...teach2("哈尔滨比北京冷得多。","Hā'ěrbīn bǐ Běijīng lěng de duō.","Harbin est bien plus froid que Pékin."),
  ...teach2("上海夏天比北京湿一点儿。","Shànghǎi xiàtiān bǐ Běijīng shī yìdiǎnr.","En été, Shanghai est un peu plus humide que Pékin."),
  ...teach2("这两个城市白天的气温差不多。","Zhè liǎng ge chéngshì báitiān de qìwēn chàbuduō.","Dans ces deux villes, les températures de journée sont à peu près les mêmes."),
  N("Demandez : Pékin est-il plus froid que Shanghai ?"),TH(),
  C("北京比上海冷吗？","Běijīng bǐ Shànghǎi lěng ma?","Pékin est-il plus froid que Shanghai ?",.66),HOLD(),
  N("Répondez : en hiver, Pékin est plus froid et aussi plus sec."),TH(),
  C("冬天北京更冷，也更干。","Dōngtiān Běijīng gèng lěng, yě gèng gān.","En hiver, Pékin est plus froid et aussi plus sec.",.66),HOLD(),
  N("Dites : Harbin est bien plus froid que Pékin."),TH(),
  C("哈尔滨比北京冷得多。","Hā'ěrbīn bǐ Běijīng lěng de duō.","Harbin est bien plus froid que Pékin.",.66),HOLD(),
    ];}},

  {num:11,hanzi:"天气预报不准",title:"Réagir à une mauvaise prévision",desc:"准 · 一点儿也不 · 糟糕 · 没带伞",
    build(){return[
  N("Leçon 11. Écoutez le dialogue cible. Il reprend la scène du support : la prévision annonçait du soleil, mais il pleut."),
  C("天气预报说今天是晴天。","Tiānqì yùbào shuō jīntiān shì qíngtiān.","La météo annonçait du soleil aujourd'hui.",.62),
  C("可是外面下大雨了，真糟糕！","Kěshì wàimiàn xià dà yǔ le, zhēn zāogāo!","Mais il pleut fort dehors, quelle catastrophe !",.62),
  N("[[准|zhǔn]] veut dire exact. Avec [[一点儿也不|yìdiǎnr yě bù]], on insiste : pas du tout."),
  ...teach2("今天的天气预报一点儿也不准。","Jīntiān de tiānqì yùbào yìdiǎnr yě bù zhǔn.","La météo d'aujourd'hui n'est pas du tout exacte."),
  ...teach2("真糟糕，我没带伞。","Zhēn zāogāo, wǒ méi dài sǎn.","Quelle catastrophe, je n'ai pas pris de parapluie."),
  ...teach2("别着急，我有两把伞，我们一起走。","Bié zháojí, wǒ yǒu liǎng bǎ sǎn, wǒmen yìqǐ zǒu.","Ne t'inquiète pas, j'ai deux parapluies ; allons-y ensemble."),
  N("Dites : la météo annonçait du soleil aujourd'hui."),TH(),
  C("天气预报说今天是晴天。","Tiānqì yùbào shuō jīntiān shì qíngtiān.","La météo annonçait du soleil aujourd'hui.",.66),HOLD(),
  N("Réagissez : mais il pleut fort dehors, quelle catastrophe !"),TH(),
  C("可是外面下大雨了，真糟糕！","Kěshì wàimiàn xià dà yǔ le, zhēn zāogāo!","Mais il pleut fort dehors, quelle catastrophe !",.66),HOLD(),
  N("Rassurez votre ami : ne t'inquiète pas, j'ai deux parapluies, allons-y ensemble."),TH(),
  C("别着急，我有两把伞，我们一起走。","Bié zháojí, wǒ yǒu liǎng bǎ sǎn, wǒmen yìqǐ zǒu.","Ne t'inquiète pas, j'ai deux parapluies ; allons-y ensemble.",.66),HOLD(),
    ];}},

  {num:12,hanzi:"天气播报",title:"Faire votre propre bulletin météo",desc:"Prévision complète et dialogue final",
    build(){return[
  N("Mission finale. Écoutez le bulletin et le dialogue cible. À la fin, vous pourrez annoncer une météo puis adapter un projet."),
  C("明天上午晴天，最高气温二十八度。","Míngtiān shàngwǔ qíngtiān, zuìgāo qìwēn èrshíbā dù.","Demain matin, il fera beau ; la température maximale sera de vingt-huit degrés.",.62),
  C("下午多云，晚上可能下雨。","Xiàwǔ duōyún, wǎnshang kěnéng xiàyǔ.","L'après-midi sera nuageux et il pourrait pleuvoir le soir.",.62),
  C("那我们上午去公园，别忘了带伞。","Nà wǒmen shàngwǔ qù gōngyuán, bié wàng le dài sǎn.","Alors, allons au parc le matin et n'oublions pas de prendre un parapluie.",.62),
  N("Vous réunissez maintenant la saison, la prévision, la température et une décision pratique."),
  ...teach2("明天最低气温十五度，早晚有点儿凉。","Míngtiān zuìdī qìwēn shíwǔ dù, zǎowǎn yǒudiǎnr liáng.","Demain, la température minimale sera de quinze degrés ; il fera un peu frais le matin et le soir."),
  ...teach2("如果下午不下雨，我们就去跑步。","Rúguǒ xiàwǔ bù xiàyǔ, wǒmen jiù qù pǎobù.","S'il ne pleut pas l'après-midi, nous irons courir."),
  N("Jouez le présentateur météo. Dites : demain matin il fera beau, la température maximale sera de vingt-huit degrés."),TH(),
  C("明天上午晴天，最高气温二十八度。","Míngtiān shàngwǔ qíngtiān, zuìgāo qìwēn èrshíbā dù.","Demain matin, il fera beau ; la température maximale sera de vingt-huit degrés.",.66),HOLD(),
  N("Poursuivez le bulletin : l'après-midi sera nuageux, et il pourrait pleuvoir le soir."),TH(),
  C("下午多云，晚上可能下雨。","Xiàwǔ duōyún, wǎnshang kěnéng xiàyǔ.","L'après-midi sera nuageux et il pourrait pleuvoir le soir.",.66),HOLD(),
  N("Décidez du programme. Dites : alors allons au parc le matin et n'oublions pas de prendre un parapluie."),TH(),
  C("那我们上午去公园，别忘了带伞。","Nà wǒmen shàngwǔ qù gōngyuán, bié wàng le dài sǎn.","Alors, allons au parc le matin et n'oublions pas de prendre un parapluie.",.66),HOLD(),
  N("Bravo. Demain, refaites ce bulletin en remplaçant le temps, la température et votre activité par votre propre situation."),
  C("再见！","Zàijiàn!","Au revoir !",.66),
    ];}},
  ]
});
