/* ============================================================
   Chapitre Bonus 9 · 谈健康 — Parler de sa santé
   Adapté du support « 谈健康 ». Vocabulaire de santé courant,
   sans diagnostic ni conseil médical personnalisé.
   ============================================================ */
registerChapter({
  group:"bonus", id:"09-health", badge:"★9", star:true,
  hanzi:"谈健康", title:"Bonus 9 · Parler de sa santé",
  desc:"Douleurs, symptômes, médecin, médicaments et repos — 12 leçons",
  intro:"Douze leçons pour dire simplement ce qui ne va pas, expliquer depuis quand, comprendre les indications usuelles du médecin et rassurer un ami. Le cours apprend à communiquer ; en cas de problème médical réel, consultez un professionnel de santé.",
  lessons:[

  {num:1,hanzi:"哪儿不舒服",title:"Dire ce qui ne va pas",desc:"哪儿不舒服 · 疼 · 头 · 手",
    build(){return[
  N("Leçon 1. Écoutez le dialogue cible. Vous allez pouvoir demander à quelqu'un où il a mal et répondre simplement."),
  C("你哪儿不舒服？","Nǐ nǎr bù shūfu?","Qu'est-ce qui ne va pas ?",.62),
  C("我头疼。","Wǒ tóu téng.","J'ai mal à la tête.",.62),
  N("[[不舒服|bù shūfu]] signifie ne pas se sentir bien. Avec une partie du corps et [[疼|téng]], on dit où l'on a mal."),
  ...teach2("我今天不太舒服。","Wǒ jīntiān bú tài shūfu.","Je ne me sens pas très bien aujourd'hui."),
  ...teach2("她头很疼，想早点儿回家。","Tā tóu hěn téng, xiǎng zǎodiǎnr huí jiā.","Elle a très mal à la tête et voudrait rentrer tôt."),
  ...teach2("你哪儿疼？我肚子疼。","Nǐ nǎr téng? Wǒ dùzi téng.","Où as-tu mal ? J'ai mal au ventre."),
  ...teach2("我的手疼，今天不想拿东西。","Wǒ de shǒu téng, jīntiān bù xiǎng ná dōngxi.","J'ai mal à la main ; je ne veux pas porter de choses aujourd'hui."),
  N("Demandez : qu'est-ce qui ne va pas ?"),TH(),
  C("你哪儿不舒服？","Nǐ nǎr bù shūfu?","Qu'est-ce qui ne va pas ?",.66),HOLD(),
  N("Répondez : j'ai mal à la tête."),TH(),
  C("我头疼。","Wǒ tóu téng.","J'ai mal à la tête.",.66),HOLD(),
  N("Dites : je ne me sens pas très bien aujourd'hui."),TH(),
  C("我今天不太舒服。","Wǒ jīntiān bú tài shūfu.","Je ne me sens pas très bien aujourd'hui.",.66),HOLD(),
    ];}},

  {num:2,hanzi:"嗓子疼",title:"Préciser la partie du corps",desc:"鼻子 · 嗓子 · 肚子 · 胳膊 · 腿 · 脚",
    build(){return[
  N("Leçon 2. Écoutez le dialogue cible. Vous allez dire clairement si vous avez mal à la gorge ou à une autre partie du corps."),
  C("你嗓子疼吗？","Nǐ sǎngzi téng ma?","As-tu mal à la gorge ?",.62),
  C("有一点儿疼，也有点儿咳嗽。","Yǒu yìdiǎnr téng, yě yǒudiǎnr késou.","J'ai un peu mal, et je tousse aussi un peu.",.62),
  N("[[嗓子|sǎngzi]] est la gorge. [[肚子|dùzi]] est le ventre. Les autres mots servent à être précis sans faire de liste abstraite."),
  ...teach2("我昨天跑步以后腿疼。","Wǒ zuótiān pǎobù yǐhòu tuǐ téng.","J'ai mal aux jambes après avoir couru hier."),
  ...teach2("他的胳膊疼，今天不能打球。","Tā de gēbo téng, jīntiān bù néng dǎ qiú.","Il a mal au bras ; il ne peut pas jouer au ballon aujourd'hui."),
  ...teach2("我走了很长时间，脚有点儿疼。","Wǒ zǒu le hěn cháng shíjiān, jiǎo yǒudiǎnr téng.","J'ai marché longtemps ; j'ai un peu mal aux pieds."),
  ...teach2("我的鼻子不舒服，一直流鼻涕。","Wǒ de bízi bù shūfu, yìzhí liú bítì.","Mon nez me gêne ; il coule sans arrêt."),
  N("Demandez : as-tu mal à la gorge ?"),TH(),
  C("你嗓子疼吗？","Nǐ sǎngzi téng ma?","As-tu mal à la gorge ?",.66),HOLD(),
  N("Répondez : j'ai un peu mal et je tousse aussi un peu."),TH(),
  C("有一点儿疼，也有点儿咳嗽。","Yǒu yìdiǎnr téng, yě yǒudiǎnr késou.","J'ai un peu mal, et je tousse aussi un peu.",.66),HOLD(),
  N("Dites : j'ai marché longtemps ; j'ai un peu mal aux pieds."),TH(),
  C("我走了很长时间，脚有点儿疼。","Wǒ zǒu le hěn cháng shíjiān, jiǎo yǒudiǎnr téng.","J'ai marché longtemps ; j'ai un peu mal aux pieds.",.66),HOLD(),
    ];}},

  {num:3,hanzi:"感冒了",title:"Nommer les symptômes courants",desc:"感冒 · 发烧 · 咳嗽 · 流鼻涕 · 打喷嚏",
    build(){return[
  N("Leçon 3. Écoutez le dialogue cible. Vous allez dire que vous avez un rhume et décrire deux symptômes."),
  C("你感冒了吗？","Nǐ gǎnmào le ma?","As-tu attrapé un rhume ?",.62),
  C("好像感冒了，我发烧，还咳嗽。","Hǎoxiàng gǎnmào le, wǒ fāshāo, hái késou.","On dirait que j'ai un rhume : j'ai de la fièvre et je tousse.",.62),
  N("[[感冒|gǎnmào]] est un rhume. Les symptômes se mettent simplement l'un après l'autre : [[发烧|fāshāo]], avoir de la fièvre ; [[咳嗽|késou]], tousser."),
  ...teach2("我不发烧，但是一直流鼻涕。","Wǒ bù fāshāo, dànshì yìzhí liú bítì.","Je n'ai pas de fièvre, mais j'ai le nez qui coule sans arrêt."),
  ...teach2("她一直打喷嚏，可能感冒了。","Tā yìzhí dǎ pēntì, kěnéng gǎnmào le.","Elle éternue sans arrêt ; elle a peut-être attrapé un rhume."),
  ...teach2("我咳嗽得很厉害，今天不想出去。","Wǒ késou de hěn lìhai, jīntiān bù xiǎng chūqù.","Je tousse beaucoup ; je ne veux pas sortir aujourd'hui."),
  ...teach2("感冒的症状有咳嗽、发烧和流鼻涕。","Gǎnmào de zhèngzhuàng yǒu késou, fāshāo hé liú bítì.","Les symptômes d'un rhume comprennent la toux, la fièvre et le nez qui coule."),
  ...teach2("他生病了，今天在家休息。","Tā shēng bìng le, jīntiān zài jiā xiūxi.","Il est malade ; il se repose à la maison aujourd'hui."),
  N("Demandez : as-tu attrapé un rhume ?"),TH(),
  C("你感冒了吗？","Nǐ gǎnmào le ma?","As-tu attrapé un rhume ?",.66),HOLD(),
  N("Répondez : on dirait que oui, j'ai de la fièvre et je tousse."),TH(),
  C("好像感冒了，我发烧，还咳嗽。","Hǎoxiàng gǎnmào le, wǒ fāshāo, hái késou.","On dirait que j'ai un rhume : j'ai de la fièvre et je tousse.",.66),HOLD(),
  N("Dites : je n'ai pas de fièvre, mais j'ai le nez qui coule sans arrêt."),TH(),
  C("我不发烧，但是一直流鼻涕。","Wǒ bù fāshāo, dànshì yìzhí liú bítì.","Je n'ai pas de fièvre, mais j'ai le nez qui coule sans arrêt.",.66),HOLD(),
    ];}},

  {num:4,hanzi:"什么时候开始的",title:"Dire depuis quand cela a commencé",desc:"什么时候 · 开始 · 今天早上 · 昨天晚上",
    build(){return[
  N("Leçon 4. Écoutez le dialogue cible. Vous allez expliquer depuis quand un symptôme a commencé."),
  C("什么时候开始的？","Shénme shíhou kāishǐ de?","Quand est-ce que cela a commencé ?",.62),
  C("今天早上开始的。","Jīntiān zǎoshang kāishǐ de.","Ça a commencé ce matin.",.62),
  N("Dans cette question, la construction shì…de sert à demander le moment précis d'un fait passé. La réponse garde souvent seulement le moment et [[开始的]]."),
  ...teach2("我是昨天晚上开始不舒服的。","Wǒ shì zuótiān wǎnshang kāishǐ bù shūfu de.","J'ai commencé à ne pas me sentir bien hier soir."),
  ...teach2("我下午开始头疼的，现在好多了。","Wǒ xiàwǔ kāishǐ tóu téng de, xiànzài hǎo duō le.","J'ai commencé à avoir mal à la tête cet après-midi ; ça va beaucoup mieux maintenant."),
  ...teach2("你是什么时候感冒的？","Nǐ shì shénme shíhou gǎnmào de?","Quand as-tu attrapé ton rhume ?"),
  N("Demandez : quand est-ce que cela a commencé ?"),TH(),
  C("什么时候开始的？","Shénme shíhou kāishǐ de?","Quand est-ce que cela a commencé ?",.66),HOLD(),
  N("Répondez : ça a commencé ce matin."),TH(),
  C("今天早上开始的。","Jīntiān zǎoshang kāishǐ de.","Ça a commencé ce matin.",.66),HOLD(),
  N("Dites : j'ai commencé à ne pas me sentir bien hier soir."),TH(),
  C("我是昨天晚上开始不舒服的。","Wǒ shì zuótiān wǎnshang kāishǐ bù shūfu de.","J'ai commencé à ne pas me sentir bien hier soir.",.66),HOLD(),
    ];}},

  {num:5,hanzi:"去看医生",title:"Parler d’une consultation",desc:"医院 · 看病 · 看医生 · 陪",
    build(){return[
  N("Leçon 5. Écoutez le dialogue cible. Vous allez demander à un ami s'il est allé à l'hôpital et proposer de l'accompagner."),
  C("你去医院了吗？","Nǐ qù yīyuàn le ma?","Es-tu allé à l'hôpital ?",.62),
  C("还没有，你陪我去吧。","Hái méiyǒu, nǐ péi wǒ qù ba.","Pas encore. Accompagne-moi, s'il te plaît.",.62),
  N("[[医院|yīyuàn]] est l'hôpital. [[看医生|kàn yīshēng]] signifie consulter un médecin. [[陪|péi]] est accompagner quelqu'un."),
  ...teach2("我下午去医院看医生。","Wǒ xiàwǔ qù yīyuàn kàn yīshēng.","Je vais consulter à l'hôpital cet après-midi."),
  ...teach2("我今天去医院看病，医生让我多休息。","Wǒ jīntiān qù yīyuàn kàn bìng, yīshēng ràng wǒ duō xiūxi.","Je vais consulter à l'hôpital aujourd'hui ; le médecin me demande de me reposer davantage."),
  ...teach2("她已经去了，医生给她开了药。","Tā yǐjīng qù le, yīshēng gěi tā kāi le yào.","Elle y est déjà allée ; le médecin lui a prescrit des médicaments."),
  ...teach2("你不舒服，我陪你去医院吧。","Nǐ bù shūfu, wǒ péi nǐ qù yīyuàn ba.","Tu ne te sens pas bien ; je t'accompagne à l'hôpital."),
  N("Demandez : es-tu allé à l'hôpital ?"),TH(),
  C("你去医院了吗？","Nǐ qù yīyuàn le ma?","Es-tu allé à l'hôpital ?",.66),HOLD(),
  N("Répondez : pas encore, accompagne-moi s'il te plaît."),TH(),
  C("还没有，你陪我去吧。","Hái méiyǒu, nǐ péi wǒ qù ba.","Pas encore. Accompagne-moi, s'il te plaît.",.66),HOLD(),
  N("Dites : tu ne te sens pas bien, je t'accompagne à l'hôpital."),TH(),
  C("你不舒服，我陪你去医院吧。","Nǐ bù shūfu, wǒ péi nǐ qù yīyuàn ba.","Tu ne te sens pas bien ; je t'accompagne à l'hôpital.",.66),HOLD(),
    ];}},

  {num:6,hanzi:"医生开的药",title:"Comprendre une ordonnance simple",desc:"开药 · 怎么吃 · 一天三次 · 一次两片",
    build(){return[
  N("Leçon 6. Écoutez le dialogue cible. Vous allez demander comment prendre un médicament et comprendre une indication simple du support."),
  C("这是医生给我开的药。","Zhè shì yīshēng gěi wǒ kāi de yào.","Ce sont les médicaments que le médecin m'a prescrits.",.62),
  C("一天三次，一次两片。","Yì tiān sān cì, yí cì liǎng piàn.","Trois fois par jour, deux comprimés à chaque fois.",.62),
  N("[[开药|kāi yào]] signifie prescrire des médicaments. La construction shì…de insiste ici sur l'auteur : c'est le médecin qui les a prescrits."),
  ...teach2("这药怎么吃？","Zhè yào zěnme chī?","Comment faut-il prendre ce médicament ?"),
  ...teach2("请按医生说的吃药。","Qǐng àn yīshēng shuō de chī yào.","Veuillez prendre le médicament comme le médecin l'a indiqué."),
  ...teach2("我没看明白这个说明。","Wǒ méi kàn míngbai zhège shuōmíng.","Je n'ai pas bien compris cette notice."),
  N("Dites : ce sont les médicaments que le médecin m'a prescrits."),TH(),
  C("这是医生给我开的药。","Zhè shì yīshēng gěi wǒ kāi de yào.","Ce sont les médicaments que le médecin m'a prescrits.",.66),HOLD(),
  N("Demandez : comment faut-il prendre ce médicament ?"),TH(),
  C("这药怎么吃？","Zhè yào zěnme chī?","Comment faut-il prendre ce médicament ?",.66),HOLD(),
  N("Répétez l'indication : trois fois par jour, deux comprimés à chaque fois."),TH(),
  C("一天三次，一次两片。","Yì tiān sān cì, yí cì liǎng piàn.","Trois fois par jour, deux comprimés à chaque fois.",.66),HOLD(),
    ];}},

  {num:7,hanzi:"多喝水",title:"Donner des conseils courants",desc:"多喝水 · 按时吃药 · 好好休息",
    build(){return[
  N("Leçon 7. Écoutez le dialogue cible. Vous allez donner à un ami les conseils simples du support."),
  C("我感冒了，应该怎么办？","Wǒ gǎnmào le, yīnggāi zěnme bàn?","J'ai attrapé un rhume. Que devrais-je faire ?",.62),
  C("你要多喝水，按时吃药，好好休息。","Nǐ yào duō hē shuǐ, ànshí chī yào, hǎohāo xiūxi.","Tu dois boire beaucoup d'eau, prendre tes médicaments à l'heure et bien te reposer.",.62),
  N("[[要|yào]] exprime ici un conseil important. [[按时|ànshí]] veut dire à l'heure, selon l'horaire prévu."),
  ...teach2("今天别去运动了，在家好好休息吧。","Jīntiān bié qù yùndòng le, zài jiā hǎohāor xiūxi ba.","Ne va pas faire de sport aujourd'hui ; repose-toi bien à la maison."),
  ...teach2("你要多喝温水，别熬夜。","Nǐ yào duō hē wēnshuǐ, bié áoyè.","Tu dois boire davantage d'eau tiède et ne pas te coucher tard."),
  ...teach2("谢谢，我会按时吃药的。","Xièxie, wǒ huì ànshí chī yào de.","Merci, je prendrai mes médicaments à l'heure."),
  N("Votre ami demande quoi faire. Dites : bois beaucoup d'eau, prends tes médicaments à l'heure et repose-toi bien."),TH(),
  C("你要多喝水，按时吃药，好好休息。","Nǐ yào duō hē shuǐ, ànshí chī yào, hǎohāo xiūxi.","Tu dois boire beaucoup d'eau, prendre tes médicaments à l'heure et bien te reposer.",.66),HOLD(),
  N("Dites : ne va pas faire de sport aujourd'hui, repose-toi bien à la maison."),TH(),
  C("今天别去运动了，在家好好休息吧。","Jīntiān bié qù yùndòng le, zài jiā hǎohāor xiūxi ba.","Ne va pas faire de sport aujourd'hui ; repose-toi bien à la maison.",.66),HOLD(),
  N("Répondez : merci, je prendrai mes médicaments à l'heure."),TH(),
  C("谢谢，我会按时吃药的。","Xièxie, wǒ huì ànshí chī yào de.","Merci, je prendrai mes médicaments à l'heure.",.66),HOLD(),
    ];}},

  {num:8,hanzi:"着凉了",title:"Expliquer une cause simple",desc:"着凉 · 下雨 · 送伞 · 是…的",
    build(){return[
  N("Leçon 8. Écoutez le dialogue cible. Vous allez expliquer avec prudence qu'une personne a peut-être pris froid."),
  C("你怎么感冒了？","Nǐ zěnme gǎnmào le?","Comment as-tu attrapé ce rhume ?",.62),
  C("可能是昨天淋雨着凉的。","Kěnéng shì zuótiān línyǔ zháoliáng de.","C'est peut-être parce que j'ai été mouillé par la pluie hier et que j'ai pris froid.",.62),
  N("[[着凉|zháoliáng]] veut dire prendre froid. Avec [[可能|kěnéng]], vous présentez une supposition, pas une certitude."),
  ...teach2("昨天给朋友送伞的时候，我淋雨了。","Zuótiān gěi péngyou sòng sǎn de shíhou, wǒ línyǔ le.","Hier, en apportant un parapluie à un ami, j'ai été mouillé par la pluie."),
  ...teach2("他昨天晚上没穿外套，可能着凉了。","Tā zuótiān wǎnshang méi chuān wàitào, kěnéng zháoliáng le.","Il n'a pas porté de veste hier soir ; il a peut-être pris froid."),
  ...teach2("你是怎么受伤的？我是打球的时候受伤的。","Nǐ shì zěnme shòushāng de? Wǒ shì dǎ qiú de shíhou shòushāng de.","Comment t'es-tu blessé ? Je me suis blessé en jouant au ballon."),
  N("Demandez : comment as-tu attrapé ce rhume ?"),TH(),
  C("你怎么感冒了？","Nǐ zěnme gǎnmào le?","Comment as-tu attrapé ce rhume ?",.66),HOLD(),
  N("Répondez prudemment : c'est peut-être parce que j'ai été mouillé par la pluie hier et que j'ai pris froid."),TH(),
  C("可能是昨天淋雨着凉的。","Kěnéng shì zuótiān línyǔ zháoliáng de.","C'est peut-être parce que j'ai été mouillé par la pluie hier et que j'ai pris froid.",.66),HOLD(),
  N("Dites : il n'a pas porté de veste hier soir ; il a peut-être pris froid."),TH(),
  C("他昨天晚上没穿外套，可能着凉了。","Tā zuótiān wǎnshang méi chuān wàitào, kěnéng zháoliáng le.","Il n'a pas porté de veste hier soir ; il a peut-être pris froid.",.66),HOLD(),
    ];}},

  {num:9,hanzi:"给朋友打电话",title:"Prendre des nouvelles par téléphone",desc:"怎么没来 · 好点儿 · 作业",
    build(){return[
  N("Leçon 9. Écoutez le dialogue cible. Vous allez appeler un camarade absent et prendre de ses nouvelles."),
  C("你今天怎么没来上课？","Nǐ jīntiān zěnme méi lái shàngkè?","Pourquoi n'es-tu pas venu en cours aujourd'hui ?",.62),
  C("我感冒了，在家休息。","Wǒ gǎnmào le, zài jiā xiūxi.","J'ai attrapé un rhume ; je me repose à la maison.",.62),
  N("Pour demander des nouvelles, on part d'un fait simple : ne pas être venu en cours. La réponse explique naturellement la situation."),
  ...teach2("你现在好点儿了吗？","Nǐ xiànzài hǎo diǎnr le ma?","Est-ce que tu vas un peu mieux maintenant ?"),
  ...teach2("好多了，就是还有点儿咳嗽。","Hǎo duō le, jiùshì hái yǒudiǎnr késou.","Ça va beaucoup mieux ; je tousse encore juste un peu."),
  ...teach2("今天没有作业，你安心休息吧。","Jīntiān méiyǒu zuòyè, nǐ ānxīn xiūxi ba.","Il n'y a pas de devoirs aujourd'hui ; repose-toi tranquillement."),
  N("Appelez votre camarade. Demandez : pourquoi n'es-tu pas venu en cours aujourd'hui ?"),TH(),
  C("你今天怎么没来上课？","Nǐ jīntiān zěnme méi lái shàngkè?","Pourquoi n'es-tu pas venu en cours aujourd'hui ?",.66),HOLD(),
  N("Répondez : j'ai attrapé un rhume, je me repose à la maison."),TH(),
  C("我感冒了，在家休息。","Wǒ gǎnmào le, zài jiā xiūxi.","J'ai attrapé un rhume ; je me repose à la maison.",.66),HOLD(),
  N("Demandez ensuite : est-ce que tu vas un peu mieux maintenant ?"),TH(),
  C("你现在好点儿了吗？","Nǐ xiànzài hǎo diǎnr le ma?","Est-ce que tu vas un peu mieux maintenant ?",.66),HOLD(),
    ];}},

  {num:10,hanzi:"在医院",title:"Jouer le dialogue chez le médecin",desc:"Symptôme · moment · médecin · médicament",
    build(){return[
  N("Leçon 10. Écoutez le dialogue cible en entier. Vous allez jouer un patient qui décrit ses symptômes sans donner de diagnostic."),
  C("你哪儿不舒服？","Nǐ nǎr bù shūfu?","Qu'est-ce qui ne va pas ?",.62),
  C("我发烧，嗓子也疼。","Wǒ fāshāo, sǎngzi yě téng.","J'ai de la fièvre et j'ai aussi mal à la gorge.",.62),
  C("什么时候开始的？","Shénme shíhou kāishǐ de?","Quand est-ce que cela a commencé ?",.62),
  C("今天早上开始的。","Jīntiān zǎoshang kāishǐ de.","Ça a commencé ce matin.",.62),
  C("我给你开点药，你要按时吃。","Wǒ gěi nǐ kāi diǎn yào, nǐ yào ànshí chī.","Je vais vous prescrire un peu de médicament ; vous devez le prendre à l'heure.",.62),
  N("Jouez maintenant les deux rôles. Vous êtes le médecin. Demandez : qu'est-ce qui ne va pas ?"),TH(),
  C("你哪儿不舒服？","Nǐ nǎr bù shūfu?","Qu'est-ce qui ne va pas ?",.66),HOLD(),
  N("Vous êtes le patient. Dites : j'ai de la fièvre et j'ai aussi mal à la gorge."),TH(),
  C("我发烧，嗓子也疼。","Wǒ fāshāo, sǎngzi yě téng.","J'ai de la fièvre et j'ai aussi mal à la gorge.",.66),HOLD(),
  N("Le médecin demande depuis quand. Posez la question."),TH(),
  C("什么时候开始的？","Shénme shíhou kāishǐ de?","Quand est-ce que cela a commencé ?",.66),HOLD(),
  N("Le patient répond : ça a commencé ce matin."),TH(),
  C("今天早上开始的。","Jīntiān zǎoshang kāishǐ de.","Ça a commencé ce matin.",.66),HOLD(),
    ];}},

  {num:11,hanzi:"医生说要休息",title:"Rapporter ce que le médecin a dit",desc:"医生说 · 要 · 已经 · 好多了",
    build(){return[
  N("Leçon 11. Écoutez le dialogue cible. Vous allez dire ce que le médecin vous a conseillé et donner de meilleures nouvelles."),
  C("医生怎么说？","Yīshēng zěnme shuō?","Qu'a dit le médecin ?",.62),
  C("医生说我要多休息，多喝水。","Yīshēng shuō wǒ yào duō xiūxi, duō hē shuǐ.","Le médecin a dit que je devais davantage me reposer et boire beaucoup d'eau.",.62),
  N("Après [[医生说|yīshēng shuō]], reprenez directement l'information. Il n'y a pas besoin d'ajouter un mot équivalent à « que » en français."),
  ...teach2("医生说我不能太累。","Yīshēng shuō wǒ bù néng tài lèi.","Le médecin a dit que je ne devais pas trop me fatiguer."),
  ...teach2("我已经吃药了，现在好多了。","Wǒ yǐjīng chī yào le, xiànzài hǎo duō le.","J'ai déjà pris le médicament ; maintenant, je vais beaucoup mieux."),
  ...teach2("明天我还要在家休息一天。","Míngtiān wǒ hái yào zài jiā xiūxi yì tiān.","Demain, je dois encore rester me reposer à la maison une journée."),
  N("Demandez : qu'a dit le médecin ?"),TH(),
  C("医生怎么说？","Yīshēng zěnme shuō?","Qu'a dit le médecin ?",.66),HOLD(),
  N("Répondez : le médecin a dit que je devais davantage me reposer et boire beaucoup d'eau."),TH(),
  C("医生说我要多休息，多喝水。","Yīshēng shuō wǒ yào duō xiūxi, duō hē shuǐ.","Le médecin a dit que je devais davantage me reposer et boire beaucoup d'eau.",.66),HOLD(),
  N("Dites : j'ai déjà pris le médicament, maintenant je vais beaucoup mieux."),TH(),
  C("我已经吃药了，现在好多了。","Wǒ yǐjīng chī yào le, xiànzài hǎo duō le.","J'ai déjà pris le médicament ; maintenant, je vais beaucoup mieux.",.66),HOLD(),
    ];}},

  {num:12,hanzi:"好好休息",title:"Dialogue final : aider un ami malade",desc:"Révision complète · 中医 et 西医",
    build(){return[
  N("Mission finale. Écoutez le dialogue cible. Vous allez pouvoir demander des nouvelles, comprendre la situation et répondre avec des phrases utiles."),
  C("你今天怎么没来上课？","Nǐ jīntiān zěnme méi lái shàngkè?","Pourquoi n'es-tu pas venu en cours aujourd'hui ?",.62),
  C("我感冒了，嗓子疼，还咳嗽。","Wǒ gǎnmào le, sǎngzi téng, hái késou.","J'ai attrapé un rhume ; j'ai mal à la gorge et je tousse aussi.",.62),
  C("什么时候开始的？","Shénme shíhou kāishǐ de?","Quand est-ce que cela a commencé ?",.62),
  C("昨天晚上开始的。我已经去医院了。","Zuótiān wǎnshang kāishǐ de. Wǒ yǐjīng qù yīyuàn le.","Ça a commencé hier soir. Je suis déjà allé à l'hôpital.",.62),
  C("那你要多喝水，按时吃药，好好休息。","Nà nǐ yào duō hē shuǐ, ànshí chī yào, hǎohāo xiūxi.","Alors, bois beaucoup d'eau, prends tes médicaments à l'heure et repose-toi bien.",.62),
  N("Le support mentionne aussi la médecine chinoise. Voici une phrase de culture générale, sans choisir de traitement."),
  ...teach2("中医和西医的治疗方法不一样。","Zhōngyī hé xīyī de zhìliáo fāngfǎ bù yíyàng.","La médecine chinoise et la médecine occidentale n'ont pas les mêmes méthodes de traitement."),
  ...teach2("有些人生病的时候会去看中医。","Yǒuxiē rén shēng bìng de shíhou huì qù kàn zhōngyī.","Certaines personnes consultent un médecin de médecine chinoise lorsqu'elles sont malades."),
  N("Vous appelez votre ami. Demandez : pourquoi n'es-tu pas venu en cours aujourd'hui ?"),TH(),
  C("你今天怎么没来上课？","Nǐ jīntiān zěnme méi lái shàngkè?","Pourquoi n'es-tu pas venu en cours aujourd'hui ?",.66),HOLD(),
  N("Répondez : j'ai attrapé un rhume, j'ai mal à la gorge et je tousse aussi."),TH(),
  C("我感冒了，嗓子疼，还咳嗽。","Wǒ gǎnmào le, sǎngzi téng, hái késou.","J'ai attrapé un rhume ; j'ai mal à la gorge et je tousse aussi.",.66),HOLD(),
  N("Demandez : quand est-ce que cela a commencé ?"),TH(),
  C("什么时候开始的？","Shénme shíhou kāishǐ de?","Quand est-ce que cela a commencé ?",.66),HOLD(),
  N("Terminez en donnant les conseils. Dites : bois beaucoup d'eau, prends tes médicaments à l'heure et repose-toi bien."),TH(),
  C("那你要多喝水，按时吃药，好好休息。","Nà nǐ yào duō hē shuǐ, ànshí chī yào, hǎohāo xiūxi.","Alors, bois beaucoup d'eau, prends tes médicaments à l'heure et repose-toi bien.",.66),HOLD(),
  N("Vous savez maintenant parler simplement de votre état, consulter et aider un ami. Pour un problème de santé réel, demandez toujours conseil à un professionnel."),
  C("再见！","Zàijiàn!","Au revoir !",.66),
    ];}},
  ]
});

/* Exercices visuels de fin de leçon : syntaxe, vocabulaire et ordre des constituants. */
registerTileExercises("09-health", {
  1:[
    TILES("Qu’est-ce qui ne va pas ?",["你","哪儿","不舒服"],["什么","头疼"],"？"),
    TILES("Je ne me sens pas très bien aujourd’hui.",["我","今天","不太","舒服"],["很","昨天"]),
  ],
  2:[
    TILES("As-tu mal à la gorge ?",["你","嗓子","疼","吗"],["鼻子","有点儿"],"？"),
    TILES("J’ai marché longtemps ; j’ai un peu mal aux pieds.",["我","走了","很长时间，","脚","有点儿疼"],["胳膊","咳嗽"]),
  ],
  3:[
    TILES("As-tu attrapé un rhume ?",["你","感冒","了","吗"],["发烧","还"],"？"),
    TILES("Je n’ai pas de fièvre, mais j’ai constamment le nez qui coule.",["我","不发烧，","但是","一直","流鼻涕"],["咳嗽","好像"]),
  ],
  4:[
    TILES("Quand est-ce que cela a commencé ?",["什么时候","开始","的"],["怎么","昨天"],"？"),
    TILES("J’ai commencé à ne pas me sentir bien hier soir.",["我","是","昨天晚上","开始","不舒服","的"],["今天早上","已经"]),
  ],
  5:[
    TILES("Es-tu allé à l’hôpital ?",["你","去医院","了","吗"],["看医生","没有"],"？"),
    TILES("Tu ne te sens pas bien ; je t’accompagne à l’hôpital.",["你","不舒服，","我","陪你","去医院","吧"],["医生","回家"]),
  ],
  6:[
    TILES("Ce sont les médicaments que le médecin m’a prescrits.",["这","是","医生","给我","开的","药"],["怎么吃","说明"]),
    TILES("Trois fois par jour, deux comprimés à chaque prise.",["一天","三次，","一次","两片"],["一个","两次"]),
  ],
  7:[
    TILES("J’ai attrapé un rhume. Que devrais-je faire ?",["我","感冒了","应该","怎么办"],["为什么","休息"],"？"),
    TILES("Tu dois boire beaucoup d’eau, prendre tes médicaments à l’heure et bien te reposer.",["你","要","多喝水，","按时吃药，","好好休息"],["别熬夜","运动"]),
  ],
  8:[
    TILES("Comment as-tu attrapé ce rhume ?",["你","怎么","感冒了"],["哪儿","发烧"],"？"),
    TILES("C’est peut-être parce que j’ai été mouillé par la pluie hier et que j’ai pris froid.",["可能","是","昨天","淋雨","着凉","的"],["今天","咳嗽"]),
  ],
  9:[
    TILES("Pourquoi n’es-tu pas venu en cours aujourd’hui ?",["你","今天","怎么","没来","上课"],["昨天","回家"],"？"),
    TILES("Est-ce que tu vas un peu mieux maintenant ?",["你","现在","好点儿","了","吗"],["已经","咳嗽"],"？"),
  ],
  10:[
    TILES("J’ai de la fièvre et j’ai aussi mal à la gorge.",["我","发烧，","嗓子","也疼"],["头","咳嗽"]),
    TILES("Je vais te prescrire un peu de médicament ; tu dois le prendre à l’heure.",["我","给你","开点药，","你","要","按时吃"],["多喝水","已经"]),
  ],
  11:[
    TILES("Le médecin a dit que je devais davantage me reposer et boire beaucoup d’eau.",["医生","说","我","要","多休息，","多喝水"],["不能","吃药"]),
    TILES("J’ai déjà pris le médicament ; maintenant, je vais beaucoup mieux.",["我","已经","吃药了，","现在","好多了"],["明天","有点儿"]),
  ],
  12:[
    TILES("J’ai attrapé un rhume ; j’ai mal à la gorge et je tousse aussi.",["我","感冒了，","嗓子疼，","还咳嗽"],["发烧","流鼻涕"]),
    TILES("Alors, bois beaucoup d’eau, prends tes médicaments à l’heure et repose-toi bien.",["那","你","要","多喝水，","按时吃药，","好好休息"],["去医院","别着急"]),
  ],
});
