/* ============================================================
   Chapitre Bonus 4 · 指示与提问 — Démonstratifs, interrogatifs,
   quantités et lieux.
   ============================================================ */
registerChapter({
  group: "bonus",
  id: "04-demonstratifs",
  badge: "★4",
  star: true,
  hanzi: "指示与提问",
  title: "Bonus 4 · Montrer, demander et situer",
  desc: "这/那 · 哪个/哪些 · 这里/那里 · 有些/有的 · 一下/有点儿 — 7 leçons",
  intro: "Sept leçons pour maîtriser les petits mots qui organisent une conversation : montrer, choisir, demander lequel, situer un objet et exprimer une quantité approximative. Chaque leçon alterne explication, dialogue et réponses à produire.",
  lessons: [

  { num:1, hanzi:"这个那个", title:"Ce, celui-ci, celui-là", desc:"这 · 那 · 这个 · 那个 · 这本/那家",
    build(){ return [
  N("Bienvenue dans ce bonus consacré aux petits mots très fréquents. Aujourd'hui, on apprend à montrer et à distinguer : ce livre-ci, ce restaurant-là, cet objet et cet autre."),
  C("这是我的书。","Zhè shì wǒ de shū.","C'est mon livre.",0.6), P(1,"…"),
  C("那个不是我的。","Nàge bú shì wǒ de.","Celui-là n'est pas à moi.",0.6),
  N("[[这|zhè]] signifie « ce/cette-ci », près de la personne qui parle. [[那|nà]] signifie « ce/cette-là », plus éloigné. Avec un nom, on ajoute [[个|ge]] : [[这个|zhège]], « celui-ci », et [[那个|nàge]], « celui-là »."),
  ...teach2("这","zhè","ceci, ce/cette-ci"),
  ...teach2("那","nà","cela, ce/cette-là"),
  ...teach2("这个","zhège","celui-ci, ceci"),
  ...teach2("那个","nàge","celui-là, cela"),
  N("Avec un objet qui a son propre classificateur, celui-ci se place entre 这 et le nom. « Ce livre-ci » se dit :"),
  ...teach2("这本书","zhè běn shū","ce livre-ci"),
  N("« Cette maison-là » se dit [[那所房子|nà suǒ fángzi]]. Pour parler naturellement, le classificateur dépend du nom."),
  ...teach2("那所房子","nà suǒ fángzi","cette maison-là"),
  N("Montrez quelque chose près de vous : dites « ceci est mon livre »."), TH(),
  C("这是我的书。","Zhè shì wǒ de shū.","C'est mon livre.",0.65), HOLD(),
  N("Montrez un objet plus loin : dites « celui-là n'est pas à moi »."), TH(),
  C("那个不是我的。","Nàge bú shì wǒ de.","Celui-là n'est pas à moi.",0.65), HOLD(),
  N("Dialogue. Votre ami montre un livre. Répondez en indiquant l'autre livre."),
  C("这是你的书吗？","Zhè shì nǐ de shū ma?","C'est ton livre ?",0.6),
  N("Répondez : non, celui-là est mon livre."), TH(),
  C("不是，那个是我的书。","Bú shì, nàge shì wǒ de shū.","Non, celui-là est mon livre.",0.65), HOLD(),
  N("Révision : dites « ce livre-ci »."), TH(), C("这本书","zhè běn shū","ce livre-ci",0.65),
  N("Dites « celui-là »."), TH(), C("那个","nàge","celui-là",0.65), HOLD(),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:2, hanzi:"哪个哪些", title:"Lequel et lesquels", desc:"哪 · 哪个 · 哪些 · 什么 · 哪一本",
    build(){ return [
  N("Leçon 2. Pour demander lequel, on utilise [[哪|nǎ]], « quel ». Avec le classificateur général, [[哪个|nǎge]] signifie « lequel/laquelle ». Pour plusieurs éléments, [[哪些|nǎxiē]] signifie « lesquels ou lesquels parmi ceux-ci »."),
  ...teach2("哪个","nǎge","lequel, laquelle"),
  ...teach2("哪些","nǎxiē","lesquels, lesquelles"),
  N("[[什么|shénme]] demande « quoi » en général. [[哪个|nǎge]] demande un choix dans un ensemble connu."),
  C("你喜欢哪个？","Nǐ xǐhuan nǎge?","Lequel tu aimes ?",0.6), P(1,"…"),
  C("我喜欢这个。","Wǒ xǐhuan zhège.","J'aime celui-ci.",0.6),
  N("Demandez : lequel tu veux ?"), TH(),
  C("你要哪个？","Nǐ yào nǎge?","Lequel tu veux ?",0.65), HOLD(),
  N("Répondez : je veux celui-là."), TH(),
  C("我要那个。","Wǒ yào nàge.","Je veux celui-là.",0.65), HOLD(),
  N("Pour plusieurs choix, demandez : lesquels tu aimes ?"), TH(),
  C("你喜欢哪些？","Nǐ xǐhuan nǎxiē?","Lesquels tu aimes ?",0.65), HOLD(),
  N("Répondez : j'aime ceux-ci et ceux-là."), TH(),
  C("我喜欢这些和那些。","Wǒ xǐhuan zhèxiē hé nàxiē.","J'aime ceux-ci et ceux-là.",0.65), HOLD(),
  N("Avec un classificateur, on peut préciser le choix. « Laquelle de ces trois photos ? » se dit :"),
  ...teach2("哪一张照片？","nǎ yì zhāng zhàopiàn?","Quelle photo, laquelle des photos ?"),
  N("Dialogue. Vous êtes dans une librairie."),
  C("你想买哪本书？","Nǐ xiǎng mǎi nǎ běn shū?","Quel livre veux-tu acheter ?",0.6),
  N("Répondez : je veux acheter ce livre-ci."), TH(),
  C("我想买这本书。","Wǒ xiǎng mǎi zhè běn shū.","Je veux acheter ce livre-ci.",0.65),
  N("Changez la question : demandez quels livres la personne aime."), TH(),
  C("你喜欢哪些书？","Nǐ xǐhuan nǎxiē shū?","Quels livres aimes-tu ?",0.65), HOLD(),
  N("Révision. « Lequel ? »"), TH(), C("哪个？","Nǎge?","Lequel ?",0.65),
  N("« Lesquels ? »"), TH(), C("哪些？","Nǎxiē?","Lesquels ?",0.65), HOLD(),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:3, hanzi:"这里那里哪儿", title:"Ici, là-bas, où ?", desc:"这里 · 这儿 · 那里 · 那儿 · 哪儿 · 那边 · 这边",
    build(){ return [
  N("Leçon 3. Les mots de lieu se construisent avec les mêmes repères : [[这|zhè]] pour ici, [[那|nà]] pour là-bas, et [[哪|nǎ]] pour demander où."),
  ...teach2("这里","zhèlǐ","ici, dans cet endroit"),
  ...teach2("这儿","zhèr","ici, forme orale"),
  ...teach2("那里","nàlǐ","là-bas, dans cet endroit"),
  ...teach2("那儿","nàr","là-bas, forme orale"),
  ...teach2("哪里","nǎlǐ","où, dans quel endroit"),
  ...teach2("哪儿","nǎr","où, dans quel endroit"),
  N("[[这边|zhèbiān]] signifie « de ce côté-ci » et [[那边|nàbiān]] « de ce côté-là ». Ils sont très utiles pour indiquer une direction."),
  ...teach2("这边","zhèbiān","ce côté-ci, par ici"),
  ...teach2("那边","nàbiān","ce côté-là, par là-bas"),
  ...teach2("哪边","nǎbiān","quel côté, par où"),
  C("洗手间在哪儿？","Xǐshǒujiān zài nǎr?","Où sont les toilettes ?",0.6), P(1,"…"),
  C("在那边。","Zài nàbiān.","C'est par là-bas.",0.6),
  N("Demandez : où est le restaurant ?"), TH(),
  C("饭店在哪儿？","Fàndiàn zài nǎr?","Où est le restaurant ?",0.65), HOLD(),
  N("Répondez : le restaurant est de ce côté-ci."), TH(),
  C("饭店在这边。","Fàndiàn zài zhèbiān.","Le restaurant est de ce côté-ci.",0.65), HOLD(),
  N("Dialogue. Quelqu'un cherche son téléphone."),
  C("我的手机在哪儿？","Wǒ de shǒujī zài nǎr?","Où est mon téléphone ?",0.6),
  N("Répondez : il est là-bas, sur la table."), TH(),
  C("它在那边，在桌子上。","Tā zài nàbiān, zài zhuōzi shàng.","Il est là-bas, sur la table.",0.65), HOLD(),
  N("Remarquez [[它|tā]] : pour un objet ou un animal déjà identifié, cela signifie « il/elle/cela ». On ne l'utilise pas pour une personne."),
  ...teach2("它","tā","il/elle/cela pour un objet ou un animal"),
  N("Révision : dites « où ? »."), TH(), C("哪儿？","Nǎr?","Où ?",0.65),
  N("Dites « ici »."), TH(), C("这儿。","Zhèr.","Ici.",0.65),
  N("Dites « là-bas »."), TH(), C("那儿。","Nàr.","Là-bas.",0.65), HOLD(),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:4, hanzi:"这些那些有的", title:"Ces choses, certaines choses", desc:"这/那 + 些 · 这些 · 那些 · 有的 · 有些 · 一些",
    build(){ return [
  N("Leçon 4. [[些|xiē]] indique plusieurs éléments sans donner de nombre précis. Avec 这, [[这些|zhèxiē]] signifie « ces choses-ci ». Avec 那, [[那些|nàxiē]] signifie « ces choses-là »."),
  ...teach2("些","xiē","des, quelques-uns (quantité indéfinie)"),
  ...teach2("这些","zhèxiē","ces choses-ci, ceux-ci"),
  ...teach2("那些","nàxiē","ces choses-là, ceux-là"),
  N("[[一些|yìxiē]] signifie « quelques, certains » sans montrer précisément lesquels."),
  ...teach2("一些","yìxiē","quelques, un certain nombre de"),
  N("Pour dire « certains… d'autres… », on utilise [[有的|yǒude]] deux fois ou avec [[有些|yǒuxiē]]."),
  ...teach2("有的","yǒude","certains, les uns"),
  ...teach2("有些","yǒuxiē","certains, quelques-uns"),
  C("这些是我的书。","Zhèxiē shì wǒ de shū.","Ce sont mes livres.",0.6), P(1,"…"),
  C("那些是你的书吗？","Nàxiē shì nǐ de shū ma?","Ces livres-là sont à toi ?",0.6),
  N("Montrez plusieurs objets près de vous : dites « ce sont mes livres »."), TH(),
  C("这些是我的书。","Zhèxiē shì wǒ de shū.","Ce sont mes livres.",0.65), HOLD(),
  N("Demandez si plusieurs objets plus loin appartiennent à votre interlocuteur."), TH(),
  C("那些是你的吗？","Nàxiē shì nǐ de ma?","Ceux-là sont à toi ?",0.65), HOLD(),
  N("Répondez : certains sont à moi, d'autres sont à ma sœur."), TH(),
  C("有的是我的，有的是我姐姐的。","Yǒude shì wǒ de, yǒude shì wǒ jiějie de.","Certains sont à moi, d'autres sont à ma sœur.",0.65), HOLD(),
  N("Avec un nom, [[有些|yǒuxiē]] signifie « certains/quelques ». Dites : certains restaurants sont très bons."), TH(),
  C("有些饭店很好。","Yǒuxiē fàndiàn hěn hǎo.","Certains restaurants sont très bons.",0.65), HOLD(),
  N("Dialogue : vous regardez des photos."),
  C("这些照片是谁的？","Zhèxiē zhàopiàn shì shéi de?","À qui sont ces photos-ci ?",0.6),
  N("Répondez : certaines sont à moi, certaines sont à mon ami."), TH(),
  C("有些是我的，有些是我朋友的。","Yǒuxiē shì wǒ de, yǒuxiē shì wǒ péngyou de.","Certaines sont à moi, certaines sont à mon ami.",0.65), HOLD(),
  N("Révision : « ces choses-ci »."), TH(), C("这些","zhèxiē","ces choses-ci",0.65),
  N("« Ces choses-là »."), TH(), C("那些","nàxiē","ces choses-là",0.65), HOLD(),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:5, hanzi:"一下有点儿", title:"Un peu, un instant, légèrement", desc:"一下 · 有点儿 · 一点儿 · 一些 · 太",
    build(){ return [
  N("Leçon 5. Deux petits mots rendent le chinois plus naturel. [[一下|yíxià]] signifie « un instant » après un verbe, et adoucit une demande. [[有点儿|yǒudiǎnr]] signifie « un peu », souvent avec une nuance de gêne ou de problème."),
  ...teach2("一下","yíxià","un instant, un petit coup (après un verbe)"),
  ...teach2("有点儿","yǒudiǎnr","un peu, légèrement (souvent un peu trop)"),
  N("« Regarde un instant » se dit :"),
  ...teach2("看一下","kàn yíxià","regarder un instant"),
  N("« Attendez un instant, s'il vous plaît » se dit :"),
  ...teach2("请等一下。","Qǐng děng yíxià.","Veuillez patienter un instant."),
  N("Ne confondez pas [[有点儿|yǒudiǎnr]], « un peu, malheureusement », avec [[一点儿|yìdiǎnr]], « un peu de quantité »."),
  ...teach2("有点儿辣。","Yǒudiǎnr là.","C'est un peu trop pimenté."),
  ...teach2("少放一点儿。","Shǎo fàng yìdiǎnr.","Mettez-en un peu moins."),
  C("你等一下。","Nǐ děng yíxià.","Attends un instant.",0.6), P(1,"…"),
  C("我有点儿累。","Wǒ yǒudiǎnr lèi.","Je suis un peu fatigué.",0.6),
  N("Demandez poliment : pouvez-vous regarder un instant ?"), TH(),
  C("你可以看一下吗？","Nǐ kěyǐ kàn yíxià ma?","Tu peux regarder un instant ?",0.65), HOLD(),
  N("Dites : j'ai un peu faim."), TH(),
  C("我有点儿饿。","Wǒ yǒudiǎnr è.","J'ai un peu faim.",0.65), HOLD(),
  N("Dites : veuillez patienter un instant."), TH(),
  C("请等一下。","Qǐng děng yíxià.","Veuillez patienter un instant.",0.65), HOLD(),
  N("Dialogue : votre ami parle trop vite."),
  C("你听懂了吗？","Nǐ tīng dǒng le ma?","Tu as compris ?",0.6),
  N("Répondez : pas très bien, parlez un peu plus lentement."), TH(),
  C("不太懂，请说慢一点儿。","Bú tài dǒng, qǐng shuō màn yìdiǎnr.","Je ne comprends pas très bien, parlez un peu plus lentement.",0.65), HOLD(),
  N("Révision : « un instant »."), TH(), C("一下","yíxià","un instant",0.65),
  N("« Un peu, légèrement »."), TH(), C("有点儿","yǒudiǎnr","un peu, légèrement",0.65), HOLD(),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:6, hanzi:"综合对话", title:"★ Grande révision : choisir et situer", desc:"哪个 · 哪些 · 哪儿 · 这边 · 那边 · 有些 · 一下",
    build(){ return [
  N("Dernière leçon : vous allez utiliser tous les mots dans une conversation réelle. Écoutez la scène, puis répondez à chaque question avant le modèle."),
  C("你想去哪儿？","Nǐ xiǎng qù nǎr?","Où veux-tu aller ?",0.6),
  N("Répondez : je veux aller de ce côté-ci."), TH(),
  C("我想去这边。","Wǒ xiǎng qù zhèbiān.","Je veux aller de ce côté-ci.",0.65), HOLD(),
  C("这边有哪些饭店？","Zhèbiān yǒu nǎxiē fàndiàn?","Quels restaurants y a-t-il de ce côté-ci ?",0.6),
  N("Répondez : il y a quelques bons restaurants de ce côté-ci."), TH(),
  C("这边有些很好的饭店。","Zhèbiān yǒuxiē hěn hǎo de fàndiàn.","Il y a quelques très bons restaurants de ce côté-ci.",0.65), HOLD(),
  C("你想去哪家？","Nǐ xiǎng qù nǎ jiā?","Dans quel restaurant veux-tu aller ?",0.6),
  N("Répondez : je veux aller dans celui-là."), TH(),
  C("我想去那家。","Wǒ xiǎng qù nà jiā.","Je veux aller dans celui-là.",0.65), HOLD(),
  N("Au restaurant, le serveur montre plusieurs plats : demandez lesquels sont pimentés."), TH(),
  C("哪些菜是辣的？","Nǎxiē cài shì là de?","Quels plats sont pimentés ?",0.65), HOLD(),
  N("Répondez : certains sont pimentés, certains ne le sont pas."), TH(),
  C("有些是辣的，有些不是。","Yǒuxiē shì là de, yǒuxiē bú shì.","Certains sont pimentés, d'autres non.",0.65), HOLD(),
  N("Vous ne comprenez pas le serveur. Demandez-lui de répéter un instant, puis de parler plus lentement."), TH(),
  C("请再说一下，请说慢一点儿。","Qǐng zài shuō yíxià, qǐng shuō màn yìdiǎnr.","Répétez, s'il vous plaît, et parlez un peu plus lentement.",0.65), HOLD(),
  N("Le serveur vous montre deux tables. Demandez : laquelle est libre ?"), TH(),
  C("哪张桌子是空的？","Nǎ zhāng zhuōzi shì kōng de?","Quelle table est libre ?",0.65), HOLD(),
  N("Répondez : cette table-ci est libre."), TH(),
  C("这张桌子是空的。","Zhè zhāng zhuōzi shì kōng de.","Cette table-ci est libre.",0.65), HOLD(),
  N("Révision finale. Dites « où ? », « lequel ? », « lesquels ? », puis « un instant »."), TH(),
  C("哪儿？哪个？哪些？一下。","Nǎr? Nǎge? Nǎxiē? Yíxià.","Où ? Lequel ? Lesquels ? Un instant.",0.65), HOLD(),
  N("Félicitations. Vous savez maintenant montrer, choisir, demander lequel, situer un objet, parler de certains éléments et adoucir une demande avec 一下. Réécoutez les dialogues et jouez les deux rôles."),
  C("谢谢，再见！","Xièxie, zàijiàn!","Merci, au revoir !",0.65), HOLD(),
    ]; } },

  { num:7, hanzi:"怎么多少", title:"★ Extensions HSK 1–2 indispensables", desc:"怎么 · 这么/那么 · 几/多少 · 每个 · 别的",
    build(){ return [
  N("Dernière leçon. Ajoutons les petits mots HSK 1 et HSK 2 qui complètent ce système. [[怎么|zěnme]] demande « comment », [[这么|zhème]] signifie « comme ceci, autant », et [[那么|nàme]] « comme cela, autant »."),
  ...teach2("怎么","zěnme","comment"),
  ...teach2("这么","zhème","ainsi, autant, à ce point-ci"),
  ...teach2("那么","nàme","ainsi, autant, à ce point-là"),
  N("Demandez : comment utilise-t-on ceci ?"), TH(),
  C("这个怎么用？","Zhège zěnme yòng?","Comment utilise-t-on ceci ?",0.65), HOLD(),
  N("Dites : ne parlez pas si vite."), TH(),
  C("别说得这么快。","Bié shuō de zhème kuài.","Ne parlez pas si vite.",0.65), HOLD(),
  N("Pour une petite quantité dénombrable, [[几|jǐ]] demande « combien ». Pour une quantité ouverte, [[多少|duōshao]] demande aussi « combien »."),
  ...teach2("几个","jǐ ge","combien de (petit nombre)"),
  ...teach2("多少","duōshao","combien, quelle quantité"),
  N("Demandez : combien de personnes êtes-vous ?"), TH(),
  C("你们有几个人？","Nǐmen yǒu jǐ ge rén?","Vous êtes combien de personnes ?",0.65), HOLD(),
  N("Demandez : combien coûte celui-là ?"), TH(),
  C("那个多少钱？","Nàge duōshao qián?","Combien coûte celui-là ?",0.65), HOLD(),
  N("[[每个|měi ge]] signifie « chaque ». [[别的|biéde]] signifie « autre, d'autres »."),
  ...teach2("每个","měi ge","chaque"),
  ...teach2("别的","biéde","autre, d'autres"),
  N("Dites : chaque personne a un livre."), TH(),
  C("每个人都有一本书。","Měi ge rén dōu yǒu yì běn shū.","Chaque personne a un livre.",0.65), HOLD(),
  N("Dialogue final. Votre ami voit beaucoup de livres."),
  C("这么多书，你要哪些？","Zhème duō shū, nǐ yào nǎxiē?","Il y a tant de livres : lesquels veux-tu ?",0.6),
  N("Répondez : je veux seulement ces quelques livres-ci, je ne veux pas les autres."), TH(),
  C("我只要这几本，别的不要。","Wǒ zhǐ yào zhè jǐ běn, biéde bú yào.","Je veux seulement ces quelques livres-ci, pas les autres.",0.65), HOLD(),
  N("Demandez ensuite : où sont les autres ?"), TH(),
  C("别的在哪儿？","Biéde zài nǎr?","Où sont les autres ?",0.65), HOLD(),
  N("Répondez : les autres sont là-bas."), TH(),
  C("别的在那边。","Biéde zài nàbiān.","Les autres sont là-bas.",0.65), HOLD(),
  N("Vous avez terminé le Bonus 4. Vous savez montrer, choisir, situer, demander lequel, où, comment et combien, puis parler de quelques éléments ou de chaque élément."),
  C("谢谢，再见！","Xièxie, zàijiàn!","Merci, au revoir !",0.65), HOLD(),
    ]; } },
  ]
});
