/* ============================================================
   Chapitre Bonus 3 · 谈饮食 — Parler de la nourriture
   Adapté du PDF « Parler de la nourriture en chinois ».
   Niveau débutant / faux débutant (environ HSK 1-2).

   Contenu uniquement : le moteur (helpers N, C, P, HOLD, TH,
   teach2, drill et registerChapter) est défini dans
   engine/player.js, chargé AVANT ce fichier.

   Progression : lire un menu, parler des goûts, reconnaître les
   plats et ingrédients, commander avec les bons classificateurs,
   choisir une boisson, préciser une restriction, demander un
   couvert et l'addition, puis révision totale.
   ============================================================ */
registerChapter({
  group: "bonus",
  id: "03-nourriture",
  badge: "★3",
  star: true,
  hanzi: "谈饮食",
  title: "Bonus 3 · Parler de la nourriture",
  desc: "Menu, goûts, plats, commande, restrictions et addition — 8 leçons",
  intro: "Huit leçons audio progressives adaptées du cours Parler de la nourriture en chinois. Vous apprendrez à lire les rubriques d'un menu, parler de vos goûts, commander des plats et des boissons, signaler une restriction alimentaire et demander l'addition. Faites les leçons dans l'ordre : chacune révise les précédentes.",
  lessons: [

// ================= PARTIE 1 =================
  { num:1, hanzi:"菜单", title:"Lire les grandes rubriques d'un menu", desc:"菜单 · 凉菜 · 热菜 · 汤 · 主食 · 饮料",
    build(){ return [
  N("Bienvenue dans ce chapitre bonus consacré à la nourriture. Aujourd'hui, vous allez apprendre à reconnaître les grandes rubriques d'un menu chinois. Écoutez d'abord le mini-dialogue cible."),
  C("这是菜单。","Zhè shì càidān.","Voici le menu.",0.4), P(2,"…"),
  C("主食点什么？","Zhǔshí diǎn shénme?","Que prenez-vous comme féculent ?",0.4), P(2,"…"),
  C("两碗米饭。","Liǎng wǎn mǐfàn.","Deux bols de riz.",0.4),

  N("Le mot pour « menu » ou « carte » se dit [[菜单|càidān]]. Écoutez et répétez."),
  ...teach2("菜单","càidān","menu, carte"),
  N("Pour dire « voici le menu », on dit littéralement « ceci est menu » :"),
  ...teach2("这是菜单。","Zhè shì càidān.","Voici le menu."),
  N("À vous : dites « voici le menu »."), TH(),
  C("这是菜单。","Zhè shì càidān.","Voici le menu.",0.6), HOLD(),

  N("Les plats froids, souvent servis en entrée, sont les [[凉菜|liángcài]]."),
  ...teach2("凉菜","liángcài","plats froids, entrées froides"),
  N("Les plats chauds sont les [[热菜|rècài]]."),
  ...teach2("热菜","rècài","plats chauds"),
  N("Une soupe ou un bouillon se dit [[汤|tāng]]."),
  ...teach2("汤","tāng","soupe, bouillon"),
  N("Les boissons sont classées sous [[饮料|yǐnliào]]."),
  ...teach2("饮料","yǐnliào","boisson"),

  N("Une rubrique importante est [[主食|zhǔshí]]. Elle ne signifie pas « plat principal ». Elle désigne les aliments de base servis avec les plats : riz, nouilles, raviolis ou petits pains."),
  ...teach2("主食","zhǔshí","féculent, aliment de base"),
  N("Le riz cuit se dit [[米饭|mǐfàn]]."),
  ...teach2("米饭","mǐfàn","riz cuit"),
  N("Les raviolis chinois se disent [[饺子|jiǎozi]]."),
  ...teach2("饺子","jiǎozi","raviolis chinois"),

  N("Question éclair. Dans quelle rubrique cherchez-vous des raviolis ? Répondez : dans les féculents."), TH(),
  C("主食。","Zhǔshí.","Dans les féculents.",0.65), HOLD(),
  N("Dans quelle rubrique cherchez-vous une soupe ?"), TH(),
  C("汤。","Tāng.","Dans les soupes.",0.65), HOLD(),
  N("Et une boisson ?"), TH(),
  C("饮料。","Yǐnliào.","Dans les boissons.",0.65), HOLD(),

  N("Le verbe [[点|diǎn]] veut dire « commander » ou « choisir un plat ». [[什么|shénme]] veut dire « quoi ». Écoutez la question : que prenez-vous comme féculent ?"),
  ...teach2("主食点什么？","Zhǔshí diǎn shénme?","Que prenez-vous comme féculent ?"),
  N("Pour l'instant, retenez la réponse complète : deux bols de riz."),
  ...teach2("两碗米饭。","Liǎng wǎn mǐfàn.","Deux bols de riz."),

  N("Mini-conversation. Le serveur vous montre quelque chose."),
  C("这是菜单。","Zhè shì càidān.","Voici le menu.",0.6),
  C("主食点什么？","Zhǔshí diǎn shénme?","Que prenez-vous comme féculent ?",0.6),
  N("Répondez : deux bols de riz."), TH(),
  C("两碗米饭。","Liǎng wǎn mǐfàn.","Deux bols de riz.",0.6), HOLD(),

  N("Révision finale. Dites : le menu."), TH(), C("菜单","càidān","le menu",0.65),
  N("Les plats froids."), TH(), C("凉菜","liángcài","les plats froids",0.65),
  N("Les plats chauds."), TH(), C("热菜","rècài","les plats chauds",0.65),
  N("Les féculents."), TH(), C("主食","zhǔshí","les féculents",0.65),
  N("Voici le menu."), TH(), C("这是菜单。","Zhè shì càidān.","Voici le menu.",0.65),
  N("Très bien. Fin de la leçon 1. À la prochaine leçon, vous apprendrez à décrire les saveurs et à dire ce que vous aimez."),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

// ================= PARTIE 2 =================
  { num:2, hanzi:"味道", title:"Les saveurs et les préférences", desc:"酸 · 甜 · 苦 · 辣 · 咸 · 喜欢……的",
    build(){ return [
  N("Leçon 2. Aujourd'hui : les cinq saveurs essentielles et vos préférences. Révision. Dites : voici le menu."), TH(),
  C("这是菜单。","Zhè shì càidān.","Voici le menu.",0.65),
  N("Dites : les plats froids, puis les plats chauds."), TH(),
  C("凉菜，热菜。","Liángcài, rècài.","Les plats froids, les plats chauds.",0.65), HOLD(),

  N("Écoutez le dialogue cible."),
  C("你喜欢什么味道？","Nǐ xǐhuan shénme wèidào?","Quelle saveur aimes-tu ?",0.4), P(2,"…"),
  C("我喜欢吃甜的。你呢？","Wǒ xǐhuan chī tián de. Nǐ ne?","J'aime manger ce qui est sucré. Et toi ?",0.4), P(2,"…"),
  C("我喜欢吃辣的。","Wǒ xǐhuan chī là de.","J'aime manger pimenté.",0.4),

  N("Le goût ou la saveur se dit [[味道|wèidào]]."),
  ...teach2("味道","wèidào","goût, saveur"),
  N("Acide se dit [[酸|suān]]."),
  ...teach2("酸","suān","acide"),
  N("Sucré se dit [[甜|tián]]."),
  ...teach2("甜","tián","sucré"),
  N("Amer se dit [[苦|kǔ]]."),
  ...teach2("苦","kǔ","amer"),
  N("Pimenté, piquant à cause du piment, se dit [[辣|là]]."),
  ...teach2("辣","là","pimenté, piquant"),
  N("Salé se dit [[咸|xián]]."),
  ...teach2("咸","xián","salé"),

  N("Pour dire « à la fois acide et pimenté », le chinois encadre les deux adjectifs avec [[又|yòu]] : [[又酸又辣|yòu suān yòu là]]."),
  ...teach2("这个汤又酸又辣。","Zhège tāng yòu suān yòu là.","Cette soupe est à la fois acide et pimentée."),
  N("Dites : cette soupe est à la fois acide et pimentée."), TH(),
  C("这个汤又酸又辣。","Zhège tāng yòu suān yòu là.","Cette soupe est à la fois acide et pimentée.",0.6), HOLD(),

  N("[[喜欢|xǐhuan]] veut dire « aimer ». Pour demander « quelle saveur aimes-tu ? », dites :"),
  ...teach2("你喜欢什么味道？","Nǐ xǐhuan shénme wèidào?","Quelle saveur aimes-tu ?"),
  N("Après un adjectif, [[的|de]] peut remplacer le nom sous-entendu. [[甜的|tián de]] signifie « ce qui est sucré ». Écoutez : j'aime manger ce qui est sucré."),
  ...teach2("我喜欢吃甜的。","Wǒ xǐhuan chī tián de.","J'aime manger ce qui est sucré."),
  N("À vous : dites « j'aime manger pimenté »."), TH(),
  C("我喜欢吃辣的。","Wǒ xǐhuan chī là de.","J'aime manger pimenté.",0.6), HOLD(),
  N("[[太|tài]] signifie « trop ». Dites : je n'aime pas ce qui est trop salé."), TH(),
  C("我不喜欢吃太咸的。","Wǒ bù xǐhuan chī tài xián de.","Je n'aime pas ce qui est trop salé.",0.6), HOLD(),

  N("Mini-conversation. On vous demande :"),
  C("你喜欢什么味道？","Nǐ xǐhuan shénme wèidào?","Quelle saveur aimes-tu ?",0.6),
  N("Répondez : j'aime manger ce qui est sucré. Et toi ?"), TH(),
  C("我喜欢吃甜的。你呢？","Wǒ xǐhuan chī tián de. Nǐ ne?","J'aime manger ce qui est sucré. Et toi ?",0.6),
  C("我喜欢吃辣的。","Wǒ xǐhuan chī là de.","J'aime manger pimenté.",0.6), HOLD(),

  N("Révision finale. Dites : acide."), TH(), C("酸","suān","acide",0.65),
  N("Sucré."), TH(), C("甜","tián","sucré",0.65),
  N("Amer."), TH(), C("苦","kǔ","amer",0.65),
  N("Pimenté."), TH(), C("辣","là","pimenté",0.65),
  N("Salé."), TH(), C("咸","xián","salé",0.65),
  N("Demandez : quelle saveur aimes-tu ?"), TH(),
  C("你喜欢什么味道？","Nǐ xǐhuan shénme wèidào?","Quelle saveur aimes-tu ?",0.65),
  N("Bravo. Fin de la leçon 2. La prochaine fois : les plats et les ingrédients."),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

// ================= PARTIE 3 =================
  { num:3, hanzi:"菜肴", title:"Plats et ingrédients", desc:"北京烤鸭 · 西红柿炒鸡蛋 · 拌黄瓜 · 宫保鸡丁 · 食材",
    build(){ return [
  N("Leçon 3. Aujourd'hui : reconnaître des plats chinois et parler des ingrédients. Révision. Demandez : quelle saveur aimes-tu ?"), TH(),
  C("你喜欢什么味道？","Nǐ xǐhuan shénme wèidào?","Quelle saveur aimes-tu ?",0.65),
  N("Répondez : j'aime manger pimenté."), TH(),
  C("我喜欢吃辣的。","Wǒ xǐhuan chī là de.","J'aime manger pimenté.",0.65), HOLD(),

  N("Écoutez la conversation cible."),
  C("你喜欢吃什么？","Nǐ xǐhuan chī shénme?","Qu'aimes-tu manger ?",0.4), P(2,"…"),
  C("我喜欢吃鱼和蔬菜。","Wǒ xǐhuan chī yú hé shūcài.","J'aime manger du poisson et des légumes.",0.4), P(2,"…"),
  C("你不喜欢吃什么？","Nǐ bù xǐhuan chī shénme?","Qu'est-ce que tu n'aimes pas manger ?",0.4), P(2,"…"),
  C("我不喜欢吃洋葱。","Wǒ bù xǐhuan chī yángcōng.","Je n'aime pas manger d'oignon.",0.4),

  N("Un plat cuisiné ou un mets se dit [[菜肴|càiyáo]]. Voici cinq plats du document."),
  ...teach2("菜肴","càiyáo","plat cuisiné, mets"),
  N("Le canard laqué de Pékin : [[北京烤鸭|Běijīng kǎoyā]]."),
  ...teach2("北京烤鸭","Běijīng kǎoyā","canard laqué de Pékin"),
  N("Les œufs sautés à la tomate : [[西红柿炒鸡蛋|xīhóngshì chǎo jīdàn]]. Le nom décrit les ingrédients et la cuisson : tomate, sauter, œuf."),
  ...teach2("西红柿炒鸡蛋","xīhóngshì chǎo jīdàn","œufs sautés à la tomate"),
  N("La salade de concombre assaisonnée : [[拌黄瓜|bàn huángguā]]."),
  ...teach2("拌黄瓜","bàn huángguā","concombre assaisonné"),
  N("La soupe aigre-piquante : [[酸辣汤|suānlà tāng]]."),
  ...teach2("酸辣汤","suānlà tāng","soupe aigre-piquante"),
  N("Le poulet Gong Bao : [[宫保鸡丁|gōngbǎo jīdīng]]."),
  ...teach2("宫保鸡丁","gōngbǎo jīdīng","poulet Gong Bao"),

  N("Quelques ingrédients très utiles. Le poisson se dit [[鱼|yú]]."),
  ...teach2("鱼","yú","poisson"),
  N("Les légumes se disent [[蔬菜|shūcài]]."),
  ...teach2("蔬菜","shūcài","légumes"),
  N("Le porc se dit [[猪肉|zhūròu]]."),
  ...teach2("猪肉","zhūròu","porc"),
  N("L'oignon se dit [[洋葱|yángcōng]]."),
  ...teach2("洋葱","yángcōng","oignon"),
  N("La coriandre se dit [[香菜|xiāngcài]]."),
  ...teach2("香菜","xiāngcài","coriandre"),

  N("Demandez : qu'aimes-tu manger ?"), TH(),
  C("你喜欢吃什么？","Nǐ xǐhuan chī shénme?","Qu'aimes-tu manger ?",0.6),
  N("Répondez : j'aime manger du poisson et des légumes."), TH(),
  C("我喜欢吃鱼和蔬菜。","Wǒ xǐhuan chī yú hé shūcài.","J'aime manger du poisson et des légumes.",0.6), HOLD(),
  N("Demandez : qu'est-ce que tu n'aimes pas manger ?"), TH(),
  C("你不喜欢吃什么？","Nǐ bù xǐhuan chī shénme?","Qu'est-ce que tu n'aimes pas manger ?",0.6),
  N("Répondez : je n'aime pas manger d'oignon."), TH(),
  C("我不喜欢吃洋葱。","Wǒ bù xǐhuan chī yángcōng.","Je n'aime pas manger d'oignon.",0.6), HOLD(),

  N("Attention : « je n'aime pas le porc » et « je ne mange pas de porc » ne donnent pas la même information. Pour signaler une vraie restriction, dites :"),
  ...teach2("我不吃猪肉。","Wǒ bù chī zhūròu.","Je ne mange pas de porc."),

  N("Révision finale. Dites : canard laqué de Pékin."), TH(), C("北京烤鸭","Běijīng kǎoyā","canard laqué de Pékin",0.65),
  N("Œufs sautés à la tomate."), TH(), C("西红柿炒鸡蛋","xīhóngshì chǎo jīdàn","œufs sautés à la tomate",0.65),
  N("Soupe aigre-piquante."), TH(), C("酸辣汤","suānlà tāng","soupe aigre-piquante",0.65),
  N("Je ne mange pas de porc."), TH(), C("我不吃猪肉。","Wǒ bù chī zhūròu.","Je ne mange pas de porc.",0.65),
  N("Très bien. Fin de la leçon 3. À la prochaine leçon, vous apprendrez à compter les portions."),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

// ================= PARTIE 4 =================
  { num:4, hanzi:"一碗米饭", title:"Quantités et classificateurs", desc:"碗 · 盘 · 杯 · 瓶 · 壶 · 份 · 只",
    build(){ return [
  N("Leçon 4. Aujourd'hui : commander la bonne quantité avec les classificateurs. Révision. Dites : soupe aigre-piquante."), TH(),
  C("酸辣汤","suānlà tāng","soupe aigre-piquante",0.65),
  N("Dites : je ne mange pas de porc."), TH(),
  C("我不吃猪肉。","Wǒ bù chī zhūròu.","Je ne mange pas de porc.",0.65), HOLD(),

  N("Écoutez le dialogue cible."),
  C("主食点什么？","Zhǔshí diǎn shénme?","Que prenez-vous comme féculent ?",0.4), P(2,"…"),
  C("两碗米饭，一盘饺子。","Liǎng wǎn mǐfàn, yì pán jiǎozi.","Deux bols de riz et une assiette de raviolis.",0.4), P(2,"…"),
  C("再来一瓶水。","Zài lái yì píng shuǐ.","Et encore une bouteille d'eau.",0.4),

  N("En chinois, un nombre est normalement suivi d'un classificateur avant le nom. Un bol se dit [[碗|wǎn]]. « Un bol de riz » :"),
  ...teach2("一碗米饭","yì wǎn mǐfàn","un bol de riz"),
  N("Avec deux, on emploie [[两|liǎng]] devant le classificateur : deux bols de riz."),
  ...teach2("两碗米饭","liǎng wǎn mǐfàn","deux bols de riz"),
  N("Une assiette se dit [[盘|pán]]. Une assiette de raviolis :"),
  ...teach2("一盘饺子","yì pán jiǎozi","une assiette de raviolis"),
  N("Une tasse ou un verre se compte avec [[杯|bēi]]. Une tasse de thé :"),
  ...teach2("一杯茶","yì bēi chá","une tasse de thé"),
  N("Une bouteille se compte avec [[瓶|píng]]. Une bouteille d'eau :"),
  ...teach2("一瓶水","yì píng shuǐ","une bouteille d'eau"),
  N("Une théière se compte avec [[壶|hú]]. Une théière de thé :"),
  ...teach2("一壶茶","yì hú chá","une théière de thé"),
  N("Pour une portion de plat, [[份|fèn]] est très pratique. Une portion de poulet Gong Bao :"),
  ...teach2("一份宫保鸡丁","yí fèn gōngbǎo jīdīng","une portion de poulet Gong Bao"),
  N("Pour un canard entier, on utilise [[只|zhī]]. Un canard laqué de Pékin :"),
  ...teach2("一只北京烤鸭","yì zhī Běijīng kǎoyā","un canard laqué de Pékin"),

  N("Vous entendez parfois [[一|yī]] prononcé yì ou yí. C'est un changement de ton naturel. Devant un premier, deuxième ou troisième ton, il se prononce généralement yì ; devant un quatrième ton, yí."),
  N("Dites : deux bols de riz et une assiette de raviolis."), TH(),
  C("两碗米饭，一盘饺子。","Liǎng wǎn mǐfàn, yì pán jiǎozi.","Deux bols de riz et une assiette de raviolis.",0.6), HOLD(),
  N("Dites : une tasse de thé."), TH(),
  C("一杯茶。","Yì bēi chá.","Une tasse de thé.",0.65), HOLD(),
  N("Dites : une portion de poulet Gong Bao."), TH(),
  C("一份宫保鸡丁。","Yí fèn gōngbǎo jīdīng.","Une portion de poulet Gong Bao.",0.6), HOLD(),

  N("Le mot [[再|zài]] permet d'ajouter quelque chose : encore, en plus. [[来|lái]], littéralement « venir », est une formule orale très courante pour commander : « apportez-moi »."),
  ...teach2("再来一瓶水。","Zài lái yì píng shuǐ.","Et encore une bouteille d'eau."),

  N("Mini-conversation."),
  C("主食点什么？","Zhǔshí diǎn shénme?","Que prenez-vous comme féculent ?",0.6),
  N("Répondez : deux bols de riz et une assiette de raviolis."), TH(),
  C("两碗米饭，一盘饺子。","Liǎng wǎn mǐfàn, yì pán jiǎozi.","Deux bols de riz et une assiette de raviolis.",0.6),
  N("Ajoutez : et encore une bouteille d'eau."), TH(),
  C("再来一瓶水。","Zài lái yì píng shuǐ.","Et encore une bouteille d'eau.",0.6), HOLD(),

  N("Révision finale. Un bol de riz."), TH(), C("一碗米饭","yì wǎn mǐfàn","un bol de riz",0.65),
  N("Une assiette de raviolis."), TH(), C("一盘饺子","yì pán jiǎozi","une assiette de raviolis",0.65),
  N("Une bouteille d'eau."), TH(), C("一瓶水","yì píng shuǐ","une bouteille d'eau",0.65),
  N("Une théière de thé."), TH(), C("一壶茶","yì hú chá","une théière de thé",0.65),
  N("Excellent. Fin de la leçon 4. La prochaine fois, vous passerez une commande complète."),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

// ================= PARTIE 5 =================
  { num:5, hanzi:"点菜", title:"Passer une commande", desc:"点 · 来 · 再 · 想要 · 您想吃点儿什么",
    build(){ return [
  N("Leçon 5. Aujourd'hui : passer une commande complète et polie. Révision. Dites : deux bols de riz."), TH(),
  C("两碗米饭。","Liǎng wǎn mǐfàn.","Deux bols de riz.",0.65),
  N("Ajoutez : et encore une bouteille d'eau."), TH(),
  C("再来一瓶水。","Zài lái yì píng shuǐ.","Et encore une bouteille d'eau.",0.65), HOLD(),

  N("Écoutez le dialogue cible."),
  C("您想吃点儿什么？","Nín xiǎng chī diǎnr shénme?","Que souhaitez-vous manger ?",0.4), P(2,"…"),
  C("来一个北京烤鸭，再来一个拌黄瓜。","Lái yí ge Běijīng kǎoyā, zài lái yí ge bàn huángguā.","Un canard laqué et aussi un concombre assaisonné.",0.4), P(2,"…"),
  C("主食点什么？","Zhǔshí diǎn shénme?","Que prenez-vous comme féculent ?",0.4), P(2,"…"),
  C("两碗米饭，一盘饺子。","Liǎng wǎn mǐfàn, yì pán jiǎozi.","Deux bols de riz et une assiette de raviolis.",0.4),

  N("[[点菜|diǎncài]] signifie « commander les plats ». Attention : [[点|diǎn]] est ici le verbe commander, tandis que [[点儿|diǎnr]] signifie « un peu »."),
  ...teach2("点菜","diǎncài","commander les plats"),
  N("Le serveur demande poliment : que souhaitez-vous manger ?"),
  ...teach2("您想吃点儿什么？","Nín xiǎng chī diǎnr shénme?","Que souhaitez-vous manger ?"),
  N("À vous : posez cette question."), TH(),
  C("您想吃点儿什么？","Nín xiǎng chī diǎnr shénme?","Que souhaitez-vous manger ?",0.6), HOLD(),

  N("Pour commander à l'oral, [[来|lái]] suivi de la quantité signifie « apportez » ou « je prends ». Dites : une soupe aigre-piquante."), TH(),
  C("来一个酸辣汤。","Lái yí ge suānlà tāng.","Une soupe aigre-piquante.",0.6), HOLD(),
  N("Pour ajouter un plat, utilisez [[再来|zài lái]], « et aussi ». Écoutez : un plat d'œufs à la tomate, puis une soupe aigre-piquante."),
  ...teach2("来一个西红柿炒鸡蛋，再来一个酸辣汤。","Lái yí ge xīhóngshì chǎo jīdàn, zài lái yí ge suānlà tāng.","Un plat d'œufs à la tomate, puis une soupe aigre-piquante."),
  N("Dites : un canard laqué et aussi un concombre assaisonné."), TH(),
  C("来一个北京烤鸭，再来一个拌黄瓜。","Lái yí ge Běijīng kǎoyā, zài lái yí ge bàn huángguā.","Un canard laqué et aussi un concombre assaisonné.",0.55), HOLD(),

  N("[[我要|wǒ yào]] signifie « je veux, je prends ». C'est correct, mais direct. Pour adoucir, dites [[我想要|wǒ xiǎng yào]], « je voudrais »."),
  ...teach2("我想要一个汤。","Wǒ xiǎng yào yí ge tāng.","Je voudrais une soupe."),
  N("Encore plus poli, [[麻烦|máfan]] signifie ici « je vous prie de »."),
  ...teach2("麻烦来一份宫保鸡丁。","Máfan lái yí fèn gōngbǎo jīdīng.","Un poulet Gong Bao, s'il vous plaît."),

  N("Jouons la scène. Vous êtes le client."),
  C("您想吃点儿什么？","Nín xiǎng chī diǎnr shénme?","Que souhaitez-vous manger ?",0.6),
  N("Commandez un canard laqué et un concombre assaisonné."), TH(),
  C("来一个北京烤鸭，再来一个拌黄瓜。","Lái yí ge Běijīng kǎoyā, zài lái yí ge bàn huángguā.","Un canard laqué et aussi un concombre assaisonné.",0.55),
  C("主食点什么？","Zhǔshí diǎn shénme?","Que prenez-vous comme féculent ?",0.6),
  N("Répondez : deux bols de riz et une assiette de raviolis."), TH(),
  C("两碗米饭，一盘饺子。","Liǎng wǎn mǐfàn, yì pán jiǎozi.","Deux bols de riz et une assiette de raviolis.",0.6), HOLD(),

  N("Révision finale. Demandez : que souhaitez-vous manger ?"), TH(),
  C("您想吃点儿什么？","Nín xiǎng chī diǎnr shénme?","Que souhaitez-vous manger ?",0.65),
  N("Je voudrais une soupe."), TH(), C("我想要一个汤。","Wǒ xiǎng yào yí ge tāng.","Je voudrais une soupe.",0.65),
  N("Un poulet Gong Bao, s'il vous plaît."), TH(),
  C("麻烦来一份宫保鸡丁。","Máfan lái yí fèn gōngbǎo jīdīng.","Un poulet Gong Bao, s'il vous plaît.",0.6),
  N("Très bien. Fin de la leçon 5. À la prochaine leçon : boissons et restrictions alimentaires."),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

// ================= PARTIE 6 =================
  { num:6, hanzi:"忌口", title:"Boissons et restrictions alimentaires", desc:"还是 · 忌口 · 别太辣 · 不要放 · 过敏",
    build(){ return [
  N("Leçon 6. Aujourd'hui : choisir une boisson et signaler clairement une restriction alimentaire. Révision. Demandez poliment : que souhaitez-vous manger ?"), TH(),
  C("您想吃点儿什么？","Nín xiǎng chī diǎnr shénme?","Que souhaitez-vous manger ?",0.65),
  N("Commandez une portion de poulet Gong Bao."), TH(),
  C("麻烦来一份宫保鸡丁。","Máfan lái yí fèn gōngbǎo jīdīng.","Un poulet Gong Bao, s'il vous plaît.",0.6), HOLD(),

  N("Écoutez le dialogue cible."),
  C("你喝茶还是可乐？","Nǐ hē chá háishì kělè?","Tu prends du thé ou du Coca-Cola ?",0.4), P(2,"…"),
  C("我喝茶。","Wǒ hē chá.","Je prends du thé.",0.4), P(2,"…"),
  C("您有什么忌口的吗？","Nín yǒu shénme jìkǒu de ma?","Avez-vous des restrictions alimentaires ?",0.4), P(2,"…"),
  C("我不吃猪肉，也不要放香菜。","Wǒ bù chī zhūròu, yě bú yào fàng xiāngcài.","Je ne mange pas de porc et ne mettez pas non plus de coriandre.",0.4),

  N("Le thé se dit [[茶|chá]], l'eau [[水|shuǐ]], et le Coca-Cola [[可乐|kělè]]."),
  ...teach2("茶、水、可乐","chá, shuǐ, kělè","thé, eau, Coca-Cola"),
  N("Dans une question à choix, placez [[还是|háishì]] entre les deux possibilités. On n'ajoute normalement pas [[吗|ma]] à la fin."),
  ...teach2("你喝茶还是可乐？","Nǐ hē chá háishì kělè?","Tu prends du thé ou du Coca-Cola ?"),
  N("Répondez : je prends du thé."), TH(),
  C("我喝茶。","Wǒ hē chá.","Je prends du thé.",0.65), HOLD(),
  N("Demandez : du thé ou de l'eau ?"), TH(),
  C("你喝茶还是水？","Nǐ hē chá háishì shuǐ?","Tu prends du thé ou de l'eau ?",0.65), HOLD(),

  N("Une restriction ou un aliment que l'on évite se dit [[忌口|jìkǒu]]. Le serveur demande : avez-vous des restrictions alimentaires ?"),
  ...teach2("您有什么忌口的吗？","Nín yǒu shénme jìkǒu de ma?","Avez-vous des restrictions alimentaires ?"),
  N("Dites : je ne mange pas de porc."), TH(),
  C("我不吃猪肉。","Wǒ bù chī zhūròu.","Je ne mange pas de porc.",0.65), HOLD(),

  N("Pour demander que le plat ne soit pas trop pimenté, dites [[别太辣|bié tài là]]."),
  ...teach2("别太辣。","Bié tài là.","Pas trop pimenté, s'il vous plaît."),
  N("Une formulation plus explicite est : ne mettez pas de coriandre. [[放|fàng]] signifie « mettre »."),
  ...teach2("不要放香菜。","Bú yào fàng xiāngcài.","Ne mettez pas de coriandre."),
  N("Pour demander moins de piment :"),
  ...teach2("少放点儿辣椒。","Shǎo fàng diǎnr làjiāo.","Mettez un peu moins de piment."),

  N("Pour une allergie, soyez explicite. [[花生|huāshēng]] signifie « cacahuète » et [[过敏|guòmǐn]] « être allergique »."),
  ...teach2("我对花生过敏。","Wǒ duì huāshēng guòmǐn.","Je suis allergique aux cacahuètes."),
  N("Dites : je suis allergique aux cacahuètes."), TH(),
  C("我对花生过敏。","Wǒ duì huāshēng guòmǐn.","Je suis allergique aux cacahuètes.",0.6), HOLD(),

  N("Mini-conversation."),
  C("您有什么忌口的吗？","Nín yǒu shénme jìkǒu de ma?","Avez-vous des restrictions alimentaires ?",0.6),
  N("Répondez : je ne mange pas de porc et ne mettez pas non plus de coriandre."), TH(),
  C("我不吃猪肉，也不要放香菜。","Wǒ bù chī zhūròu, yě bú yào fàng xiāngcài.","Je ne mange pas de porc et ne mettez pas non plus de coriandre.",0.55), HOLD(),

  N("Révision finale. Demandez : thé ou Coca-Cola ?"), TH(),
  C("你喝茶还是可乐？","Nǐ hē chá háishì kělè?","Tu prends du thé ou du Coca-Cola ?",0.65),
  N("Avez-vous des restrictions alimentaires ?"), TH(),
  C("您有什么忌口的吗？","Nín yǒu shénme jìkǒu de ma?","Avez-vous des restrictions alimentaires ?",0.65),
  N("Pas trop pimenté."), TH(), C("别太辣。","Bié tài là.","Pas trop pimenté.",0.65),
  N("Ne mettez pas de coriandre."), TH(), C("不要放香菜。","Bú yào fàng xiāngcài.","Ne mettez pas de coriandre.",0.65),
  N("Excellent. Fin de la leçon 6. À la prochaine leçon : les couverts, l'accueil et l'addition."),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

// ================= PARTIE 7 =================
  { num:7, hanzi:"买单", title:"Service, couverts et addition", desc:"几位 · 筷子 · 勺子 · 请给我 · 稍等 · 买单 · 一共",
    build(){ return [
  N("Leçon 7. Aujourd'hui : de votre arrivée au restaurant jusqu'à l'addition. Révision. Dites : pas trop pimenté."), TH(),
  C("别太辣。","Bié tài là.","Pas trop pimenté.",0.65),
  N("Dites : je suis allergique aux cacahuètes."), TH(),
  C("我对花生过敏。","Wǒ duì huāshēng guòmǐn.","Je suis allergique aux cacahuètes.",0.6), HOLD(),

  N("Écoutez la scène cible."),
  C("欢迎光临，您几位？","Huānyíng guānglín, nín jǐ wèi?","Bienvenue. Vous êtes combien ?",0.4), P(2,"…"),
  C("两位。","Liǎng wèi.","Deux personnes.",0.4), P(2,"…"),
  C("两位坐这儿吧。这是菜单。","Liǎng wèi zuò zhèr ba. Zhè shì càidān.","Asseyez-vous ici. Voici le menu.",0.4), P(2,"…"),
  C("服务员，请给我一双筷子。","Fúwùyuán, qǐng gěi wǒ yì shuāng kuàizi.","Une paire de baguettes, s'il vous plaît.",0.4), P(2,"…"),
  C("好的，请稍等。","Hǎo de, qǐng shāo děng.","Très bien, veuillez patienter.",0.4), P(2,"…"),
  C("你好，麻烦买单。","Nǐ hǎo, máfan mǎidān.","Bonjour, l'addition s'il vous plaît.",0.4), P(2,"…"),
  C("一共五十六块。","Yígòng wǔshíliù kuài.","Cela fait 56 yuans au total.",0.4),

  N("[[欢迎光临|huānyíng guānglín]] signifie « bienvenue dans notre établissement ». [[位|wèi]] est un classificateur poli pour les personnes."),
  ...teach2("欢迎光临，您几位？","Huānyíng guānglín, nín jǐ wèi?","Bienvenue. Vous êtes combien ?"),
  N("Répondez : deux personnes."), TH(),
  C("两位。","Liǎng wèi.","Deux personnes.",0.65), HOLD(),

  N("Le serveur vous invite à vous asseoir ici et vous donne le menu."),
  ...teach2("两位坐这儿吧。这是菜单。","Liǎng wèi zuò zhèr ba. Zhè shì càidān.","Asseyez-vous ici. Voici le menu."),

  N("À table, les baguettes se disent [[筷子|kuàizi]]. Une paire se compte avec [[双|shuāng]]."),
  ...teach2("一双筷子","yì shuāng kuàizi","une paire de baguettes"),
  N("Une cuillère se dit [[勺子|sháozi]] et se compte avec [[把|bǎ]]."),
  ...teach2("一把勺子","yì bǎ sháozi","une cuillère"),
  N("Pour demander un objet poliment : [[请给我|qǐng gěi wǒ]], « donnez-moi, s'il vous plaît », puis l'objet."),
  ...teach2("服务员，请给我一双筷子。","Fúwùyuán, qǐng gěi wǒ yì shuāng kuàizi.","Une paire de baguettes, s'il vous plaît."),
  N("Demandez : pourriez-vous me donner une cuillère ?"), TH(),
  C("可以给我一把勺子吗？","Kěyǐ gěi wǒ yì bǎ sháozi ma?","Pourriez-vous me donner une cuillère ?",0.6), HOLD(),

  N("Le serveur répond souvent [[请稍等|qǐng shāo děng]], « veuillez patienter un instant »."),
  ...teach2("好的，请稍等。","Hǎo de, qǐng shāo děng.","Très bien, veuillez patienter."),
  N("Pour demander l'addition, [[买单|mǎidān]] est très courant. Une formulation douce :"),
  ...teach2("你好，麻烦买单。","Nǐ hǎo, máfan mǎidān.","Bonjour, l'addition s'il vous plaît."),
  N("[[一共|yígòng]] veut dire « au total », et [[块|kuài]] est l'unité monétaire familière pour le yuan."),
  ...teach2("一共五十六块。","Yígòng wǔshíliù kuài.","Cela fait 56 yuans au total."),

  N("Jouons la fin du repas. Demandez une paire de baguettes."), TH(),
  C("服务员，请给我一双筷子。","Fúwùyuán, qǐng gěi wǒ yì shuāng kuàizi.","Une paire de baguettes, s'il vous plaît.",0.6),
  C("好的，请稍等。","Hǎo de, qǐng shāo děng.","Très bien, veuillez patienter.",0.65),
  N("Puis demandez poliment l'addition."), TH(),
  C("你好，麻烦买单。","Nǐ hǎo, máfan mǎidān.","Bonjour, l'addition s'il vous plaît.",0.65),
  C("一共五十六块。","Yígòng wǔshíliù kuài.","Cela fait 56 yuans au total.",0.65), HOLD(),

  N("Révision finale. Vous êtes combien ?"), TH(), C("您几位？","Nín jǐ wèi?","Vous êtes combien ?",0.65),
  N("Deux personnes."), TH(), C("两位。","Liǎng wèi.","Deux personnes.",0.65),
  N("Une paire de baguettes, s'il vous plaît."), TH(),
  C("请给我一双筷子。","Qǐng gěi wǒ yì shuāng kuàizi.","Une paire de baguettes, s'il vous plaît.",0.65),
  N("L'addition, s'il vous plaît."), TH(),
  C("你好，麻烦买单。","Nǐ hǎo, máfan mǎidān.","L'addition, s'il vous plaît.",0.65),
  N("Bravo. Fin de la leçon 7. La dernière leçon sera une grande révision, avec une commande sur place et par téléphone."),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

// ================= PARTIE 8 =================
  { num:8, hanzi:"总复习", title:"★ Révision totale et commande téléphonique", desc:"Restaurant complet · restrictions · addition · 订餐 · 送到",
    build(){ return [
  N("Bienvenue dans la révision totale du chapitre Parler de la nourriture. Cette leçon est presque entièrement composée de questions. Répondez avant d'écouter la solution."),

  N("Dites : voici le menu."), TH(),
  C("这是菜单。","Zhè shì càidān.","Voici le menu.",0.65), P(1.5,"…"),
  N("Dites : plats froids, plats chauds, soupes, féculents, boissons."), TH(),
  C("凉菜、热菜、汤、主食、饮料。","Liángcài, rècài, tāng, zhǔshí, yǐnliào.","Plats froids, plats chauds, soupes, féculents, boissons.",0.6), P(1.5,"…"),

  N("Demandez : quelle saveur aimes-tu ?"), TH(),
  C("你喜欢什么味道？","Nǐ xǐhuan shénme wèidào?","Quelle saveur aimes-tu ?",0.65), P(1.5,"…"),
  N("Dites : j'aime manger ce qui est sucré."), TH(),
  C("我喜欢吃甜的。","Wǒ xǐhuan chī tián de.","J'aime manger ce qui est sucré.",0.65), P(1.5,"…"),
  N("Dites : cette soupe est à la fois acide et pimentée."), TH(),
  C("这个汤又酸又辣。","Zhège tāng yòu suān yòu là.","Cette soupe est à la fois acide et pimentée.",0.6), P(1.5,"…"),

  N("Dites : canard laqué de Pékin."), TH(),
  C("北京烤鸭","Běijīng kǎoyā","canard laqué de Pékin",0.65), P(1.5,"…"),
  N("Dites : œufs sautés à la tomate."), TH(),
  C("西红柿炒鸡蛋","xīhóngshì chǎo jīdàn","œufs sautés à la tomate",0.65), P(1.5,"…"),
  N("Dites : soupe aigre-piquante."), TH(),
  C("酸辣汤","suānlà tāng","soupe aigre-piquante",0.65), P(1.5,"…"),

  N("Dites : deux bols de riz et une assiette de raviolis."), TH(),
  C("两碗米饭，一盘饺子。","Liǎng wǎn mǐfàn, yì pán jiǎozi.","Deux bols de riz et une assiette de raviolis.",0.6), P(1.5,"…"),
  N("Ajoutez : et encore une bouteille d'eau."), TH(),
  C("再来一瓶水。","Zài lái yì píng shuǐ.","Et encore une bouteille d'eau.",0.65), P(1.5,"…"),

  N("Le restaurant vous accueille. Répondez à la question."),
  C("欢迎光临，您几位？","Huānyíng guānglín, nín jǐ wèi?","Bienvenue. Vous êtes combien ?",0.6),
  N("Dites : deux personnes."), TH(),
  C("两位。","Liǎng wèi.","Deux personnes.",0.65), P(1.5,"…"),
  C("您想吃点儿什么？","Nín xiǎng chī diǎnr shénme?","Que souhaitez-vous manger ?",0.6),
  N("Commandez poliment une portion de poulet Gong Bao et un concombre assaisonné."), TH(),
  C("麻烦来一份宫保鸡丁，再来一个拌黄瓜。","Máfan lái yí fèn gōngbǎo jīdīng, zài lái yí ge bàn huángguā.","Un poulet Gong Bao et un concombre assaisonné, s'il vous plaît.",0.55), P(1.5,"…"),
  C("主食点什么？","Zhǔshí diǎn shénme?","Que prenez-vous comme féculent ?",0.6),
  N("Répondez : deux bols de riz."), TH(),
  C("两碗米饭。","Liǎng wǎn mǐfàn.","Deux bols de riz.",0.65), P(1.5,"…"),
  C("你喝茶还是可乐？","Nǐ hē chá háishì kělè?","Tu prends du thé ou du Coca-Cola ?",0.6),
  N("Répondez : je prends du thé."), TH(),
  C("我喝茶。","Wǒ hē chá.","Je prends du thé.",0.65), P(1.5,"…"),

  C("您有什么忌口的吗？","Nín yǒu shénme jìkǒu de ma?","Avez-vous des restrictions alimentaires ?",0.6),
  N("Dites : je ne mange pas de porc et ne mettez pas de coriandre."), TH(),
  C("我不吃猪肉，也不要放香菜。","Wǒ bù chī zhūròu, yě bú yào fàng xiāngcài.","Je ne mange pas de porc et ne mettez pas non plus de coriandre.",0.55), P(1.5,"…"),
  N("Ajoutez : je suis allergique aux cacahuètes."), TH(),
  C("我对花生过敏。","Wǒ duì huāshēng guòmǐn.","Je suis allergique aux cacahuètes.",0.6), P(1.5,"…"),

  N("Demandez une paire de baguettes."), TH(),
  C("服务员，请给我一双筷子。","Fúwùyuán, qǐng gěi wǒ yì shuāng kuàizi.","Une paire de baguettes, s'il vous plaît.",0.6), P(1.5,"…"),
  N("Demandez poliment l'addition."), TH(),
  C("你好，麻烦买单。","Nǐ hǎo, máfan mǎidān.","Bonjour, l'addition s'il vous plaît.",0.65),
  C("一共五十六块。","Yígòng wǔshíliù kuài.","Cela fait 56 yuans au total.",0.65), HOLD(),

  N("Dernière situation : commander par téléphone. Écoutez d'abord les trois phrases."),
  C("你好，是北京餐厅吗？我想订餐。","Nǐ hǎo, shì Běijīng Cāntīng ma? Wǒ xiǎng dìngcān.","Bonjour, c'est bien le restaurant Beijing ? Je voudrais commander un repas.",0.5),
  C("我要一个宫保鸡丁、一个拌黄瓜和两碗米饭。","Wǒ yào yí ge gōngbǎo jīdīng, yí ge bàn huángguā hé liǎng wǎn mǐfàn.","Je voudrais un poulet Gong Bao, un concombre assaisonné et deux bols de riz.",0.5),
  C("请送到和平路十五号。","Qǐng sòng dào Hépíng Lù shíwǔ hào.","Livrez au 15, rue Heping, s'il vous plaît.",0.55),

  N("Appelez et dites : bonjour, c'est bien le restaurant Beijing ? Je voudrais commander un repas."), TH(),
  C("你好，是北京餐厅吗？我想订餐。","Nǐ hǎo, shì Běijīng Cāntīng ma? Wǒ xiǎng dìngcān.","Bonjour, c'est bien le restaurant Beijing ? Je voudrais commander un repas.",0.55),
  N("Commandez un poulet Gong Bao, un concombre assaisonné et deux bols de riz."), TH(),
  C("我要一个宫保鸡丁、一个拌黄瓜和两碗米饭。","Wǒ yào yí ge gōngbǎo jīdīng, yí ge bàn huángguā hé liǎng wǎn mǐfàn.","Je voudrais un poulet Gong Bao, un concombre assaisonné et deux bols de riz.",0.5),
  N("Donnez l'adresse : livrez au 15, rue Heping, s'il vous plaît."), TH(),
  C("请送到和平路十五号。","Qǐng sòng dào Hépíng Lù shíwǔ hào.","Livrez au 15, rue Heping, s'il vous plaît.",0.55), HOLD(),

  N("Félicitations ! Vous avez terminé le chapitre Parler de la nourriture. Vous savez lire les principales rubriques d'un menu, parler de vos goûts, commander, préciser une restriction alimentaire, demander un couvert et régler l'addition. Réécoutez cette révision jusqu'à pouvoir jouer les scènes sans regarder le texte."),
  C("祝你胃口好！","Zhù nǐ wèikǒu hǎo!","Bon appétit !",0.65),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  ]
});
