/* ============================================================
   Chapitre Bonus 2 · 谈日程安排 — Dates et planning
   D'après « 谈日程安排 cours planning » (话题一 谈日期 / 话题二 谈日程).
   Contenu uniquement : le moteur (helpers N, C, P, HOLD, TH,
   teach, drill et registerChapter) est défini dans
   engine/player.js, chargé AVANT ce fichier.
   Suppose le chapitre bonus 1 (Le temps) et le HSK 1 acquis :
   今天/昨天/明天, 今年/去年/明年, 星期一…星期六/星期日, 几月几号,
   多大, 时候, 事, 问题, 想, 送(HSK) déjà connus — pas re-enseignés ici.
   ============================================================ */
registerChapter({
  group: "bonus",
  id: "02-planning",
  badge: "★2",
  star: true,
  hanzi: "谈日程",
  title: "Bonus 2 · Dates et planning",
  desc: "Jours, années, anniversaires, fêtes et emploi du temps — 6 leçons",
  intro: "Six leçons dans l'esprit Pimsleur, à la suite du chapitre « Le temps ». Fais-les dans l'ordre : chaque leçon révise les précédentes. La leçon s'arrête quand c'est à toi de parler (désactivable avec « Mode continu »).",
  lessons: [

  { num:1, hanzi:"大前天，大后天", title:"Avant-hier, après-demain… et au-delà", desc:"前天 · 后天 · 大前天 · 大后天 · 前年 · 后年 · 大前年 · 大后年",
    build(){ return [
N("Bienvenue dans ce nouveau chapitre bonus, consacré aux dates et au planning. Aujourd'hui, on va au-delà d'hier, aujourd'hui et demain. Petite révision d'abord. Demandez : quelle est la date aujourd'hui ?"),
  TH(),
  C("今天几号？","Jīntiān jǐ hào?","Quelle est la date aujourd'hui ?",0.65),
  N("Et : quel jour de la semaine sommes-nous ?"),
  TH(),
  C("星期几？","Xīngqī jǐ?","Quel jour de la semaine ?",0.65),
  N("Dites : demain, j'ai cours."),
  TH(),
  C("明天我上课。","Míngtiān wǒ shàngkè.","Demain, j'ai cours.",0.65), HOLD(),

  // ---------- Dialogue cible ----------
  N("Écoutez la conversation d'aujourd'hui."),
  C("后天你做什么？","Hòutiān nǐ zuò shénme?","Que fais-tu après-demain ?",0.4),
  P(2,"…"),
  C("后天是星期六，我休息。大后天呢？","Hòutiān shì Xīngqīliù, wǒ xiūxi. Dàhòutiān ne?","Après-demain c'est samedi, je suis en repos. Et dans trois jours ?",0.4),
  P(2,"…"),
  C("大后天我要去北京。","Dàhòutiān wǒ yào qù Běijīng.","Dans trois jours, je dois aller à Pékin.",0.4),
  N("À la fin de cette leçon, cette conversation sera à vous."),

  // ---------- 前天 / 后天 ----------
  N("Vous connaissez [[昨天|zuótiān]], hier, et [[明天|míngtiān]], demain. « Avant-hier » se dit [[前天|qiántiān]] — littéralement « le jour d'avant ». Écoutez et répétez."),
  ...teach("前天","qiántiān","avant-hier"),
  N("« Après-demain » se dit [[后天|hòutiān]] — « le jour d'après »."),
  ...teach("后天","hòutiān","après-demain"),
  ...drill("Dites : avant-hier, j'avais cours.","前天我上课了。","Qiántiān wǒ shàngkè le.","Avant-hier, j'avais cours."),
  ...drill("Dites : après-demain, je suis en repos.","后天我休息。","Hòutiān wǒ xiūxi.","Après-demain, je suis en repos."),

  // ---------- 大前天 / 大后天 ----------
  N("Pour aller encore plus loin, on ajoute [[大|dà]] devant : « il y a trois jours » se dit [[大前天|dàqiántiān]]."),
  ...teach("大前天","dàqiántiān","il y a trois jours"),
  N("Et « dans trois jours » se dit [[大后天|dàhòutiān]]."),
  ...teach("大后天","dàhòutiān","dans trois jours"),
  N("Récapitulons dans l'ordre : il y a trois jours, avant-hier, hier, aujourd'hui, demain, après-demain, dans trois jours."),
  C("大前天，前天，昨天，今天，明天，后天，大后天。","Dàqiántiān, qiántiān, zuótiān, jīntiān, míngtiān, hòutiān, dàhòutiān.","Il y a 3 j, avant-hier, hier, aujourd'hui, demain, après-demain, dans 3 j.",0.5),
  ...drill("Dites : dans trois jours, j'irai à Pékin.","大后天我要去北京。","Dàhòutiān wǒ yào qù Běijīng.","Dans trois jours, j'irai à Pékin."),

  // ---------- 前年 / 后年 ----------
  N("La même logique s'applique aux années. Vous connaissez [[去年|qùnián]], l'an dernier, et [[明年|míngnián]], l'an prochain. « Il y a deux ans » se dit [[前年|qiánnián]]."),
  ...teach("前年","qiánnián","il y a deux ans"),
  N("« Dans deux ans » se dit [[后年|hòunián]]."),
  ...teach("后年","hòunián","dans deux ans"),
  ...drill("Dites : il y a deux ans, j'étais à Paris.","前年我在巴黎。","Qiánnián wǒ zài Bālí.","Il y a deux ans, j'étais à Paris."),

  // ---------- 大前年 / 大后年 ----------
  N("Et pour trois ans d'écart : [[大前年|dà qiánnián]], il y a trois ans."),
  ...teach("大前年","dà qiánnián","il y a trois ans"),
  N("[[大后年|dà hòunián]], dans trois ans."),
  ...teach("大后年","dà hòunián","dans trois ans"),
  N("Pour demander une année passée ou future, on utilise [[是哪一年|shì nǎ yì nián]] : « c'est quelle année ? ». Demandez : l'an prochain, ou dans deux ans, ou dans trois ans, c'est quelle année ?"),
  TH(),
  C("明年／后年／大后年是哪一年？","Míngnián / hòunián / dà hòunián shì nǎ yì nián?","L'an prochain / dans 2 ans / dans 3 ans, c'est quelle année ?",0.55), HOLD(),
  N("Répondez : cette année, c'est 2011."),
  TH(),
  C("今年是2011年。","Jīnnián shì èr líng yī yī nián.","Cette année, c'est 2011.",0.6), HOLD(),

  // ---------- Mini-conversation ----------
  N("Mini-conversation. On vous demande :"),
  C("后天你做什么？","Hòutiān nǐ zuò shénme?","Que fais-tu après-demain ?",0.65),
  N("Répondez : après-demain c'est samedi, je suis en repos."),
  TH(),
  C("后天是星期六，我休息。","Hòutiān shì Xīngqīliù, wǒ xiūxi.","Après-demain c'est samedi, je suis en repos.",0.6), HOLD(),
  C("大后天呢？","Dàhòutiān ne?","Et dans trois jours ?",0.65),
  N("Répondez : dans trois jours, je dois aller à Pékin."),
  TH(),
  C("大后天我要去北京。","Dàhòutiān wǒ yào qù Běijīng.","Dans trois jours, je dois aller à Pékin.",0.55),
  C("大后天我要去北京。","Dàhòutiān wǒ yào qù Běijīng.","Dans trois jours, je dois aller à Pékin.",0.6), HOLD(),

  // ---------- Révision finale ----------
  N("Révision finale. Dites : avant-hier."),
  TH(),
  C("前天","qiántiān","avant-hier",0.65),
  N("Après-demain."),
  TH(),
  C("后天","hòutiān","après-demain",0.65),
  N("Il y a trois jours."),
  TH(),
  C("大前天","dàqiántiān","il y a trois jours",0.65),
  N("Dans trois jours."),
  TH(),
  C("大后天","dàhòutiān","dans trois jours",0.65),
  N("Il y a deux ans."),
  TH(),
  C("前年","qiánnián","il y a deux ans",0.65),
  N("Dans deux ans."),
  TH(),
  C("后年","hòunián","dans deux ans",0.65),
  N("Excellent ! Vous savez maintenant vous situer jusqu'à trois jours et trois ans dans le passé ou le futur. Fin de la leçon 1. À demain pour la leçon 2 : les anniversaires !"),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:2, hanzi:"生日快乐", title:"Les anniversaires", desc:"生日 · 蛋糕 · 礼物 · 想要",
    build(){ return [
N("Bienvenue dans la leçon 2. Aujourd'hui : parler des anniversaires et des cadeaux. Révision. Demandez : quel âge a-t-il ?"),
  TH(),
  C("他多大？","Tā duō dà?","Quel âge a-t-il ?",0.65),
  N("Dites : après-demain, c'est mon anniversaire — enfin, vous allez apprendre ce mot dans un instant. D'abord, demandez la date d'aujourd'hui."),
  TH(),
  C("今天几月几号？","Jīntiān jǐ yuè jǐ hào?","Quelle est la date aujourd'hui ?",0.65), HOLD(),

  // ---------- Dialogue cible ----------
  N("Écoutez la conversation d'aujourd'hui, entre deux camarades de classe."),
  C("你的生日是几月几号？","Nǐ de shēngrì shì jǐ yuè jǐ hào?","C'est quand, ton anniversaire ?",0.4),
  P(2,"…"),
  C("我的生日是九月二十四号。","Wǒ de shēngrì shì jiǔ yuè èrshísì hào.","Mon anniversaire est le 24 septembre.",0.4),
  P(2,"…"),
  C("今年的生日你想要什么礼物？","Jīnnián de shēngrì nǐ xiǎngyào shénme lǐwù?","Pour ton anniversaire cette année, tu veux quel cadeau ?",0.4),
  P(2,"…"),
  C("我想要一个蛋糕。","Wǒ xiǎngyào yí ge dàngāo.","Je voudrais un gâteau.",0.4),
  N("À la fin de cette leçon, cette conversation sera à vous."),

  // ---------- 生日 ----------
  N("« L'anniversaire », le jour de naissance, se dit [[生日|shēngrì]]. Écoutez et répétez."),
  ...teach("生日","shēngrì","l'anniversaire"),
  N("Demandez : c'est quand, ton anniversaire ? Littéralement : ton anniversaire est quel mois, quel jour ?"),
  TH(),
  C("你的生日是几月几号？","Nǐ de shēngrì shì jǐ yuè jǐ hào?","C'est quand, ton anniversaire ?",0.6), HOLD(),
  N("Répondez avec votre propre date, ou avec cet exemple : mon anniversaire est le 24 septembre."),
  TH(),
  C("我的生日是九月二十四号。","Wǒ de shēngrì shì jiǔ yuè èrshísì hào.","Mon anniversaire est le 24 septembre.",0.6), HOLD(),

  // ---------- 礼物 / 蛋糕 ----------
  N("« Un cadeau », un présent, se dit [[礼物|lǐwù]]."),
  ...teach("礼物","lǐwù","un cadeau"),
  N("« Un gâteau » se dit [[蛋糕|dàngāo]]."),
  ...teach("蛋糕","dàngāo","un gâteau"),
  N("Pour dire « vouloir » un objet précis, on utilise [[想要|xiǎngyào]] — un peu plus fort que le simple [[想|xiǎng]] que vous connaissez déjà. Écoutez : je voudrais un gâteau."),
  ...teach("我想要一个蛋糕。","Wǒ xiǎngyào yí ge dàngāo.","Je voudrais un gâteau."),
  ...drill("Demandez : pour ton anniversaire cette année, tu veux quel cadeau ?","今年的生日你想要什么礼物？","Jīnnián de shēngrì nǐ xiǎngyào shénme lǐwù?","Pour ton anniversaire, tu veux quel cadeau ?"),
  ...drill("Répondez : je voudrais un cadeau.","我想要一个礼物。","Wǒ xiǎngyào yí ge lǐwù.","Je voudrais un cadeau."),

  // ---------- Enquête façon Pimsleur ----------
  N("Imaginez que vous faites une petite enquête sur les anniversaires de vos camarades. Demandez à quelqu'un : c'est quand, ton anniversaire ?"),
  TH(),
  C("你的生日是几月几号？","Nǐ de shēngrì shì jǐ yuè jǐ hào?","C'est quand, ton anniversaire ?",0.6),
  N("On vous répond : mon anniversaire est le 8 mars."),
  C("我的生日是三月八号。","Wǒ de shēngrì shì sān yuè bā hào.","Mon anniversaire est le 8 mars.",0.6),
  N("Demandez maintenant ce qu'il ou elle veut comme cadeau cette année."),
  TH(),
  C("今年的生日你想要什么礼物？","Jīnnián de shēngrì nǐ xiǎngyào shénme lǐwù?","Cette année, tu veux quel cadeau ?",0.6), HOLD(),

  // ---------- Rapporter l'information ----------
  N("Pour rapporter ce que vous avez appris à quelqu'un d'autre, on répète simplement les phrases avec le nom de la personne. Écoutez : l'anniversaire de Wang est le 8 mars, cette année pour son anniversaire elle veut un cadeau."),
  C("王的生日是三月八号，今年的生日她想要一个礼物。","Wáng de shēngrì shì sān yuè bā hào, jīnnián de shēngrì tā xiǎngyào yí ge lǐwù.","L'anniversaire de Wang est le 8 mars, elle veut un cadeau.",0.5),
  C("王的生日是三月八号，今年的生日她想要一个礼物。","Wáng de shēngrì shì sān yuè bā hào, jīnnián de shēngrì tā xiǎngyào yí ge lǐwù.","L'anniversaire de Wang est le 8 mars, elle veut un cadeau.",0.6), HOLD(),

  // ---------- Mini-conversation ----------
  N("Mini-conversation. Un ami vous demande :"),
  C("你的生日是几月几号？","Nǐ de shēngrì shì jǐ yuè jǐ hào?","C'est quand, ton anniversaire ?",0.65),
  N("Répondez avec votre date d'anniversaire — ou avec l'exemple : le 24 septembre."),
  TH(),
  C("我的生日是九月二十四号。","Wǒ de shēngrì shì jiǔ yuè èrshísì hào.","Mon anniversaire est le 24 septembre.",0.6),
  C("今年的生日你想要什么礼物？","Jīnnián de shēngrì nǐ xiǎngyào shénme lǐwù?","Cette année, tu veux quel cadeau ?",0.65),
  N("Répondez : je voudrais un gâteau."),
  TH(),
  C("我想要一个蛋糕。","Wǒ xiǎngyào yí ge dàngāo.","Je voudrais un gâteau.",0.65), HOLD(),

  // ---------- Révision finale ----------
  N("Révision finale. Dites : l'anniversaire."),
  TH(),
  C("生日","shēngrì","l'anniversaire",0.65),
  N("C'est quand, ton anniversaire ?"),
  TH(),
  C("你的生日是几月几号？","Nǐ de shēngrì shì jǐ yuè jǐ hào?","C'est quand, ton anniversaire ?",0.65),
  N("Un cadeau."),
  TH(),
  C("礼物","lǐwù","un cadeau",0.65),
  N("Je voudrais un gâteau."),
  TH(),
  C("我想要一个蛋糕。","Wǒ xiǎngyào yí ge dàngāo.","Je voudrais un gâteau.",0.65),
  N("Parfait. Fin de la leçon 2. Demain, la leçon 3 : Noël et les fêtes !"),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:3, hanzi:"圣诞晚会", title:"Noël et les fêtes", desc:"圣诞节 · 新年 · 晚会 · 参加 · 送",
    build(){ return [
N("Bienvenue dans la leçon 3. Aujourd'hui : les fêtes, les soirées, et offrir des cadeaux. Révision. Dites : je voudrais un gâteau."),
  TH(),
  C("我想要一个蛋糕。","Wǒ xiǎngyào yí ge dàngāo.","Je voudrais un gâteau.",0.65),
  N("Demandez : c'est quand, ton anniversaire ?"),
  TH(),
  C("你的生日是几月几号？","Nǐ de shēngrì shì jǐ yuè jǐ hào?","C'est quand, ton anniversaire ?",0.65), HOLD(),

  // ---------- Dialogue cible ----------
  N("Écoutez la conversation d'aujourd'hui."),
  C("圣诞节你想送爸爸什么礼物？","Shèngdànjié nǐ xiǎng sòng bàba shénme lǐwù?","Pour Noël, tu veux offrir quoi à ton papa ?",0.4),
  P(2,"…"),
  C("我想送他一个礼物。你参加圣诞晚会吗？","Wǒ xiǎng sòng tā yí ge lǐwù. Nǐ cānjiā Shèngdàn wǎnhuì ma?","Je veux lui offrir un cadeau. Tu vas à la fête de Noël ?",0.4),
  P(2,"…"),
  C("参加！新年晚会我也参加。","Cānjiā! Xīnnián wǎnhuì wǒ yě cānjiā.","J'y vais ! La fête du Nouvel An aussi, j'y vais.",0.4),
  N("À la fin de cette leçon, cette conversation sera à vous."),

  // ---------- 圣诞节 / 新年 ----------
  N("« Noël » se dit [[圣诞节|Shèngdàn Jié]]. Écoutez et répétez."),
  ...teach("圣诞节","Shèngdàn Jié","Noël"),
  N("« Le Nouvel An » se dit [[新年|xīnnián]]."),
  ...teach("新年","xīnnián","le Nouvel An"),
  ...drill("Dites : Noël.","圣诞节","Shèngdàn Jié","Noël"),

  // ---------- 晚会 / 参加 ----------
  N("« Une soirée », « une fête », se dit [[晚会|wǎnhuì]]."),
  ...teach("晚会","wǎnhuì","une soirée, une fête"),
  N("« Participer », « assister à », se dit [[参加|cānjiā]]. Écoutez : la fête de Noël."),
  ...teach("圣诞晚会","Shèngdàn wǎnhuì","la fête de Noël"),
  ...teach("参加","cānjiā","participer, assister à"),
  N("Demandez : tu vas à la fête de Noël ? Littéralement « tu participes la fête de Noël ? »"),
  TH(),
  C("你参加圣诞晚会吗？","Nǐ cānjiā Shèngdàn wǎnhuì ma?","Tu vas à la fête de Noël ?",0.6), HOLD(),
  N("Répondez : j'y vais ! Simplement le verbe seul."),
  TH(),
  C("参加！","Cānjiā!","J'y vais !",0.65), HOLD(),

  // ---------- 送 ----------
  N("« Offrir », « donner un cadeau à quelqu'un », se dit [[送|sòng]]. La structure est : sujet + [[送|sòng]] + personne + objet. Écoutez : j'offre un cadeau à papa."),
  ...teach("我送爸爸一个礼物。","Wǒ sòng bàba yí ge lǐwù.","J'offre un cadeau à papa."),
  N("Demandez : pour Noël, tu veux offrir quoi à ton papa ?"),
  TH(),
  C("圣诞节你想送爸爸什么礼物？","Shèngdànjié nǐ xiǎng sòng bàba shénme lǐwù?","Pour Noël, tu veux offrir quoi à ton papa ?",0.55), HOLD(),
  ...drill("Répondez : je veux lui offrir un cadeau.","我想送他一个礼物。","Wǒ xiǎng sòng tā yí ge lǐwù.","Je veux lui offrir un cadeau."),
  ...drill("Dites : pour le Nouvel An, je veux offrir un gâteau à maman.","新年我想送妈妈一个蛋糕。","Xīnnián wǒ xiǎng sòng māma yí ge dàngāo.","Pour le Nouvel An, je veux offrir un gâteau à maman."),

  // ---------- Mini-conversation ----------
  N("Mini-conversation. On vous demande :"),
  C("圣诞节你想送爸爸什么礼物？","Shèngdànjié nǐ xiǎng sòng bàba shénme lǐwù?","Pour Noël, tu veux offrir quoi à ton papa ?",0.65),
  N("Répondez : je veux lui offrir un cadeau."),
  TH(),
  C("我想送他一个礼物。","Wǒ xiǎng sòng tā yí ge lǐwù.","Je veux lui offrir un cadeau.",0.6),
  C("你参加圣诞晚会吗？","Nǐ cānjiā Shèngdàn wǎnhuì ma?","Tu vas à la fête de Noël ?",0.65),
  N("Répondez : j'y vais ! Et la fête du Nouvel An aussi, j'y vais."),
  TH(),
  C("参加！新年晚会我也参加。","Cānjiā! Xīnnián wǎnhuì wǒ yě cānjiā.","J'y vais ! La fête du Nouvel An aussi, j'y vais.",0.55),
  C("参加！新年晚会我也参加。","Cānjiā! Xīnnián wǎnhuì wǒ yě cānjiā.","J'y vais ! La fête du Nouvel An aussi, j'y vais.",0.6), HOLD(),

  // ---------- Révision finale ----------
  N("Révision finale. Dites : Noël."),
  TH(),
  C("圣诞节","Shèngdàn Jié","Noël",0.65),
  N("Le Nouvel An."),
  TH(),
  C("新年","xīnnián","le Nouvel An",0.65),
  N("Tu vas à la fête de Noël ?"),
  TH(),
  C("你参加圣诞晚会吗？","Nǐ cānjiā Shèngdàn wǎnhuì ma?","Tu vas à la fête de Noël ?",0.65),
  N("J'offre un cadeau à papa."),
  TH(),
  C("我送爸爸一个礼物。","Wǒ sòng bàba yí ge lǐwù.","J'offre un cadeau à papa.",0.65),
  N("Excellent ! Fin de la leçon 3. Demain, la leçon 4 : un mariage !"),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:4, hanzi:"参加婚礼", title:"Un mariage", desc:"结婚 · 婚礼 · 红包 · 什么时候",
    build(){ return [
N("Bienvenue dans la leçon 4. Aujourd'hui : parler d'un mariage. Révision. Dites : j'offre un cadeau à papa."),
  TH(),
  C("我送爸爸一个礼物。","Wǒ sòng bàba yí ge lǐwù.","J'offre un cadeau à papa.",0.65),
  N("Demandez : tu vas à la fête de Noël ?"),
  TH(),
  C("你参加圣诞晚会吗？","Nǐ cānjiā Shèngdàn wǎnhuì ma?","Tu vas à la fête de Noël ?",0.65), HOLD(),

  // ---------- Dialogue cible ----------
  N("Écoutez la conversation d'aujourd'hui, une amie vous annonce une nouvelle."),
  C("你知道吗？我朋友要结婚了！","Nǐ zhīdào ma? Wǒ péngyou yào jié hūn le!","Tu sais quoi ? Mon ami va se marier !",0.4),
  P(2,"…"),
  C("真的吗？婚礼是什么时候？","Zhēn de ma? Hūnlǐ shì shénme shíhou?","Vraiment ? Le mariage, c'est quand ?",0.4),
  P(2,"…"),
  C("大后天。你参加吗？","Dàhòutiān. Nǐ cānjiā ma?","Dans trois jours. Tu y vas ?",0.4),
  P(2,"…"),
  C("参加！我要准备一个红包。","Cānjiā! Wǒ yào zhǔnbèi yí ge hóngbāo.","J'y vais ! Je dois préparer une enveloppe rouge.",0.4),
  N("À la fin de cette leçon, cette conversation sera à vous."),

  // ---------- 结婚 / 婚礼 ----------
  N("« Se marier » se dit [[结婚|jié hūn]] — littéralement « nouer le mariage ». Écoutez et répétez."),
  ...teach("结婚","jié hūn","se marier"),
  N("« Le mariage », la cérémonie, se dit [[婚礼|hūnlǐ]]."),
  ...teach("婚礼","hūnlǐ","le mariage (la cérémonie)"),
  N("Annoncez : mon ami va se marier ! On ajoute [[了|le]] à la fin pour un événement qui arrive."),
  TH(),
  C("我朋友要结婚了！","Wǒ péngyou yào jié hūn le!","Mon ami va se marier !",0.6), HOLD(),

  // ---------- 什么时候 (rappel) ----------
  N("Vous connaissez déjà [[时候|shíhou]], le moment. Rappel : « quand » se dit [[什么时候|shénme shíhou]]. Demandez : le mariage, c'est quand ?"),
  TH(),
  C("婚礼是什么时候？","Hūnlǐ shì shénme shíhou?","Le mariage, c'est quand ?",0.6), HOLD(),
  N("Répondez avec ce que vous avez appris hier : dans trois jours."),
  TH(),
  C("大后天。","Dàhòutiān.","Dans trois jours.",0.65), HOLD(),

  // ---------- 红包 ----------
  N("Nouveau mot de culture chinoise : [[红包|hóngbāo]], « l'enveloppe rouge », une enveloppe contenant de l'argent, offerte pour un mariage, une naissance, ou le Nouvel An."),
  ...teach("红包","hóngbāo","l'enveloppe rouge (argent porte-bonheur)"),
  N("« Préparer » se dit [[准备|zhǔnbèi]] — vous l'avez peut-être déjà croisé. Écoutez : je dois préparer une enveloppe rouge."),
  ...teach("我要准备一个红包。","Wǒ yào zhǔnbèi yí ge hóngbāo.","Je dois préparer une enveloppe rouge."),
  ...drill("Dites : tu vas au mariage ?","你参加婚礼吗？","Nǐ cānjiā hūnlǐ ma?","Tu vas au mariage ?"),
  ...drill("Répondez : j'y vais ! Je dois préparer une enveloppe rouge.","参加！我要准备一个红包。","Cānjiā! Wǒ yào zhǔnbèi yí ge hóngbāo.","J'y vais ! Je dois préparer une enveloppe rouge."),

  // ---------- Mini-conversation ----------
  N("Mini-conversation. Une amie vous annonce :"),
  C("你知道吗？我朋友要结婚了！","Nǐ zhīdào ma? Wǒ péngyou yào jié hūn le!","Tu sais quoi ? Mon ami va se marier !",0.65),
  N("Réagissez : vraiment ? Puis demandez : le mariage, c'est quand ?"),
  TH(),
  C("真的吗？婚礼是什么时候？","Zhēn de ma? Hūnlǐ shì shénme shíhou?","Vraiment ? Le mariage, c'est quand ?",0.6),
  C("大后天。你参加吗？","Dàhòutiān. Nǐ cānjiā ma?","Dans trois jours. Tu y vas ?",0.65),
  N("Répondez : j'y vais ! Je dois préparer une enveloppe rouge."),
  TH(),
  C("参加！我要准备一个红包。","Cānjiā! Wǒ yào zhǔnbèi yí ge hóngbāo.","J'y vais ! Je dois préparer une enveloppe rouge.",0.55),
  C("参加！我要准备一个红包。","Cānjiā! Wǒ yào zhǔnbèi yí ge hóngbāo.","J'y vais ! Je dois préparer une enveloppe rouge.",0.6), HOLD(),

  // ---------- Révision finale ----------
  N("Révision finale. Dites : se marier."),
  TH(),
  C("结婚","jié hūn","se marier",0.65),
  N("Le mariage, c'est quand ?"),
  TH(),
  C("婚礼是什么时候？","Hūnlǐ shì shénme shíhou?","Le mariage, c'est quand ?",0.65),
  N("Une enveloppe rouge."),
  TH(),
  C("红包","hóngbāo","une enveloppe rouge",0.65),
  N("Je dois préparer une enveloppe rouge."),
  TH(),
  C("我要准备一个红包。","Wǒ yào zhǔnbèi yí ge hóngbāo.","Je dois préparer une enveloppe rouge.",0.65),
  N("Excellent ! Fin de la leçon 4. Demain, la leçon 5 : organiser la semaine prochaine !"),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:5, hanzi:"下周的安排", title:"Le programme de la semaine", desc:"安排 · 下周 · 这周 · 上周",
    build(){ return [
N("Bienvenue dans la leçon 5. Aujourd'hui : parler de son emploi du temps pour la semaine. Révision. Demandez : le mariage, c'est quand ?"),
  TH(),
  C("婚礼是什么时候？","Hūnlǐ shì shénme shíhou?","Le mariage, c'est quand ?",0.65),
  N("Dites : dans trois jours."),
  TH(),
  C("大后天。","Dàhòutiān.","Dans trois jours.",0.65), HOLD(),

  // ---------- Dialogue cible ----------
  N("Écoutez la conversation d'aujourd'hui."),
  C("你下周有什么安排？","Nǐ xiàzhōu yǒu shénme ānpái?","Qu'est-ce que tu as prévu la semaine prochaine ?",0.4),
  P(2,"…"),
  C("下周一我上课，下周三我去医院，星期六我参加一个婚礼。","Xiàzhōuyī wǒ shàngkè, xiàzhōusān wǒ qù yīyuàn, Xīngqīliù wǒ cānjiā yí ge hūnlǐ.","Lundi j'ai cours, mercredi je vais à l'hôpital, samedi je vais à un mariage.",0.4),
  P(2,"…"),
  C("这周你忙不忙？","Zhè zhōu nǐ máng bu máng?","Tu es occupé cette semaine ?",0.4),
  P(2,"…"),
  C("很忙！上周比较轻松。","Hěn máng! Shàngzhōu bǐjiào qīngsōng.","Très occupé ! La semaine dernière était plus tranquille.",0.4),
  N("À la fin de cette leçon, cette conversation sera à vous."),

  // ---------- 周 / 下周 / 这周 / 上周 ----------
  N("[[周|zhōu]] est un synonyme courant de [[星期|xīngqī]] pour « semaine ». « La semaine prochaine » se dit [[下周|xiàzhōu]] — comme [[下课|xiàkè]], [[下|xià]] veut dire « suivant »."),
  ...teach("下周","xiàzhōu","la semaine prochaine"),
  N("« Cette semaine » se dit [[这周|zhè zhōu]]."),
  ...teach("这周","zhè zhōu","cette semaine"),
  N("« La semaine dernière » se dit [[上周|shàngzhōu]]."),
  ...teach("上周","shàngzhōu","la semaine dernière"),
  ...drill("Dites : la semaine prochaine.","下周","xiàzhōu","la semaine prochaine"),

  // ---------- 安排 ----------
  N("« Le programme », « prévoir », « organiser », se dit [[安排|ānpái]]. Demandez : qu'est-ce que tu as prévu la semaine prochaine ?"),
  ...teach("安排","ānpái","le programme, prévoir"),
  TH(),
  C("你下周有什么安排？","Nǐ xiàzhōu yǒu shénme ānpái?","Qu'est-ce que tu as prévu la semaine prochaine ?",0.6), HOLD(),

  // ---------- 星期 + 下周 combinés ----------
  N("Pour préciser un jour de la semaine prochaine, on place [[下周|xiàzhōu]] devant le jour : « lundi prochain » se dit [[下周一|xiàzhōuyī]]."),
  ...teach("下周一","xiàzhōuyī","lundi prochain"),
  N("Répondez à la question précédente : lundi j'ai cours, mercredi je vais à l'hôpital, samedi je vais à un mariage."),
  TH(),
  C("下周一我上课，下周三我去医院，星期六我参加一个婚礼。","Xiàzhōuyī wǒ shàngkè, xiàzhōusān wǒ qù yīyuàn, Xīngqīliù wǒ cānjiā yí ge hūnlǐ.","Lundi j'ai cours, mercredi je vais à l'hôpital, samedi un mariage.",0.55),
  C("下周一我上课，下周三我去医院，星期六我参加一个婚礼。","Xiàzhōuyī wǒ shàngkè, xiàzhōusān wǒ qù yīyuàn, Xīngqīliù wǒ cānjiā yí ge hūnlǐ.","Lundi j'ai cours, mercredi je vais à l'hôpital, samedi un mariage.",0.6), HOLD(),

  // ---------- 忙 / 轻松 ----------
  N("« Occupé » se dit [[忙|máng]], vous le connaissez peut-être déjà. « Détendu », « tranquille », se dit [[轻松|qīngsōng]]. Demandez : tu es occupé cette semaine ?"),
  ...teach("这周你忙不忙？","Zhè zhōu nǐ máng bu máng?","Tu es occupé cette semaine ?"),
  ...teach("轻松","qīngsōng","détendu, tranquille"),
  ...drill("Répondez : très occupé ! La semaine dernière était plus tranquille.","很忙！上周比较轻松。","Hěn máng! Shàngzhōu bǐjiào qīngsōng.","Très occupé ! La semaine dernière était plus tranquille."),

  // ---------- Mini-conversation ----------
  N("Mini-conversation. On vous demande :"),
  C("你下周有什么安排？","Nǐ xiàzhōu yǒu shénme ānpái?","Qu'est-ce que tu as prévu la semaine prochaine ?",0.65),
  N("Répondez avec votre propre programme, ou avec l'exemple appris."),
  TH(),
  C("下周一我上课，下周三我去医院，星期六我参加一个婚礼。","Xiàzhōuyī wǒ shàngkè, xiàzhōusān wǒ qù yīyuàn, Xīngqīliù wǒ cānjiā yí ge hūnlǐ.","Lundi j'ai cours, mercredi je vais à l'hôpital, samedi un mariage.",0.6),
  C("这周你忙不忙？","Zhè zhōu nǐ máng bu máng?","Tu es occupé cette semaine ?",0.65),
  N("Répondez : très occupé, la semaine dernière était plus tranquille."),
  TH(),
  C("很忙！上周比较轻松。","Hěn máng! Shàngzhōu bǐjiào qīngsōng.","Très occupé ! La semaine dernière était plus tranquille.",0.6), HOLD(),

  // ---------- Révision finale ----------
  N("Révision finale. Dites : la semaine prochaine."),
  TH(),
  C("下周","xiàzhōu","la semaine prochaine",0.65),
  N("Le programme, qu'est-ce que tu as prévu ?"),
  TH(),
  C("你下周有什么安排？","Nǐ xiàzhōu yǒu shénme ānpái?","Qu'est-ce que tu as prévu la semaine prochaine ?",0.65),
  N("Lundi prochain."),
  TH(),
  C("下周一","xiàzhōuyī","lundi prochain",0.65),
  N("Tu es occupé cette semaine ?"),
  TH(),
  C("这周你忙不忙？","Zhè zhōu nǐ máng bu máng?","Tu es occupé cette semaine ?",0.65),
  N("Formidable ! Vous savez maintenant construire et raconter tout un emploi du temps. Fin de la leçon 5. Demain, la grande révision !"),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  { num:6, star:true, hanzi:"总复习", title:"Révision totale", desc:"Uniquement des questions — leçons 1 à 5",
    build(){ return [
N("Bienvenue dans la grande révision de ce chapitre. Ici, pas de nouveau vocabulaire : uniquement des questions sur tout ce que vous avez appris dans les leçons 1 à 5. Répondez à voix haute avant chaque correction. C'est parti."),

  N("Leçon 1. Dites : avant-hier."),
  TH(),
  C("前天","qiántiān","avant-hier",0.65),
  N("Après-demain."),
  TH(),
  C("后天","hòutiān","après-demain",0.65),
  N("Il y a trois jours."),
  TH(),
  C("大前天","dàqiántiān","il y a trois jours",0.65),
  N("Dans trois jours."),
  TH(),
  C("大后天","dàhòutiān","dans trois jours",0.65),
  N("Il y a deux ans."),
  TH(),
  C("前年","qiánnián","il y a deux ans",0.65),
  N("Dans deux ans."),
  TH(),
  C("后年","hòunián","dans deux ans",0.65),

  N("Leçon 2, les anniversaires. Demandez : c'est quand, ton anniversaire ?"),
  TH(),
  C("你的生日是几月几号？","Nǐ de shēngrì shì jǐ yuè jǐ hào?","C'est quand, ton anniversaire ?",0.65),
  N("Un cadeau."),
  TH(),
  C("礼物","lǐwù","un cadeau",0.65),
  N("Je voudrais un gâteau."),
  TH(),
  C("我想要一个蛋糕。","Wǒ xiǎngyào yí ge dàngāo.","Je voudrais un gâteau.",0.65),

  N("Leçon 3, les fêtes. Dites : Noël."),
  TH(),
  C("圣诞节","Shèngdàn Jié","Noël",0.65),
  N("Le Nouvel An."),
  TH(),
  C("新年","xīnnián","le Nouvel An",0.65),
  N("Demandez : tu vas à la fête de Noël ?"),
  TH(),
  C("你参加圣诞晚会吗？","Nǐ cānjiā Shèngdàn wǎnhuì ma?","Tu vas à la fête de Noël ?",0.65),
  N("J'offre un cadeau à papa."),
  TH(),
  C("我送爸爸一个礼物。","Wǒ sòng bàba yí ge lǐwù.","J'offre un cadeau à papa.",0.65),

  N("Leçon 4, un mariage. Dites : se marier."),
  TH(),
  C("结婚","jié hūn","se marier",0.65),
  N("Demandez : le mariage, c'est quand ?"),
  TH(),
  C("婚礼是什么时候？","Hūnlǐ shì shénme shíhou?","Le mariage, c'est quand ?",0.65),
  N("Une enveloppe rouge."),
  TH(),
  C("红包","hóngbāo","une enveloppe rouge",0.65),

  N("Leçon 5, la semaine. Dites : la semaine prochaine."),
  TH(),
  C("下周","xiàzhōu","la semaine prochaine",0.65),
  N("Cette semaine."),
  TH(),
  C("这周","zhè zhōu","cette semaine",0.65),
  N("La semaine dernière."),
  TH(),
  C("上周","shàngzhōu","la semaine dernière",0.65),
  N("Demandez : qu'est-ce que tu as prévu la semaine prochaine ?"),
  TH(),
  C("你下周有什么安排？","Nǐ xiàzhōu yǒu shénme ānpái?","Qu'est-ce que tu as prévu la semaine prochaine ?",0.65),
  N("Tu es occupé cette semaine ?"),
  TH(),
  C("这周你忙不忙？","Zhè zhōu nǐ máng bu máng?","Tu es occupé cette semaine ?",0.65),

  N("Félicitations ! Vous venez de réviser les cinq leçons de ce chapitre. Vous savez maintenant parler des dates dans le temps, des anniversaires, des fêtes, d'un mariage, et raconter tout un emploi du temps. Refaites cette révision régulièrement. À bientôt !"),
  C("再见！","Zàijiàn!","Au revoir !",0.65),
    ]; } },

  ]
});
