/* ============================================================
   Chapitre Bonus 5 · 句子结构 — Construire des phrases et poser
   des questions avec les structures essentielles HSK1–HSK2.
   ============================================================ */
function bonus5Pinyin(zh){
  return (typeof BONUS5_PINYIN !== 'undefined' && BONUS5_PINYIN[zh]) || '';
}
function B5C(zh, fr, rate, origin){
  return C(zh, bonus5Pinyin(zh), fr, rate || .66, origin || 'direct');
}
function b5teach(zh, fr){
  return [B5C(zh, fr, .58, 'teach'), B5C(zh, fr, .7, 'teach'), HOLD('Répète à voix haute, puis ▶')];
}
function b5drill(prompt, zh, fr){
  return [N(prompt), TH(), B5C(zh, fr, .68, 'drill'), HOLD('Répète le modèle, puis ▶')];
}
function b5item(prompt, zh, fr){
  return b5drill(prompt, zh, fr);
}

registerChapter({
  group: "bonus",
  id: "05-syntaxe",
  badge: "★5",
  star: true,
  hanzi: "句子结构",
  title: "Bonus 5 · Construire ses phrases",
  desc: "SVO · ordre temps–lieu · 的/得 · questions · négation · structures HSK1–HSK2 — 18 leçons",
  intro: "Dix-huit épisodes progressifs pour comprendre l'ordre des mots chinois et produire soi-même des affirmations, des négations et des questions. Le vocabulaire reste principalement au niveau HSK1, avec les mots HSK2 indispensables. Chaque règle est suivie de transformations, de réponses corrigées et de dialogues.",
  lessons: [

  {num:1,hanzi:"四种基本句子",title:"Les quatre phrases de base",desc:"S + V + O · S + 是 + N · S + Adj · S + 有 + O",build(){return[
  N("Leçon 1. Une phrase chinoise n'utilise pas toujours un verbe comme « être ». Commençons par quatre modèles fondamentaux."),
  N("Modèle 1 : sujet + verbe + objet, ou S V O. Le sujet fait l'action ; l'objet reçoit l'action."),
  ...b5teach("我喝茶。","Je bois du thé."),
  ...b5teach("他学习汉语。","Il étudie le chinois."),
  ...b5drill("Remplacez le sujet et l'objet : elle mange du riz.","她吃米饭。","Elle mange du riz."),
  N("Modèle 2 : sujet + 是 + nom. 是 relie le sujet à une identité, une profession ou une catégorie."),
  ...b5teach("我是学生。","Je suis étudiant."),
  ...b5drill("Dites : il est professeur.","他是老师。","Il est professeur."),
  N("Modèle 3 : sujet + adjectif. En chinois, l'adjectif peut être le prédicat. On ne met généralement pas 是 devant lui."),
  ...b5teach("今天天气很好。","Aujourd'hui, il fait très beau."),
  ...b5teach("这个菜很热。","Ce plat est chaud."),
  N("Erreur à éviter : n'insérez pas le verbe « être » devant l'adjectif. Pour une description simple, placez directement 很热 après le sujet."),
  ...b5drill("Décrivez la chambre : elle est grande.","房间很大。","La chambre est grande."),
  N("Modèle 4 : sujet + 有 + objet. 有 exprime la possession."),
  ...b5teach("我有一本书。","J'ai un livre."),
  ...b5drill("Dites : elle a un ami chinois.","她有一个中国朋友。","Elle a un ami chinois."),
  N("Test. Identifiez le modèle puis produisez la phrase. Première phrase : mon père boit du café."),
  ...b5drill("Utilisez S V O.","我爸爸喝咖啡。","Mon père boit du café."),
  ...b5drill("Deuxième phrase : ma mère est médecin.","我妈妈是医生。","Ma mère est médecin."),
  ...b5drill("Troisième phrase : le café est chaud.","咖啡很热。","Le café est chaud."),
  ...b5drill("Quatrième phrase : nous avons deux chats.","我们有两只猫。","Nous avons deux chats."),
  N("Bilan : 是 devant un nom, mais pas devant un adjectif simple. Avec une action, gardez l'ordre sujet, verbe, objet."),
  ];}},

  {num:2,hanzi:"好看的衣服",title:"L’objet décrit avec 的",desc:"S + V + Adj + 的 + O · possesseur + 的 + nom",build(){return[
  N("Leçon 2. Voici la consigne qui vous intéresse : construire une phrase avec sujet + verbe + adjectif + 的 + objet."),
  B5C("请用“主语、动词、形容词、的、宾语”的句型造句。","Construisez une phrase avec le modèle : sujet, verbe, adjectif, de, objet.",.58),
  N("Dans ce modèle, adjectif + 的 + nom forme un seul groupe nominal. Dans 我喜欢好看的衣服, l'objet entier est 好看的衣服 : de beaux vêtements."),
  ...b5teach("我喜欢好看的衣服。","J'aime les beaux vêtements."),
  N("Découpage : 我, sujet ; 喜欢, verbe ; 好看的衣服, objet. À l'intérieur de l'objet : 好看 + 的 + 衣服."),
  ...b5teach("他买便宜的水果。","Il achète des fruits bon marché."),
  ...b5drill("Changez l'adjectif : elle aime les livres intéressants.","她喜欢有意思的书。","Elle aime les livres intéressants."),
  ...b5drill("Changez le verbe : j'achète une grande tasse.","我买一个大杯子。","J'achète une grande tasse."),
  N("Avec un adjectif court très courant, 的 peut parfois disparaître, surtout dans une expression fixe : 大杯子, grande tasse. Avec une description plus développée, gardez 的."),
  ...b5teach("我想买一件很漂亮的衣服。","Je voudrais acheter un très beau vêtement."),
  N("Le même 的 relie un possesseur au nom."),
  ...b5teach("这是我的书。","C'est mon livre."),
  ...b5drill("Dites : j'aime le thé de mon professeur.","我喜欢老师的茶。","J'aime le thé de mon professeur."),
  N("Une petite phrase verbale peut aussi décrire le nom. 我妈妈做的饭 signifie le repas que ma mère a préparé."),
  ...b5teach("我喜欢我妈妈做的饭。","J'aime les repas préparés par ma mère."),
  ...b5drill("Dites : je veux acheter le livre que tu aimes.","我想买你喜欢的书。","Je veux acheter le livre que tu aimes."),
  N("Question : quel type de vêtements aimes-tu ?"),
  B5C("你喜欢什么样的衣服？","Quel genre de vêtements aimes-tu ?",.64),
  ...b5drill("Répondez avec adjectif + 的 + nom : j'aime les vêtements simples.","我喜欢简单的衣服。","J'aime les vêtements simples."),
  ...b5drill("Posez une nouvelle question : quel genre de livres achètes-tu ?","你买什么样的书？","Quel genre de livres achètes-tu ?"),
  N("Bilan : le schéma S V Adj 的 O est bien une phrase S V O ; Adj 的 O constitue l'objet décrit."),
  ];}},

  {num:3,hanzi:"时间地点动作",title:"Placer le temps et le lieu",desc:"S + temps + lieu + V + O · 去 + lieu + V",build(){return[
  N("Leçon 3. Ordre très utile : sujet + moment + lieu + verbe + objet. Le temps vient avant le lieu ; le lieu où se déroule l'action vient avant le verbe."),
  ...b5teach("我今天在家学习汉语。","Aujourd'hui, j'étudie le chinois à la maison."),
  N("Découpage : 我, qui ; 今天, quand ; 在家, où ; 学习汉语, quelle action."),
  ...b5teach("他明天在学校看书。","Demain, il lira à l'école."),
  ...b5drill("Changez le moment : ce soir, je mange à la maison.","我今天晚上在家吃饭。","Ce soir, je mange à la maison."),
  ...b5drill("Changez le lieu : demain, elle étudie à la bibliothèque.","她明天在图书馆学习。","Demain, elle étudie à la bibliothèque."),
  N("Le groupe de temps peut aussi ouvrir la phrase. Le sens reste le même."),
  ...b5teach("明天我在学校上课。","Demain, j'ai cours à l'école."),
  N("Attention : avec 去 ou 来, le lieu est une destination et suit le verbe de déplacement."),
  ...b5teach("我明天去学校。","Demain, je vais à l'école."),
  ...b5teach("我明天去学校学习汉语。","Demain, je vais à l'école étudier le chinois."),
  N("Comparez : 我在学校学习, j'étudie à l'école ; 我去学校学习, je vais à l'école pour étudier."),
  ...b5drill("Dites : cet après-midi, je vais au magasin acheter du thé.","我今天下午去商店买茶。","Cet après-midi, je vais au magasin acheter du thé."),
  ...b5drill("Dites : ce soir, nous regardons un film chez moi.","我们今天晚上在我家看电影。","Ce soir, nous regardons un film chez moi."),
  N("Question sur le temps : remplacez le moment par 什么时候 sans déplacer le reste."),
  ...b5teach("你什么时候在家学习？","Quand étudies-tu à la maison ?"),
  N("Question sur le lieu : remplacez le lieu par 在哪儿."),
  ...b5teach("你今天在哪儿学习？","Où étudies-tu aujourd'hui ?"),
  ...b5drill("Posez la question : où manges-tu ce soir ?","你今天晚上在哪儿吃饭？","Où manges-tu ce soir ?"),
  ...b5drill("Posez la question : quand vas-tu à Pékin ?","你什么时候去北京？","Quand vas-tu à Pékin ?"),
  N("Bilan : quand, puis où, puis action. Mais la destination de 去 ou 来 se place après le verbe de déplacement."),
  ];}},

  {num:4,hanzi:"在和有",title:"Position ou existence ?",desc:"objet + 在 + lieu · lieu + 有 + objet",build(){return[
  N("Leçon 4. Deux modèles se ressemblent en français mais organisent la scène différemment."),
  N("Objet connu + 在 + lieu répond à « où est cet objet ? »."),
  ...b5teach("书在桌子上。","Le livre est sur la table."),
  ...b5teach("我的朋友在学校。","Mon ami est à l'école."),
  N("Lieu + 有 + objet introduit ce qui existe dans ce lieu."),
  ...b5teach("桌子上有一本书。","Il y a un livre sur la table."),
  ...b5teach("学校里有很多学生。","Il y a beaucoup d'élèves dans l'école."),
  N("Comparez. 书在哪儿？ demande la position d'un livre connu. 桌子上有什么？ demande ce qu'il y a sur la table."),
  B5C("书在哪儿？","Où est le livre ?",.68),
  B5C("桌子上有什么？","Qu'y a-t-il sur la table ?",.68),
  ...b5drill("Répondez à la première question : le livre est sur la chaise.","书在椅子上。","Le livre est sur la chaise."),
  ...b5drill("Répondez à la seconde : il y a un téléphone sur la table.","桌子上有一个手机。","Il y a un téléphone sur la table."),
  N("Avec une personne, la même opposition fonctionne."),
  B5C("老师在哪儿？","Où est le professeur ?",.68),
  B5C("教室里有谁？","Qui y a-t-il dans la salle de classe ?",.68),
  ...b5drill("Répondez : le professeur est dans la salle de classe.","老师在教室里。","Le professeur est dans la salle de classe."),
  ...b5drill("Répondez en commençant par le lieu : dans la salle de classe, il y a le professeur Wang.","教室里有王老师。","Dans la salle de classe, il y a le professeur Wang."),
  N("Transformez la position en existence. Point de départ : le chat est sous la chaise."),
  B5C("猫在椅子下面。","Le chat est sous la chaise.",.68),
  ...b5drill("Commencez maintenant par le lieu.","椅子下面有一只猫。","Il y a un chat sous la chaise."),
  N("Bilan : objet connu d'abord avec 在 ; lieu d'abord avec 有 pour présenter quelque chose."),
  ];}},

  {num:5,hanzi:"不没别",title:"Construire une négation",desc:"不 + présent/habitude · 没 + passé · 没有 · 别 + V",build(){return[
  N("Leçon 5. 不 nie une habitude, un état ou une intention. 没 nie une action accomplie. 没有 nie aussi la possession ou l'existence."),
  ...b5teach("我不喝咖啡。","Je ne bois pas de café."),
  ...b5teach("他今天不忙。","Il n'est pas occupé aujourd'hui."),
  ...b5drill("Niez une intention : demain, je ne vais pas à Pékin.","我明天不去北京。","Demain, je ne vais pas à Pékin."),
  N("Pour une action passée non réalisée, mettez 没 devant le verbe et n'ajoutez pas 了."),
  ...b5teach("我昨天没喝咖啡。","Hier, je n'ai pas bu de café."),
  ...b5teach("他还没吃饭。","Il n'a pas encore mangé."),
  ...b5drill("Dites : hier, je n'ai pas regardé la télévision.","我昨天没看电视。","Hier, je n'ai pas regardé la télévision."),
  N("Pour « ne pas avoir », utilisez 没有."),
  ...b5teach("我没有车。","Je n'ai pas de voiture."),
  ...b5teach("杯子里没有水。","Il n'y a pas d'eau dans le verre."),
  ...b5drill("Dites : l'école n'a pas de restaurant.","学校里没有饭店。","Il n'y a pas de restaurant dans l'école."),
  N("Pour une interdiction ou un conseil négatif, utilisez 别 + verbe."),
  ...b5teach("别说话。","Ne parle pas."),
  ...b5drill("Dites : ne bois pas cette tasse de café.","别喝这杯咖啡。","Ne bois pas cette tasse de café."),
  N("Choisissez 不 ou 没. Première situation : aujourd'hui, il pleut, donc je ne vais pas au parc."),
  ...b5drill("C'est une décision présente.","我今天不去公园。","Aujourd'hui, je ne vais pas au parc."),
  ...b5drill("Deuxième situation : hier, je ne suis pas allé au parc.","我昨天没去公园。","Hier, je ne suis pas allé au parc."),
  N("Bilan : 不 pour ce qui n'est pas ou ne se fera pas ; 没 pour ce qui ne s'est pas fait ; 没有 pour ne pas avoir ; 别 pour interdire."),
  ];}},

  {num:6,hanzi:"吗和呢",title:"Les questions avec 吗 et 呢",desc:"affirmation + 吗 · réponse courte · nom + 呢",build(){return[
  N("Leçon 6. Pour transformer une affirmation en question oui/non, gardez exactement le même ordre et ajoutez 吗 à la fin."),
  B5C("你是学生。","Tu es étudiant.",.7),
  ...b5teach("你是学生吗？","Es-tu étudiant ?"),
  B5C("他喝茶。","Il boit du thé.",.7),
  ...b5teach("他喝茶吗？","Est-ce qu'il boit du thé ?"),
  ...b5drill("Transformez en question : elle est chinoise.","她是中国人吗？","Est-elle chinoise ?"),
  ...b5drill("Transformez en question : tu aimes ce livre.","你喜欢这本书吗？","Aimes-tu ce livre ?"),
  N("Réponse positive : répétez le verbe principal. Réponse négative : 不 + verbe, ou 不是 avec 是."),
  B5C("你是老师吗？","Es-tu professeur ?",.68),
  B5C("是，我是老师。","Oui, je suis professeur.",.68),
  B5C("不是，我是学生。","Non, je suis étudiant.",.68),
  B5C("你喝咖啡吗？","Bois-tu du café ?",.68),
  B5C("喝，我喝咖啡。","Oui, j'en bois.",.68),
  B5C("不喝，我喝茶。","Non, je n'en bois pas ; je bois du thé.",.68),
  N("呢 permet de retourner une question déjà comprise : et toi ? et lui ?"),
  ...b5teach("我很好，你呢？","Je vais bien, et toi ?"),
  ...b5drill("Demandez : je bois du thé, et toi ?","我喝茶，你呢？","Je bois du thé, et toi ?"),
  N("呢 peut aussi demander où se trouve quelque chose dans un contexte clair."),
  ...b5teach("我的手机呢？","Et mon téléphone ? Où est mon téléphone ?"),
  N("Dialogue. Répondez, puis retournez la question."),
  B5C("你喜欢中国菜吗？","Aimes-tu la cuisine chinoise ?",.66),
  ...b5drill("Dites : oui, j'aime beaucoup la cuisine chinoise, et toi ?","喜欢，我很喜欢中国菜。你呢？","Oui, j'aime beaucoup la cuisine chinoise. Et toi ?"),
  N("Bilan : 吗 transforme toute l'affirmation en question ; 呢 reprend une question déjà installée dans la conversation."),
  ];}},

  {num:7,hanzi:"正反问句",title:"Les questions A-not-A",desc:"是不是 · 有没有 · V 不 V · V 没 V",build(){return[
  N("Leçon 7. Une autre question oui/non répète l'élément positif et négatif. N'ajoutez pas 吗 à cette structure."),
  ...b5teach("你是不是老师？","Es-tu professeur ?"),
  ...b5teach("你去不去学校？","Vas-tu à l'école ?"),
  ...b5teach("这个菜好不好吃？","Est-ce que ce plat est bon ?"),
  ...b5drill("Demandez : boit-il du thé ?","他喝不喝茶？","Est-ce qu'il boit du thé ?"),
  ...b5drill("Demandez : êtes-vous occupé aujourd'hui ?","你今天忙不忙？","Es-tu occupé aujourd'hui ?"),
  N("Avec 有, la forme est 有没有."),
  ...b5teach("你有没有中国朋友？","As-tu des amis chinois ?"),
  ...b5drill("Demandez : y a-t-il de l'eau dans le verre ?","杯子里有没有水？","Y a-t-il de l'eau dans le verre ?"),
  N("Avec un verbe modal, répétez le modal : 能不能, 会不会, 可不可以."),
  ...b5teach("你能不能帮我？","Peux-tu m'aider ?"),
  ...b5drill("Demandez : sais-tu parler chinois ?","你会不会说汉语？","Sais-tu parler chinois ?"),
  ...b5drill("Demandez poliment : puis-je m'asseoir ici ?","我可不可以坐这儿？","Puis-je m'asseoir ici ?"),
  N("Pour vérifier une action passée, le chinois oral emploie souvent verbe + 没 + verbe, ou …了没有."),
  ...b5teach("你吃没吃饭？","As-tu mangé ?"),
  ...b5teach("你吃饭了没有？","As-tu mangé ?"),
  ...b5drill("Demandez : as-tu vu ce film ?","你看没看这部电影？","As-tu vu ce film ?"),
  N("Choisissez une forme. Vous voulez savoir si votre ami vient demain."),
  ...b5drill("Utilisez V 不 V.","你明天来不来？","Viens-tu demain ?"),
  N("Bilan : 吗 et A-not-A ont le même objectif, mais ne se cumulent pas. Une seule de ces deux formes suffit."),
  ];}},

  {num:8,hanzi:"疑问词的位置",title:"Garder le mot interrogatif à sa place",desc:"谁 · 什么 · 哪个 · 哪儿 · 什么时候 · 怎么",build(){return[
  N("Leçon 8. En chinois, le mot interrogatif reste à la place exacte de l'information inconnue. On ne le déplace pas au début comme en français."),
  B5C("王老师喝茶。","Le professeur Wang boit du thé.",.7),
  N("Pour demander qui boit du thé, remplacez 王老师 par 谁."),
  ...b5teach("谁喝茶？","Qui boit du thé ?"),
  N("Pour demander ce qu'il boit, remplacez 茶 par 什么."),
  ...b5teach("王老师喝什么？","Que boit le professeur Wang ?"),
  B5C("他在学校学习汉语。","Il étudie le chinois à l'école.",.68),
  ...b5drill("Remplacez le lieu : où étudie-t-il le chinois ?","他在哪儿学习汉语？","Où étudie-t-il le chinois ?"),
  ...b5drill("Remplacez l'objet : qu'étudie-t-il à l'école ?","他在学校学习什么？","Qu'étudie-t-il à l'école ?"),
  B5C("她明天坐飞机去北京。","Demain, elle va à Pékin en avion.",.68),
  ...b5drill("Demandez quand elle va à Pékin.","她什么时候去北京？","Quand va-t-elle à Pékin ?"),
  ...b5drill("Demandez comment elle va à Pékin.","她怎么去北京？","Comment va-t-elle à Pékin ?"),
  ...b5drill("Demandez où elle va demain.","她明天去哪儿？","Où va-t-elle demain ?"),
  N("哪 + classificateur + nom demande lequel dans un ensemble."),
  ...b5teach("你喜欢哪本书？","Quel livre aimes-tu ?"),
  ...b5drill("Demandez : quel professeur enseigne le chinois ?","哪位老师教汉语？","Quel professeur enseigne le chinois ?"),
  N("Atelier inverse. Écoutez la réponse et fabriquez la question."),
  B5C("我的朋友买苹果。","Mon ami achète des pommes.",.68),
  ...b5drill("L'inconnue est la personne.","谁买苹果？","Qui achète des pommes ?"),
  ...b5drill("L'inconnue est l'objet.","你的朋友买什么？","Qu'achète ton ami ?"),
  N("Bilan : construisez d'abord la réponse normale, puis remplacez seulement l'information manquante par le mot interrogatif."),
  ];}},

  {num:9,hanzi:"数量和量词",title:"Nombres, classificateurs et choix",desc:"nombre + classificateur + nom · 几 · 多少 · 这/那/哪",build(){return[
  N("Leçon 9. Devant un nom comptable, le chinois place généralement : nombre + classificateur + nom."),
  ...b5teach("一个人","une personne"),
  ...b5teach("两本书","deux livres"),
  ...b5teach("三杯茶","trois tasses de thé"),
  N("Avec 这, 那 et 哪, gardez aussi le classificateur."),
  ...b5teach("这个人","cette personne"),
  ...b5teach("那本书","ce livre-là"),
  ...b5teach("哪杯茶？","quelle tasse de thé ?"),
  ...b5drill("Dites : j'achète deux pommes.","我买两个苹果。","J'achète deux pommes."),
  ...b5drill("Dites : je veux cette tasse de thé.","我要这杯茶。","Je veux cette tasse de thé."),
  N("几 demande un petit nombre attendu. 多少 demande une quantité ouverte ou un prix."),
  ...b5teach("你有几本书？","Combien de livres as-tu ?"),
  ...b5teach("你们学校有多少学生？","Combien d'élèves y a-t-il dans votre école ?"),
  ...b5teach("这本书多少钱？","Combien coûte ce livre ?"),
  ...b5drill("Demandez : combien de personnes y a-t-il dans sa famille ?","他家有几口人？","Combien de personnes y a-t-il dans sa famille ?"),
  ...b5drill("Demandez le prix de cette tasse.","这个杯子多少钱？","Combien coûte cette tasse ?"),
  N("Pour une heure ou une date, 几 reste très courant."),
  B5C("现在几点？","Quelle heure est-il ?",.68),
  B5C("今天几号？","Quelle est la date aujourd'hui ?",.68),
  N("Mini-dialogue au magasin."),
  B5C("你要哪本书？","Quel livre veux-tu ?",.66),
  ...b5drill("Répondez : je veux ces deux livres.","我要这两本书。","Je veux ces deux livres."),
  ...b5drill("Demandez ensuite combien coûtent ces deux livres.","这两本书多少钱？","Combien coûtent ces deux livres ?"),
  N("Bilan : démonstratif ou nombre, puis classificateur, puis nom. Le classificateur fait partie de la structure, pas du vocabulaire décoratif."),
  ];}},

  {num:10,hanzi:"想能会可以",title:"Ajouter un verbe modal",desc:"S + modal + V + O · 想/要/会/能/可以/应该",build(){return[
  N("Leçon 10. Un verbe modal se place avant le verbe principal. On ne met pas de mot équivalent à « de » entre les deux."),
  ...b5teach("我想学汉语。","Je veux apprendre le chinois."),
  ...b5teach("他会说汉语。","Il sait parler chinois."),
  ...b5teach("我能看懂这本书。","Je peux comprendre ce livre en le lisant."),
  ...b5teach("你可以坐这儿。","Tu peux t'asseoir ici."),
  N("Nuances : 想, avoir envie ; 要, vouloir ou devoir selon le contexte ; 会, savoir faire ou probabilité ; 能, capacité ou possibilité ; 可以, permission."),
  ...b5drill("Exprimez une envie : je veux boire du thé.","我想喝茶。","J'ai envie de boire du thé."),
  ...b5drill("Exprimez une compétence : elle sait écrire les caractères chinois.","她会写汉字。","Elle sait écrire les caractères chinois."),
  ...b5drill("Exprimez une possibilité : aujourd'hui, je peux venir.","我今天能来。","Je peux venir aujourd'hui."),
  ...b5drill("Demandez une permission : puis-je lire ce livre ?","我可以看这本书吗？","Puis-je lire ce livre ?"),
  N("应该, niveau HSK2, exprime ce qu'il convient de faire."),
  ...b5teach("你应该多休息。","Tu devrais te reposer davantage."),
  ...b5drill("Donnez un conseil : tu devrais boire plus d'eau.","你应该多喝水。","Tu devrais boire davantage d'eau."),
  N("Négation : 不 se place généralement avant le modal."),
  ...b5teach("我不会开车。","Je ne sais pas conduire."),
  ...b5teach("你不可以在这儿吃饭。","Tu ne peux pas manger ici."),
  ...b5drill("Dites : demain, je ne pourrai pas venir.","我明天不能来。","Je ne pourrai pas venir demain."),
  N("Question : placez le mot interrogatif dans la proposition, sans changer la chaîne modal + verbe."),
  ...b5drill("Demandez : qu'est-ce que tu veux manger ?","你想吃什么？","Que veux-tu manger ?"),
  ...b5drill("Demandez : où peut-on acheter du thé ?","在哪儿可以买茶？","Où peut-on acheter du thé ?"),
  N("Bilan : sujet + modal + verbe principal + objet. Un seul bloc verbal, sans préposition entre les verbes."),
  ];}},

  {num:11,hanzi:"连动和双宾语",title:"Enchaîner deux actions",desc:"去 + lieu + V · 给 + personne + objet · V + personne + objet",build(){return[
  N("Leçon 11. Le chinois enchaîne souvent les verbes selon l'ordre réel des actions."),
  ...b5teach("我去商店买水果。","Je vais au magasin acheter des fruits."),
  ...b5teach("他来我家吃饭。","Il vient manger chez moi."),
  N("L'ordre est logique : aller au magasin, puis acheter ; venir chez moi, puis manger."),
  ...b5drill("Dites : je vais à la bibliothèque lire.","我去图书馆看书。","Je vais lire à la bibliothèque."),
  ...b5drill("Dites : elle vient à Pékin étudier le chinois.","她来北京学习汉语。","Elle vient à Pékin étudier le chinois."),
  N("Deuxième structure : 给 + personne + objet, donner quelque chose à quelqu'un."),
  ...b5teach("我给你一本书。","Je te donne un livre."),
  ...b5drill("Dites : le professeur nous donne deux livres.","老师给我们两本书。","Le professeur nous donne deux livres."),
  N("Certains verbes acceptent directement deux objets : personne, puis chose ou information."),
  ...b5teach("我告诉你一个好消息。","Je t'annonce une bonne nouvelle."),
  ...b5teach("他问老师一个问题。","Il pose une question au professeur."),
  ...b5teach("我送妈妈一件衣服。","J'offre un vêtement à ma mère."),
  ...b5drill("Dites : je pose une question à mon ami.","我问朋友一个问题。","Je pose une question à mon ami."),
  ...b5drill("Dites : elle offre un livre à son père.","她送爸爸一本书。","Elle offre un livre à son père."),
  N("Avec 给 comme préposition, le groupe 给 + personne vient avant le verbe."),
  ...b5teach("我给妈妈买了一杯茶。","J'ai acheté une tasse de thé pour ma mère."),
  ...b5drill("Dites : il téléphone à son professeur.","他给老师打电话。","Il téléphone à son professeur."),
  N("Question. Remplacez le destinataire inconnu par 谁."),
  ...b5drill("Demandez : à qui offres-tu un livre ?","你送谁一本书？","À qui offres-tu un livre ?"),
  ...b5drill("Forme avec 给 : pour qui achètes-tu du thé ?","你给谁买茶？","Pour qui achètes-tu du thé ?"),
  N("Bilan : les actions suivent leur chronologie ; avec deux objets, la personne précède généralement la chose."),
  ];}},

  {num:12,hanzi:"了过正在",title:"Situer l’action dans le temps",desc:"V + 了 · 还没 · V + 过 · 正在 + V",build(){return[
  N("Leçon 12. Le chinois ne conjugue pas le verbe. Il utilise des marqueurs et des mots de temps."),
  N("Verbe + 了 présente une action comme accomplie dans le contexte."),
  ...b5teach("我吃了饭。","J'ai mangé."),
  ...b5teach("他买了一本书。","Il a acheté un livre."),
  ...b5drill("Dites : hier, j'ai regardé un film.","我昨天看了一部电影。","Hier, j'ai regardé un film."),
  N("La négation de l'action accomplie utilise 没 et retire 了."),
  ...b5teach("我没吃饭。","Je n'ai pas mangé."),
  ...b5drill("Dites : il n'a pas acheté ce livre.","他没买这本书。","Il n'a pas acheté ce livre."),
  N("过 indique une expérience vécue au moins une fois."),
  ...b5teach("我去过北京。","Je suis déjà allé à Pékin."),
  ...b5teach("我没吃过这个菜。","Je n'ai jamais mangé ce plat."),
  ...b5drill("Demandez : as-tu déjà vu ce film ?","你看过这部电影吗？","As-tu déjà vu ce film ?"),
  ...b5drill("Répondez : non, je ne l'ai jamais vu.","没有，我没看过。","Non, je ne l'ai jamais vu."),
  N("在, 正在 ou 正在…呢 encadre une action en cours."),
  ...b5teach("我在吃饭。","Je suis en train de manger."),
  ...b5teach("他正在看书呢。","Il est en train de lire."),
  ...b5drill("Dites : nous sommes en train d'étudier le chinois.","我们正在学习汉语。","Nous sommes en train d'étudier le chinois."),
  N("Comparez trois sens avec le même verbe."),
  B5C("我看了这本书。","J'ai lu ce livre.",.68),
  B5C("我看过这本书。","J'ai déjà lu ce livre.",.68),
  B5C("我正在看这本书。","Je suis en train de lire ce livre.",.68),
  ...b5drill("Question en cours : que fais-tu ?","你在做什么？","Qu'est-ce que tu fais ?"),
  N("Bilan : 了, action accomplie ; 过, expérience ; 在 ou 正在, action en cours ; 没 pour nier l'accompli."),
  ];}},

  {num:13,hanzi:"是……的",title:"Mettre un détail passé en relief",desc:"S + 是 + temps/lieu/manière + V + 的",build(){return[
  N("Leçon 13. 是…的 ne raconte pas simplement qu'une action a eu lieu. Cette structure met en relief un détail déjà connu : quand, où, comment ou avec qui."),
  N("Action connue : il est venu. Question : quand ?"),
  ...b5teach("他是昨天来的。","C'est hier qu'il est venu."),
  N("Action connue : elle a acheté ce livre. Question : où ?"),
  ...b5teach("这本书是她在北京买的。","C'est à Pékin qu'elle a acheté ce livre."),
  N("À l'oral, 是 peut disparaître, mais 的 reste."),
  ...b5teach("我是坐飞机来的。","Je suis venu en avion."),
  ...b5teach("我坐飞机来的。","Je suis venu en avion."),
  ...b5drill("Mettez le moment en relief : je suis arrivé lundi.","我是星期一到的。","C'est lundi que je suis arrivé."),
  ...b5drill("Mettez le moyen en relief : il est venu en train.","他是坐火车来的。","Il est venu en train."),
  ...b5drill("Mettez la personne en relief : je suis venu avec mon ami.","我是跟朋友一起来的。","Je suis venu avec mon ami."),
  N("La question remplace le détail par un interrogatif à la même place."),
  ...b5teach("你是什么时候来的？","Quand es-tu venu ?"),
  ...b5teach("你是在哪儿买的？","Où l'as-tu acheté ?"),
  ...b5teach("你是怎么来的？","Comment es-tu venu ?"),
  ...b5drill("Demandez : avec qui es-tu venu ?","你是跟谁一起来的？","Avec qui es-tu venu ?"),
  N("Ne confondez pas avec une simple action future. Pour « je viendrai demain », dites 我明天来, sans 是…的."),
  B5C("我明天来。","Je viendrai demain.",.7),
  N("Mini-dialogue."),
  B5C("你是什么时候到北京的？","Quand es-tu arrivé à Pékin ?",.66),
  ...b5drill("Répondez : je suis arrivé hier matin.","我是昨天上午到北京的。","Je suis arrivé à Pékin hier matin."),
  N("Bilan : action passée connue, détail mis en relief entre 是 et le verbe ; 的 ferme la structure."),
  ];}},

  {num:14,hanzi:"结果和程度",title:"Résultat ou manière ?",desc:"V + 完/好/懂/见 · V + 得 + Adj",build(){return[
  N("Leçon 14. Après un verbe, un complément peut indiquer le résultat obtenu."),
  ...b5teach("我吃完了。","J'ai fini de manger."),
  ...b5teach("我买好了。","J'ai fini d'acheter ce qu'il fallait ; tout est prêt."),
  ...b5teach("我听懂了。","J'ai compris ce que j'ai entendu."),
  ...b5teach("我看见老师了。","J'ai vu le professeur."),
  ...b5drill("Dites : j'ai fini de lire ce livre.","我看完这本书了。","J'ai fini de lire ce livre."),
  ...b5drill("Dites : je n'ai pas compris.","我没听懂。","Je n'ai pas compris."),
  N("Pour décrire la manière ou le degré d'une action, utilisez verbe + 得 + adjectif."),
  ...b5teach("他说得很快。","Il parle vite."),
  ...b5teach("她汉语说得很好。","Elle parle très bien chinois."),
  ...b5teach("他写汉字写得很漂亮。","Il écrit très joliment les caractères chinois."),
  N("Avec un objet, le verbe est souvent répété : sujet + verbe + objet + verbe + 得 + description."),
  ...b5drill("Dites : il cuisine très bien.","他做饭做得很好。","Il cuisine très bien."),
  ...b5drill("Dites : elle écrit les caractères chinois très vite.","她写汉字写得很快。","Elle écrit les caractères chinois très vite."),
  N("Question : remplacez la description par 怎么样."),
  ...b5teach("他说汉语说得怎么样？","Comment parle-t-il le chinois ?"),
  ...b5drill("Demandez : comment cuisine-t-elle ?","她做饭做得怎么样？","Comment cuisine-t-elle ?"),
  N("Ne confondez pas les trois de : 好看的衣服, 的 décrit un nom ; 说得很好, 得 décrit une action ; 慢慢地说, 地 place une manière avant le verbe."),
  B5C("请慢慢地说。","Parlez lentement, s'il vous plaît.",.68),
  ...b5drill("Produisez une demande plus simple avec 一点儿 : parlez un peu plus lentement.","请说慢一点儿。","Parlez un peu plus lentement, s'il vous plaît."),
  N("Bilan : résultat directement après le verbe ; manière après 得 ; 的 reste attaché au nom décrit."),
  ];}},

  {num:15,hanzi:"比较和程度",title:"Comparer et nuancer",desc:"A 比 B + Adj · 没有 · 一样 · 有点儿 · Adj + 一点儿",build(){return[
  N("Leçon 15. Comparaison positive : A + 比 + B + adjectif. N'ajoutez pas 很 devant l'adjectif dans ce modèle simple."),
  ...b5teach("今天比昨天热。","Aujourd'hui, il fait plus chaud qu'hier."),
  ...b5teach("我比弟弟高。","Je suis plus grand que mon petit frère."),
  ...b5drill("Dites : le thé est plus chaud que le café.","茶比咖啡热。","Le thé est plus chaud que le café."),
  N("Pour quantifier l'écart, ajoutez 一点儿 ou 得多 après l'adjectif."),
  ...b5teach("这本书比那本贵一点儿。","Ce livre est un peu plus cher que celui-là."),
  ...b5teach("北京比这里冷得多。","Pékin est beaucoup plus froid qu'ici."),
  N("Comparaison négative : A 没有 B + adjectif signifie que A est moins adjectif que B."),
  ...b5teach("我没有哥哥高。","Je ne suis pas aussi grand que mon grand frère."),
  ...b5drill("Dites : aujourd'hui, il ne fait pas aussi froid qu'hier.","今天没有昨天冷。","Aujourd'hui, il ne fait pas aussi froid qu'hier."),
  N("Égalité : A 跟 B 一样 + adjectif."),
  ...b5teach("这本书跟那本书一样贵。","Ce livre est aussi cher que celui-là."),
  ...b5drill("Dites : ma tasse est aussi grande que la tienne.","我的杯子跟你的一样大。","Ma tasse est aussi grande que la tienne."),
  N("Degré sans comparaison : 有点儿 avant un adjectif exprime souvent un léger problème ; adjectif + 一点儿 demande ou constate un changement mesuré."),
  ...b5teach("这个菜有点儿辣。","Ce plat est un peu trop pimenté."),
  ...b5teach("请说慢一点儿。","Parlez un peu plus lentement, s'il vous plaît."),
  ...b5drill("Dites : cette chambre est un peu petite.","这个房间有点儿小。","Cette chambre est un peu petite."),
  ...b5drill("Demandez une taille supérieure : je voudrais une chambre un peu plus grande.","我想要一个大一点儿的房间。","Je voudrais une chambre un peu plus grande."),
  N("Question comparative : qui est plus grand, toi ou ton frère ?"),
  ...b5teach("你和你弟弟谁高？","Qui est plus grand, toi ou ton petit frère ?"),
  N("Bilan : 比 pour plus, 没有 pour moins, 一样 pour égalité, 有点儿 pour un léger défaut."),
  ];}},

  {num:16,hanzi:"连接两句话",title:"Relier deux idées",desc:"因为…所以… · 虽然…但是… · 先…再… · 一边…一边…",build(){return[
  N("Leçon 16. HSK2 introduit des paires qui organisent clairement deux propositions."),
  N("Cause puis conséquence : 因为…所以…. En conversation, l'un des deux peut disparaître, mais apprenez d'abord la paire complète."),
  ...b5teach("因为下雨，所以我不去公园。","Comme il pleut, je ne vais pas au parc."),
  ...b5drill("Changez la cause : comme je suis malade, je ne vais pas à l'école.","因为我生病了，所以我不去学校。","Comme je suis malade, je ne vais pas à l'école."),
  N("Concession puis contraste : 虽然…但是…."),
  ...b5teach("虽然这本书很贵，但是我很喜欢。","Même si ce livre est cher, je l'aime beaucoup."),
  ...b5drill("Dites : même si le chinois est difficile, il est très intéressant.","虽然汉语很难，但是很有意思。","Même si le chinois est difficile, il est très intéressant."),
  N("Ordre d'actions : 先…再…, d'abord, puis."),
  ...b5teach("我先吃饭，再看书。","Je mange d'abord, puis je lis."),
  ...b5drill("Dites : va d'abord au magasin, puis rentre à la maison.","你先去商店，再回家。","Va d'abord au magasin, puis rentre à la maison."),
  N("Actions simultanées : 一边…一边…. Les deux actions ont normalement le même sujet."),
  ...b5teach("我一边吃饭，一边看电视。","Je regarde la télévision en mangeant."),
  ...b5drill("Dites : elle écoute de la musique en lisant.","她一边看书，一边听音乐。","Elle écoute de la musique en lisant."),
  N("Question de cause avec 为什么 ; réponse avec 因为."),
  B5C("你为什么学习汉语？","Pourquoi étudies-tu le chinois ?",.68),
  ...b5drill("Répondez : parce que j'aime le chinois.","因为我喜欢汉语。","Parce que j'aime le chinois."),
  N("Production guidée. Expliquez un projet en trois étapes : raison, première action, action suivante."),
  ...b5drill("Modèle : comme je veux mieux parler chinois, j'écoute d'abord, puis je répète la phrase.","因为我想说好汉语，所以我先听，再说一遍。","Comme je veux mieux parler chinois, j'écoute d'abord, puis je répète la phrase."),
  N("Bilan : chaque paire indique la relation logique entre les deux morceaux ; ne changez pas l'ordre des connecteurs."),
  ];}},

  {num:17,hanzi:"句子修理课",title:"Atelier : réparer et transformer",desc:"ordre des mots · choix du modèle · questions corrigées",exercise:true,build(){return[
  N("Leçon 17. Atelier de réparation. Écoutez une intention française, construisez la phrase, puis comparez avec la correction expliquée."),
  ...b5drill("Phrase 1 : ma sœur aînée est très grande. N'utilisez pas 是 devant l'adjectif.","我姐姐很高。","Ma sœur aînée est très grande."),
  N("Correction : sujet + adjectif. 很 relie naturellement le sujet à la qualité."),
  ...b5drill("Phrase 2 : j'aime les chats très petits. L'objet entier est adjectif + 的 + nom.","我喜欢很小的猫。","J'aime les chats très petits."),
  N("Pour dire simplement « les petits chats » ou « les chatons », 小猫 est plus naturel. La description 很小的猫 insiste sur leur très petite taille."),
  B5C("我喜欢小猫。","J'aime les petits chats.",.7),
  ...b5drill("Phrase 3 : demain, je lis à la bibliothèque. Placez le temps avant le lieu.","我明天在图书馆看书。","Demain, je lis à la bibliothèque."),
  ...b5drill("Phrase 4 : il y a un chat sous la table. Commencez par le lieu.","桌子下面有一只猫。","Il y a un chat sous la table."),
  ...b5drill("Phrase 5 : hier, je ne suis pas allé à l'école. Choisissez 没.","我昨天没去学校。","Hier, je ne suis pas allé à l'école."),
  ...b5drill("Phrase 6 : est-ce que tu aimes le thé ? Utilisez 吗.","你喜欢茶吗？","Aimes-tu le thé ?"),
  ...b5drill("Même question avec la forme affirmative-négative.","你喜不喜欢茶？","Aimes-tu le thé ?"),
  ...b5drill("Phrase 7 : où ton ami apprend-il le chinois ? Gardez 哪儿 à la place du lieu.","你的朋友在哪儿学习汉语？","Où ton ami apprend-il le chinois ?"),
  ...b5drill("Phrase 8 : je veux acheter ces deux livres. Respectez démonstratif, nombre, classificateur, nom.","我想买这两本书。","Je veux acheter ces deux livres."),
  ...b5drill("Phrase 9 : je suis venu en avion. Utilisez 是…的.","我是坐飞机来的。","Je suis venu en avion."),
  ...b5drill("Phrase 10 : elle parle chinois très vite. Utilisez 得.","她汉语说得很快。","Elle parle chinois très vite."),
  ...b5drill("Phrase 11 : ce livre est un peu plus cher que celui-là.","这本书比那本贵一点儿。","Ce livre est un peu plus cher que celui-là."),
  ...b5drill("Phrase 12 : comme je suis fatigué, je rentre d'abord me reposer.","因为我累了，所以我先回家休息。","Comme je suis fatigué, je rentre d'abord me reposer."),
  N("Dernier diagnostic. Une question chinoise conserve la place de la réponse. Dites d'abord : Wang Ming boira du café au restaurant demain."),
  B5C("王明明天在饭店喝咖啡。","Demain, Wang Ming boira du café au restaurant.",.68),
  ...b5drill("Remplacez la personne.","谁明天在饭店喝咖啡？","Qui boira du café au restaurant demain ?"),
  ...b5drill("Remplacez le moment.","王明什么时候在饭店喝咖啡？","Quand Wang Ming boira-t-il du café au restaurant ?"),
  ...b5drill("Remplacez le lieu.","王明明天在哪儿喝咖啡？","Où Wang Ming boira-t-il du café demain ?"),
  ...b5drill("Remplacez l'objet.","王明明天在饭店喝什么？","Que boira Wang Ming au restaurant demain ?"),
  N("Vous savez maintenant reconstruire une phrase depuis sa fonction, et non depuis l'ordre du français."),
  ];}},

  {num:18,hanzi:"综合对话",title:"Grande pratique : jouer les deux rôles",desc:"présentation · restaurant · rendez-vous · questions libres",exercise:true,build(){return[
  N("Leçon 18. Grande pratique. Vous jouez les deux personnages. Après chaque réplique, répétez-la, puis produisez la réponse suivante avant le modèle."),
  N("Scène 1. Deux étudiants se rencontrent."),
  B5C("你好，你是新学生吗？","Bonjour, es-tu un nouvel étudiant ?",.62),HOLD(),
  ...b5drill("Jouez le nouvel étudiant : oui, je m'appelle Li Ming et je viens de France.","是的，我叫李明，我从法国来。","Oui, je m'appelle Li Ming et je viens de France."),
  B5C("你为什么学习汉语？","Pourquoi apprends-tu le chinois ?",.64),HOLD(),
  ...b5drill("Répondez avec 因为 : parce que j'aime le chinois et la cuisine chinoise.","因为我喜欢汉语和中国菜。","Parce que j'aime le chinois et la cuisine chinoise."),
  B5C("你每天在哪儿学习？","Où étudies-tu chaque jour ?",.64),HOLD(),
  ...b5drill("Répondez avec temps, lieu, verbe : l'après-midi, j'étudie à la bibliothèque.","我下午在图书馆学习。","L'après-midi, j'étudie à la bibliothèque."),
  N("Scène 2. Au restaurant."),
  B5C("你想吃什么？","Que veux-tu manger ?",.64),HOLD(),
  ...b5drill("Répondez avec un objet décrit : je voudrais manger des plats pas trop pimentés.","我想吃点儿不太辣的菜。","Je voudrais manger des plats qui ne soient pas trop pimentés."),
  B5C("这个菜怎么样？","Que penses-tu de ce plat ?",.64),HOLD(),
  ...b5drill("Comparez : il est meilleur que celui-là, mais un peu cher.","这个菜比那个好吃，但是有点儿贵。","Ce plat est meilleur que celui-là, mais il est un peu cher."),
  B5C("你喝不喝茶？","Bois-tu du thé ?",.64),HOLD(),
  ...b5drill("Répondez négativement et proposez de l'eau.","我不喝茶，我想喝水。","Je ne bois pas de thé ; je voudrais de l'eau."),
  N("Scène 3. Organiser un rendez-vous."),
  B5C("你明天能不能来我家？","Peux-tu venir chez moi demain ?",.64),HOLD(),
  ...b5drill("Répondez : demain matin je ne peux pas, mais l'après-midi je peux.","我明天上午不能来，但是下午可以。","Je ne peux pas venir demain matin, mais je peux l'après-midi."),
  B5C("你怎么来？","Comment viendras-tu ?",.66),HOLD(),
  ...b5drill("Répondez au futur simple, sans la structure de mise en relief : je viendrai à vélo.","我骑自行车来。","Je viendrai à vélo."),
  B5C("你来的时候，可以帮我买两杯咖啡吗？","Quand tu viendras, pourras-tu m'acheter deux cafés ?",.6),HOLD(),
  ...b5drill("Acceptez et demandez quel type de café.","可以。你想喝什么样的咖啡？","D'accord. Quel genre de café veux-tu boire ?"),
  N("Production finale. Créez maintenant cinq phrases personnelles : une identité avec 是, une habitude S V O, un objet décrit avec 的, une question avec un mot interrogatif et une comparaison."),
  TH(),
  B5C("我是学生。我每天喝茶。我喜欢有意思的书。你在哪儿学习汉语？今天比昨天热。","Je suis étudiant. Je bois du thé chaque jour. J'aime les livres intéressants. Où étudies-tu le chinois ? Aujourd'hui, il fait plus chaud qu'hier.",.56),
  HOLD("Écoute le modèle, puis crée tes cinq phrases avant de terminer, puis ▶"),
  N("Félicitations. Vous avez terminé le Bonus 5. Réécoutez les leçons 2, 3, 8, 14 et 17 : elles donnent l'ossature la plus utile pour fabriquer vos propres phrases."),
  B5C("多说，多问，慢慢就会说得更自然。","Parlez davantage, posez davantage de questions : peu à peu, vous parlerez plus naturellement.",.66),
  B5C("再见！","Au revoir !",.72),
  ];}}
  ]
});
