/* Nouveau HSK 3.0 · Leçon 6 — 高铁上还可以点外卖
   Source : « 新HSK教程 3 », leçon 6. Exercices audio originaux. */
registerChapter({
  group:"hsk3", id:"hsk3-06", badge:6,
  hanzi:"高铁上还可以点外卖", title:"Leçon 6 · Voyager en train à grande vitesse",
  desc:"6 cours · 该…了 · 如果…就… · 越来越 · trajet pratique",
  intro:"Ce parcours suit tout un trajet en train à grande vitesse : achat du billet, route vers la gare, contrôle et expérience à bord. Les ateliers mettent l'accent sur la décision au bon moment, l'hypothèse et une évolution progressive.",
  lessons:[

  {num:1, hanzi:"该买票了", title:"Partie 1 · Acheter le billet", desc:"Dialogue 1 · premier trajet · 该…了", build(){return[
  N("Partie 1. Bai Jiayue n'a encore jamais pris le train à grande vitesse. Il est temps d'acheter les billets."),
  HC("家月，咱们该买去上海的票了。你打算怎么去上海？", "Jiayue, il est temps d'acheter nos billets pour Shanghai. Comment comptes-tu y aller ?", .54),
  HC("我还没坐过高铁，咱们坐高铁去，怎么样？", "Je n'ai encore jamais pris le train à grande vitesse. Et si nous y allions ainsi ?", .58),
  HC("没问题，从北京到上海的高铁很多，非常方便。", "Pas de problème. Il y a beaucoup de trains entre Pékin et Shanghai ; c'est très pratique.", .58),
  HC("怎么买票？", "Comment achète-t-on les billets ?", .72),
  HC("用手机App就能买。给我你的护照，我帮你买。", "On peut les acheter simplement avec une application. Donne-moi ton passeport, je vais t'aider.", .58),
  HC("太好了！我早就听说过高铁，终于可以坐了。", "Génial ! J'en entends parler depuis longtemps ; je vais enfin pouvoir le prendre.", .58),
  HC("高铁又快又舒服，你一定会喜欢的。", "Le train à grande vitesse est rapide et confortable ; tu vas sûrement l'apprécier.", .62),

  N("[[该…了|gāi…le]] indique que le moment approprié est arrivé : « il est temps de ». Ce n'est pas une obligation administrative aussi forte que 必须."),
  HC("咱们该买票了。", "Il est temps d'acheter nos billets.", .72),
  HC("天晚了，我该回家了。", "Il se fait tard ; il est temps que je rentre.", .7),
  HC("电影快开始了，我们该进去了。", "Le film va commencer ; il est temps d'entrer.", .68),
  ...h3drill("Votre train part bientôt : il est temps d'aller à la gare.", "火车快开了，我们该去车站了。", "Le train va bientôt partir ; il est temps d'aller à la gare."),
  ...h3drill("Vous êtes fatigué le soir : il est temps de dormir.", "我累了，该睡觉了。", "Je suis fatigué ; il est temps de dormir."),

  N("Pratique : [[用|yòng]] + moyen + 就能 + action présente une solution facile. 用手机App就能买 : une application suffit."),
  ...h3drill("Dites que le passeport suffit pour entrer en gare.", "用护照就能进站。", "Le passeport suffit pour entrer dans la gare."),
  N("Fin de la partie 1. Vous savez décider au bon moment et présenter un moyen simple."),
  ];}},

  {num:2, hanzi:"如果没走错", title:"Partie 2 · En route vers la gare", desc:"Dialogue 2 · itinéraire · 如果…就…", build(){return[
  N("Partie 2. Liu Ming conduit les voyageurs à la gare du Sud, mais la circulation ralentit."),
  HC("过了前面的路口就到高铁站了。", "Après le carrefour devant nous, nous arriverons à la gare.", .62),
  HC("已经九点了，这条路车很多，您小心点儿。", "Il est déjà neuf heures. Il y a beaucoup de voitures sur cette route ; soyez prudent.", .58),
  HC("好，你们还有一个小时，应该不会迟到的。", "D'accord. Il vous reste une heure ; vous ne devriez pas être en retard.", .58),
  HC("这条路红绿灯也多。", "Il y a aussi beaucoup de feux sur cette route.", .68),
  HC("是啊，又过一个路口，后来就走不动了。", "Oui. Après un autre carrefour, la circulation s'est complètement bloquée.", .58),
  HC("那您今天为什么走了这条路？", "Alors pourquoi avez-vous pris cette route aujourd'hui ?", .64),
  HC("我一急就走错了。如果没走错，二十分钟以前就到了。", "Dans la précipitation, je me suis trompé de route. Sinon, nous serions arrivés il y a vingt minutes.", .56),

  N("Hypothèse : 如果 + condition, sujet + 就 + résultat. Si le sujet du résultat est exprimé, il vient avant 就."),
  HC("如果你需要帮忙，就给我打电话。", "Si tu as besoin d'aide, appelle-moi.", .68),
  HC("如果有时间，我就去上海玩几天。", "Si j'ai le temps, j'irai quelques jours à Shanghai.", .66),
  HC("如果明天下雨，我们就坐地铁。", "S'il pleut demain, nous prendrons le métro.", .68),
  N("Dans 如果有时间，我就去…, 我 se place avant 就 car c'est le sujet de la conséquence."),
  ...h3drill("Faites une hypothèse : si nous partons maintenant, nous ne serons pas en retard.", "如果我们现在出发，就不会迟到。", "Si nous partons maintenant, nous ne serons pas en retard."),
  ...h3drill("Changez le sujet du résultat : s'il y a trop de monde, je prendrai un taxi.", "如果人太多，我就坐出租车。", "S'il y a trop de monde, je prendrai un taxi."),
  ...h3drill("Situation passée contraire aux faits : si je ne m'étais pas trompé de route, je serais déjà arrivé.", "如果我没走错路，早就到了。", "Si je ne m'étais pas trompé de route, je serais arrivé depuis longtemps."),

  N("Jeu de rôle. Votre ami s'inquiète du retard. Rassurez-le avec une condition concrète."),
  ...h3drill("Dites : si la circulation avance, nous arriverons dans vingt minutes.", "如果路上不堵车，我们二十分钟就能到。", "S'il n'y a pas d'embouteillage, nous arriverons en vingt minutes."),
  N("Fin de la partie 2. Vous savez relier clairement une condition à sa conséquence."),
  ];}},

  {num:3, hanzi:"条件和时间", title:"Partie 3 · Focus intermédiaire", desc:"如果 / 一…就… / …了就… / 该…了", build(){return[
  N("Focus intermédiaire. Quatre structures contiennent souvent 就, mais elles ne répondent pas à la même question."),
  N("如果…就… construit une condition possible."),
  HC("如果票买好了，我们就出发。", "Si les billets sont achetés, nous partons.", .68),
  N("一…就… décrit une réaction immédiate ou habituelle : dès que."),
  HC("我一坐车就想睡觉。", "Dès que je monte dans un véhicule, j'ai envie de dormir.", .7),
  N("Verbe + 了 + 就… enchaîne deux actions achevées ou programmées."),
  HC("我检了票就进站。", "Dès que j'ai validé mon billet, j'entre dans la gare.", .7),
  N("该…了 juge que le bon moment est arrivé."),
  HC("已经九点了，我们该检票了。", "Il est déjà neuf heures ; il est temps de passer le contrôle.", .68),

  N("Choisissez la relation. Une condition météo : s'il neige, nous prendrons le train."),
  ...h3drill("Répondez.", "如果下雪，我们就坐高铁。", "S'il neige, nous prendrons le train à grande vitesse."),
  N("Une réaction régulière : dès qu'il est pressé, il se trompe."),
  ...h3drill("Répondez.", "他一着急就会走错。", "Dès qu'il est pressé, il se trompe."),
  N("Deux étapes : après le contrôle, nous montons à l'étage."),
  ...h3drill("Répondez.", "我们检了票就上楼。", "Dès que nous avons passé le contrôle, nous montons."),
  N("Le moment approprié : il est temps de préparer les bagages."),
  ...h3drill("Répondez.", "我们该准备行李了。", "Il est temps de préparer les bagages."),
  N("Fin du focus. Ne choisissez pas 就 isolément : identifiez la relation complète autour de lui."),
  ];}},

  {num:4, hanzi:"人越来越多", title:"Partie 4 · Contrôle et embarquement", desc:"Dialogue 3 · gare · 越来越", build(){return[
  N("Partie 4. À la gare, Bai Jiayue et Li Wen font la queue pour le contrôle de sécurité et des billets."),
  HC("李文，我的耳机没电了，你有充电宝吗？", "Li Wen, mes écouteurs n'ont plus de batterie. As-tu une batterie externe ?", .58),
  HC("有，这些常用的东西我都放在包里了，我给你拿。", "Oui. Je mets toutes ces choses utiles dans mon sac ; je te la donne.", .58),
  HC("前面的人越来越多。", "Il y a de plus en plus de monde devant nous.", .7),
  HC("对，快到检票时间了。咱们一起走，别分开。", "Oui, l'heure du contrôle approche. Restons ensemble, ne nous séparons pas.", .58),
  HC("我还没拿到车票呢。", "Je n'ai toujours pas récupéré mon billet.", .68),
  HC("不用拿票，刷护照就能检票进站。", "Pas besoin de billet papier : il suffit de scanner le passeport pour entrer.", .62),
  HC("去哪儿检票？", "Où passe-t-on le contrôle ?", .72),
  HC("检票口在二层，咱们一会儿坐电梯上去。", "Le contrôle est au deuxième étage ; nous prendrons l'ascenseur dans un instant.", .6),

  N("[[越来越|yuèláiyuè]] + adjectif ou verbe psychologique décrit une évolution progressive avec le temps. N'ajoutez pas 很 ou 非常 entre les deux."),
  HC("前面的人越来越多。", "Il y a de plus en plus de monde devant nous.", .7),
  HC("高铁越来越方便了。", "Le train à grande vitesse est de plus en plus pratique.", .7),
  HC("我越来越喜欢坐火车了。", "J'aime de plus en plus prendre le train.", .68),
  HC("妈妈越来越着急了。", "La mère devient de plus en plus inquiète.", .68),
  ...h3drill("Décrivez la foule : la gare devient de plus en plus fréquentée.", "车站里的人越来越多。", "Il y a de plus en plus de monde dans la gare."),
  ...h3drill("Décrivez votre progression : je comprends de mieux en mieux le chinois.", "我越来越听得懂中文了。", "Je comprends de mieux en mieux le chinois."),
  N("Attention : 越来越很方便 est incorrect. 越来越 contient déjà l'idée de degré croissant."),

  N("Mission pratique. Demandez où se trouve le contrôle, puis expliquez comment entrer."),
  ...h3drill("Posez la question.", "请问，去哪儿检票？", "Excusez-moi, où passe-t-on le contrôle ?"),
  ...h3drill("Donnez la réponse complète.", "检票口在二层，刷护照就能进站。", "Le contrôle est au deuxième étage ; il suffit de scanner le passeport pour entrer."),
  N("Fin de la partie 4. Vous savez vous orienter en gare et décrire une évolution en cours."),
  ];}},

  {num:5, hanzi:"高铁上的体验", title:"Partie 5 · L'expérience à bord", desc:"Récit guidé · service · bilan personnel", build(){return[
  N("Partie 5. Bai Jiayue raconte son premier voyage en train à grande vitesse."),
  HC("这次放假，我去了北京，还去了上海。", "Pendant ces vacances, je suis allée à Pékin et aussi à Shanghai.", .64),
  HC("我是从北京南站坐高铁去的上海。", "C'est depuis la gare du Sud de Pékin que j'ai pris le train pour Shanghai.", .62),
  HC("我觉得坐在高铁上跟坐在家里的沙发上一样，又安静又舒服。", "Je trouve qu'être assise dans le train, c'est comme être sur le canapé chez soi : calme et confortable.", .54),
  HC("坐累了就站一会儿，饿了就点外卖。", "Quand on est fatigué d'être assis, on se lève un moment ; quand on a faim, on commande à manger.", .6),
  HC("对，你没听错，高铁上可以点外卖。", "Oui, tu as bien entendu : on peut commander à manger dans le train.", .64),
  HC("只需要选择好车站和想吃的东西，到站时不用下车，服务员就会给你拿过来。", "Il suffit de choisir la gare et le repas. À l'arrivée, inutile de descendre : un employé vous l'apporte.", .5),
  HC("现在喜欢坐高铁的人越来越多。", "Aujourd'hui, de plus en plus de personnes aiment prendre le train à grande vitesse.", .64),
  HC("我爸妈来中国旅游的时候，我一定要带他们坐一次高铁。", "Quand mes parents viendront voyager en Chine, je tiens à leur faire prendre ce train une fois.", .56),

  N("Compréhension. D'où Bai Jiayue est-elle partie ?"),
  TH(), HC("她从北京南站出发。", "Elle est partie de la gare du Sud de Pékin.", .7), HOLD(),
  N("Comment reçoit-on une commande à bord ?"),
  TH(), HC("到站时不用下车，服务员会把外卖拿过来。", "À l'arrivée en gare, on ne descend pas ; un employé apporte la commande.", .64), HOLD(),
  N("Pourquoi veut-elle faire essayer le train à ses parents ?"),
  TH(), HC("因为高铁又快又舒服，也很方便。", "Parce que le train est rapide, confortable et pratique.", .68), HOLD(),

  N("Réponse personnelle. Comparez deux moyens de transport et donnez votre préférence. Modèle :"),
  TH(), HC("飞机比较快，但是高铁越来越方便，所以我更喜欢坐高铁。", "L'avion est plus rapide, mais le train devient de plus en plus pratique ; je préfère donc le train.", .62), HOLD("Répète ce modèle ou donne ta propre réponse, puis ▶"),
  N("Fin de la partie 5. Vous savez raconter un trajet avec des détails réellement utiles."),
  ];}},

  {num:6, hanzi:"综合练习", title:"Partie 6 · Exercices créés", desc:"Hypothèses · évolution · trajet complet", exercise:true, build(){return[
  N("Exercices originaux de la leçon 6. Répondez avant la correction."),
  N("Exercice 1. Il est temps de partir pour la gare."),
  TH(), HC("我们该去车站了。", "Il est temps d'aller à la gare.", .72), HOLD(),
  N("Exercice 2. S'il y a trop de monde, nous prendrons l'escalier."),
  TH(), HC("如果人太多，我们就走楼梯。", "S'il y a trop de monde, nous prendrons l'escalier.", .68), HOLD(),
  N("Exercice 3. Placez le sujet du résultat : s'il pleut, Li Wen prendra le métro."),
  TH(), HC("如果下雨，李文就坐地铁。", "S'il pleut, Li Wen prendra le métro.", .68), HOLD(),
  N("Exercice 4. Décrivez une évolution : les billets deviennent de plus en plus faciles à acheter."),
  TH(), HC("买票越来越方便了。", "Acheter des billets devient de plus en plus pratique.", .68), HOLD(),
  N("Exercice 5. Dites que vous aimez de plus en plus voyager en train."),
  TH(), HC("我越来越喜欢坐火车旅行了。", "J'aime de plus en plus voyager en train.", .68), HOLD(),
  N("Exercice 6. Demandez une batterie externe, car vos écouteurs sont déchargés."),
  TH(), HC("我的耳机没电了，你有充电宝吗？", "Mes écouteurs n'ont plus de batterie ; as-tu une batterie externe ?", .66), HOLD(),
  N("Exercice 7. Expliquez l'entrée en gare : il suffit de scanner le passeport."),
  TH(), HC("不用拿票，刷护照就能进站。", "Inutile de prendre un billet papier ; il suffit de scanner le passeport pour entrer.", .68), HOLD(),
  N("Exercice 8. Incident complet. Vous êtes dans les embouteillages : continuez en voiture s'il reste assez de temps ; sinon, proposez le métro."),
  TH(), HC("如果时间还够，我们就继续开车；如果来不及，我们就坐地铁。", "S'il reste assez de temps, continuons en voiture ; sinon, prenons le métro.", .62), HOLD(),
  N("Bilan des leçons 4 à 6. Vous savez préparer un voyage, gérer un retard, décrire des loisirs et effectuer un trajet moderne en autonomie."),
  HC("如果准备好了，我们现在就出发。", "Si tout est prêt, partons tout de suite.", .7),
  HC("再见！", "Au revoir !", .74),
  ];}}
  ]
});
