/* Nouveau HSK 3.0 · Leçon 8 — 今天我出院了
   Source : « 新HSK教程 3 », leçon 8. Exercices audio originaux. */
registerChapter({group:"hsk3",id:"hsk3-08",badge:8,
  hanzi:"今天我出院了",title:"Leçon 8 · Santé et sortie de l'hôpital",
  desc:"6 cours · 下去 · mots séparables · durée · avant/après",
  intro:"Cette leçon vous apprend à décrire un état de santé, comprendre des consignes médicales simples et raconter une hospitalisation. Un atelier spécial distingue la durée d'une action de la durée écoulée depuis un événement.",lessons:[

  {num:1,hanzi:"不能再胖下去了",title:"Partie 1 · Reprendre le sport",desc:"Dialogue 1 · habitudes · continuation avec 下去",build(){return[
  N("Partie 1. Au gymnase, Li Wen remarque que Chen Tianzhong vient maintenant tous les jours."),
  HC("天中，最近常看见你来体育馆。", "Tianzhong, ces derniers temps je te vois souvent au gymnase.", .64),
  HC("我每天下午都来跑一个小时步。", "Je viens courir une heure tous les après-midi.", .66),
  HC("你的运动习惯真不错。", "Tes habitudes sportives sont vraiment bonnes.", .7),
  HC("因为我今年胖了十多斤，不能再胖下去了，有点儿不健康。", "Parce que j'ai pris plus de cinq kilos cette année. Je ne peux pas continuer à grossir ; ce n'est pas très sain.", .56),
  HC("我下课以后常去打羽毛球，你也来玩儿吧。", "Après les cours, je joue souvent au badminton. Viens jouer avec nous.", .6),
  HC("我知道，但是你们的水平太高了，我打得不怎么样。", "Je sais, mais votre niveau est trop élevé ; je ne joue pas très bien.", .58),
  HC("没关系，我可以教你。", "Ce n'est pas grave, je peux t'apprendre.", .7),

  N("Le complément [[下去|xiàqu]] après un verbe ou un adjectif signifie que l'action ou l'état déjà commencé continue."),
  HC("我不能再胖下去了。", "Je ne peux pas continuer à grossir.", .7),
  HC("这本书很有意思，我想读下去。", "Ce livre est intéressant ; je veux continuer à le lire.", .68),
  HC("如果再热下去，就不能出门了。", "S'il continue à faire plus chaud, on ne pourra plus sortir.", .68),
  ...h3drill("Encouragez votre ami : continue à apprendre le chinois.", "你要继续学下去。", "Tu dois continuer à apprendre le chinois."),
  ...h3drill("Refusez une situation : je ne veux pas continuer à vivre ici.", "我不想在这里住下去了。", "Je ne veux pas continuer à vivre ici."),

  N("跑步 est un mot séparable : on place la durée entre 跑 et 步 : 跑一个小时步. On ne dit pas 跑步一个小时 dans le modèle étudié ici."),
  ...h3teach("我每天跑一个小时步。", "Je cours une heure chaque jour."),
  ...h3drill("Changez la durée : je cours une demi-heure chaque matin.", "我每天早上跑半个小时步。", "Je cours une demi-heure chaque matin."),
  N("Fin de la partie 1. Vous savez parler d'une habitude et décider de la poursuivre ou de l'arrêter."),
  ];}},

  {num:2,hanzi:"耳朵一直有点儿疼",title:"Partie 2 · Décrire ses symptômes",desc:"Dialogue 2 · fièvre · mots séparables",build(){return[
  N("Partie 2. En classe, Annie trouve que Chen Tianzhong n'a pas l'air bien."),
  HC("你怎么了？看上去有点儿不舒服。", "Qu'est-ce qui t'arrive ? Tu n'as pas l'air très bien.", .62),
  HC("昨天游完泳以后，耳朵一直有点儿疼。", "Depuis que j'ai fini de nager hier, j'ai constamment un peu mal à l'oreille.", .58),
  HC("是不是感冒了？发烧吗？", "Tu as peut-être pris froid ? Tu as de la fièvre ?", .66),
  HC("好像发低烧了。", "Il me semble avoir un peu de fièvre.", .7),
  HC("我送你去医院，让医生检查一下吧。", "Je t'emmène à l'hôpital pour qu'un médecin t'examine.", .62),
  HC("我先回去睡一觉，可能休息休息就好了。", "Je vais d'abord rentrer dormir un peu ; du repos suffira peut-être.", .58),
  HC("好吧，如果下午还发烧，就一定要去看医生。", "D'accord, mais si tu as encore de la fièvre cet après-midi, il faudra vraiment consulter.", .58),
  HC("谢谢关心，我会注意的。", "Merci de t'en soucier ; je ferai attention.", .68),

  N("Les mots séparables ressemblent à un verbe unique mais contiennent un verbe et un nom. Le complément s'insère : 游泳 devient 游完泳 ; 睡觉 devient 睡一觉 ; 下雨 devient 下了两次雨."),
  HC("我游完泳以后回家。", "Je rentre après avoir fini de nager.", .68),
  HC("我想睡一觉。", "Je voudrais dormir un peu.", .72),
  HC("今天下了两次雨。", "Il a plu deux fois aujourd'hui.", .72),
  ...h3drill("Dites : après l'examen, je vais voyager.", "考完试以后，我要去旅游。", "Après l'examen, je vais voyager."),
  ...h3drill("Dites : j'ai nagé une heure hier.", "我昨天游了一个小时泳。", "J'ai nagé une heure hier."),
  ...h3drill("Dites : prends d'abord une douche, puis mange.", "你先洗个澡，再吃饭。", "Prends d'abord une douche, puis mange."),

  N("Jeu de rôle. Demandez depuis quand la douleur a commencé, puis proposez une consultation."),
  ...h3drill("Posez la question.", "你的耳朵什么时候开始疼的？", "Quand ton oreille a-t-elle commencé à te faire mal ?"),
  ...h3drill("Faites la proposition.", "我陪你去医院检查一下吧。", "Je vais t'accompagner à l'hôpital pour un examen."),
  N("Fin de la partie 2. Vous pouvez décrire des symptômes simples et comprendre des mots séparables en contexte."),
  ];}},

  {num:3,hanzi:"多久和多久以前",title:"Partie 3 · Focus intermédiaire sur la durée",desc:"Action durable · temps écoulé depuis un événement",build(){return[
  N("Focus intermédiaire. Deux phrases françaises avec « depuis » peuvent exiger des structures chinoises différentes."),
  N("Une action continue encore maintenant : verbe + durée + 了."),
  HC("我在医院住了三天了。", "Je suis à l'hôpital depuis trois jours.", .7),
  HC("我学中文学了两年了。", "J'apprends le chinois depuis deux ans.", .7),
  N("Un événement ponctuel est terminé, puis le temps s'écoule : événement + durée + 了."),
  HC("她回家两个月了。", "Cela fait deux mois qu'elle est rentrée.", .7),
  HC("开学已经三个多星期了。", "Cela fait déjà plus de trois semaines que les cours ont commencé.", .68),
  HC("我上次来医院已经是两年前了。", "Ma dernière visite à l'hôpital remonte déjà à deux ans.", .68),

  N("Comparez : 我住了三天院了 signifie que l'hospitalisation dure depuis trois jours. 我出院三天了 signifie que la sortie a eu lieu il y a trois jours."),
  HC("我住了三天院了。", "Je suis hospitalisé depuis trois jours.", .72),
  HC("我出院三天了。", "Je suis sorti de l'hôpital il y a trois jours.", .72),
  ...h3drill("Action encore en cours : je vis à Pékin depuis six mois.", "我在北京住了六个月了。", "Je vis à Pékin depuis six mois."),
  ...h3drill("Événement terminé : cela fait six mois que je suis arrivé à Pékin.", "我到北京六个月了。", "Je suis arrivé à Pékin il y a six mois."),
  ...h3drill("État depuis un événement : nous sommes mariés depuis deux ans.", "我们结婚两年了。", "Nous sommes mariés depuis deux ans."),
  N("À l'oral, choisissez d'abord : est-ce l'action qui dure encore, ou le temps depuis un événement terminé ?"),
  N("Fin du focus. Cette décision évite les traductions mécaniques du français « depuis »."),
  ];}},

  {num:4,hanzi:"住院做检查",title:"Partie 4 · Une visite à l'hôpital",desc:"Dialogue 3 · hospitalisation · 得 / 才",build(){return[
  N("Partie 4. Annie rend visite à Chen Tianzhong, hospitalisé après une douleur soudaine."),
  HC("你怎么突然住院了？大家都很担心你。", "Pourquoi as-tu été hospitalisé si soudainement ? Tout le monde s'inquiète.", .6),
  HC("昨天我的腿突然疼得不能走了，医生说需要住院做检查。", "Hier, ma jambe s'est soudain mise à me faire si mal que je ne pouvais plus marcher. Le médecin a demandé une hospitalisation pour des examens.", .54),
  HC("是不是因为最近运动太多了？", "Est-ce parce que tu as fait trop de sport récemment ?", .64),
  HC("我也不知道，还得做完检查才能知道。", "Je ne sais pas non plus ; il faut terminer les examens avant de le savoir.", .62),
  HC("你很少生病，上次来医院是什么时候？", "Tu es rarement malade. Quand es-tu venu à l'hôpital la dernière fois ?", .6),
  HC("我上次来医院已经是差不多两年前了。", "Ma dernière visite remonte à presque deux ans.", .62),
  HC("别担心，听医生的话，好好休息，你的腿一定能好。", "Ne t'inquiète pas. Suis les conseils du médecin et repose-toi bien ; ta jambe guérira.", .56),
  HC("谢谢。有人来看我，我就开心多了。", "Merci. Quand quelqu'un vient me voir, je me sens beaucoup mieux.", .62),

  N("[[还得|hái děi]] signifie « il faut encore ». 得 se prononce děi lorsqu'il exprime la nécessité."),
  ...h3teach("还得做完检查。", "Il faut encore terminer les examens."),
  N("…才知道 présente une condition préalable : on ne saura qu'après. Cette attente est plus contraignante que 就."),
  ...h3drill("Dites : il faut laisser le médecin examiner avant de savoir.", "还得让医生检查以后才知道。", "Il faut encore attendre l'examen du médecin avant de savoir."),

  N("Compréhension. Pourquoi Chen Tianzhong a-t-il été hospitalisé ?"),
  TH(), HC("因为他的腿突然疼得不能走了。", "Parce que sa jambe s'est soudain mise à lui faire si mal qu'il ne pouvait plus marcher.", .66), HOLD(),
  N("Le médecin connaît-il déjà la cause ?"),
  TH(), HC("还不知道，得做完检查才能知道。", "Pas encore ; il faut terminer les examens pour le savoir.", .66), HOLD(),
  N("Fin de la partie 4. Vous pouvez raconter le motif d'une consultation et comprendre une nécessité médicale simple."),
  ];}},

  {num:5,hanzi:"睡前吃一次",title:"Partie 5 · Comprendre une ordonnance",desc:"Récit · fréquence · avant et après",build(){return[
  N("Partie 5. Chen Tianzhong est rentré chez lui et résume les consignes du médecin."),
  HC("今天我出院了。", "Aujourd'hui, je suis sorti de l'hôpital.", .74),
  HC("出院前，医生给我开了几种药，而且告诉了我吃药的方法。", "Avant ma sortie, le médecin m'a prescrit plusieurs médicaments et expliqué comment les prendre.", .56),
  HC("有一种药需要每天睡前吃一次，其他几种每天吃三次，饭后吃。", "L'un doit être pris une fois par jour avant le coucher ; les autres, trois fois par jour après les repas.", .54),
  HC("除了吃药，医生还说最重要的是多休息。", "En plus des médicaments, le médecin a dit que le plus important était de beaucoup se reposer.", .6),
  HC("我都记在心里了，回家以后一定会多注意。", "J'ai tout bien retenu et je ferai davantage attention à mon retour.", .6),
  HC("希望我的腿能快一点儿好。", "J'espère que ma jambe guérira vite.", .68),

  N("Temps ou événement + 前/以前 signifie avant ; + 后/以后 signifie après. Les formes courtes sont fréquentes avec des habitudes : 睡前, 饭后, 下班后."),
  HC("这种药每天睡前吃一次。", "Ce médicament se prend une fois par jour avant le coucher.", .68),
  HC("其他几种每天饭后吃三次。", "Les autres se prennent trois fois par jour après les repas.", .68),
  HC("考完试以后，咱们一起去旅游吧。", "Après les examens, partons voyager ensemble.", .68),
  ...h3drill("Dites : prenez ce médicament après le petit déjeuner.", "这种药早饭后吃。", "Prenez ce médicament après le petit déjeuner."),
  ...h3drill("Dites : avant de sortir, n'oubliez pas votre médicament.", "出门前别忘了带药。", "Avant de sortir, n'oubliez pas votre médicament."),

  N("Mission d'écoute. Reformulez l'ordonnance : un médicament avant de dormir, les autres après les repas."),
  ...h3drill("Donnez les deux consignes.", "一种药睡前吃，其他几种饭后吃。", "Un médicament se prend avant le coucher ; les autres après les repas."),
  N("Réponse personnelle. Citez une bonne habitude de santé avec 前 ou 后. Modèle :"),
  TH(), HC("我每天晚饭后散步半个小时。", "Je marche une demi-heure après le dîner chaque jour.", .68), HOLD("Répète ce modèle ou donne ta propre habitude, puis ▶"),
  N("Fin de la partie 5. Vous savez comprendre et reformuler une fréquence et un moment de prise."),
  ];}},

  {num:6,hanzi:"综合练习",title:"Partie 6 · Exercices créés",desc:"Symptômes · durée · consignes",exercise:true,build(){return[
  N("Exercices originaux de la leçon 8. Répondez avant la correction."),
  N("Exercice 1. Dites que vous ne voulez pas continuer à grossir."),
  TH(), HC("我不想再胖下去了。", "Je ne veux pas continuer à grossir.", .72), HOLD(),
  N("Exercice 2. Placez la durée dans le mot séparable : j'ai nagé trente minutes."),
  TH(), HC("我游了半个小时泳。", "J'ai nagé une demi-heure.", .72), HOLD(),
  N("Exercice 3. Dites : j'ai un peu de fièvre et mal à l'oreille."),
  TH(), HC("我发低烧了，耳朵也有点儿疼。", "J'ai un peu de fièvre et mal à l'oreille.", .7), HOLD(),
  N("Exercice 4. Action en cours : je suis hospitalisé depuis deux jours."),
  TH(), HC("我住了两天院了。", "Je suis hospitalisé depuis deux jours.", .72), HOLD(),
  N("Exercice 5. Événement terminé : je suis sorti de l'hôpital il y a deux jours."),
  TH(), HC("我出院两天了。", "Je suis sorti de l'hôpital il y a deux jours.", .72), HOLD(),
  N("Exercice 6. Si la fièvre continue cet après-midi, vous irez consulter."),
  TH(), HC("如果下午还发烧，我就去看医生。", "Si j'ai encore de la fièvre cet après-midi, j'irai consulter.", .68), HOLD(),
  N("Exercice 7. Reformulez : ce médicament, une fois avant le coucher."),
  TH(), HC("这种药每天睡前吃一次。", "Ce médicament se prend une fois par jour avant le coucher.", .68), HOLD(),
  N("Exercice 8. Dialogue. Votre ami a l'air malade ; posez deux questions et proposez votre aide."),
  TH(), HC("你怎么了？发烧吗？我陪你去医院检查一下吧。", "Qu'est-ce qui t'arrive ? As-tu de la fièvre ? Je vais t'accompagner à l'hôpital.", .62),
  HC("谢谢，我先休息一下，如果还不舒服就去医院。", "Merci. Je vais d'abord me reposer ; si je ne vais pas mieux, j'irai à l'hôpital.", .64), HOLD(),
  N("Bravo. Vous pouvez parler de santé sans confondre durée de l'état et temps écoulé depuis un événement."),
  HC("好好休息，继续健康地生活下去。", "Reposez-vous bien et continuez à vivre sainement.", .68),
  HC("再见！", "Au revoir !", .74),
  ];}}
  ]});
