/* Nouveau HSK 3.0 · Leçon 9 — 打不好没关系
   Source : « 新HSK教程 3 », leçon 9. Exercices audio originaux. */
registerChapter({group:"hsk3",id:"hsk3-09",badge:9,hanzi:"打不好没关系",
title:"Leçon 9 · S'entraîner et suivre une compétition",desc:"6 cours · 为了 · complément potentiel · 越A越B",
intro:"Vous allez préparer une rencontre sportive, encourager un débutant, commenter un match et présenter un athlète. Les exercices privilégient la capacité réelle à produire une phrase nouvelle, même imparfaite.",lessons:[

{num:1,hanzi:"为了准备运动会",title:"Partie 1 · Se préparer à une compétition",desc:"Dialogue 1 · objectif avec 为了",build(){return[
N("Partie 1. À l'entrée de la bibliothèque, Li Wen rend sa carte de campus à Bai Jiayue."),
HC("家月，对不起，我昨天忘了还你校园卡了。", "Jiayue, désolé, j'ai oublié de te rendre ta carte de campus hier.", .58),
HC("没关系。你怎么这么快就进来了？", "Ce n'est rien. Comment es-tu entré si vite ?", .62),
HC("我正在球场打球呢，接了你的电话就跑过来了。", "Je jouais sur le terrain ; dès que j'ai reçu ton appel, j'ai couru jusqu'ici.", .58),
HC("听说为了准备运动会，你们几个男生每天都练球。", "J'ai entendu dire que plusieurs garçons s'entraînent tous les jours pour préparer la rencontre sportive.", .56),
HC("是啊！你打算参加运动会吗？", "Oui ! Comptes-tu participer à la rencontre ?", .64),
HC("我想参加网球比赛，最近一直在练习。", "Je voudrais participer au tournoi de tennis ; je m'entraîne beaucoup en ce moment.", .62),
HC("好，到时候我去看你的比赛。", "D'accord, j'irai voir ton match le moment venu.", .66),

N("[[为了|wèile]] introduit le but ; l'autre proposition donne l'action entreprise pour l'atteindre."),
HC("为了准备运动会，我们每天都练球。", "Pour préparer la rencontre sportive, nous nous entraînons chaque jour.", .68),
HC("为了考上大学，她每天努力学习。", "Pour entrer à l'université, elle travaille dur chaque jour.", .66),
HC("为了早点儿到家，我打算坐飞机。", "Pour rentrer plus tôt, je compte prendre l'avion.", .68),
...h3drill("Donnez le but : je cours tous les jours pour être en meilleure santé.", "为了更健康，我每天都跑步。", "Pour être en meilleure santé, je cours chaque jour."),
...h3drill("Variez l'action : pour gagner le match, nous allons nous entraîner davantage.", "为了赢得比赛，我们要多练习。", "Pour gagner le match, nous devons nous entraîner davantage."),

N("Réponse personnelle. Quel est votre objectif en apprenant le chinois ? Modèle :"),
TH(),HC("为了跟中国朋友聊天儿，我每天都练习说中文。", "Pour discuter avec des amis chinois, je m'exerce à parler chinois chaque jour.", .66),HOLD("Répète ce modèle ou donne ton propre objectif, puis ▶"),
N("Fin de la partie 1. Vous savez relier une action régulière à son objectif concret."),
];}},

{num:2,hanzi:"打不好没关系",title:"Partie 2 · Encourager un débutant",desc:"Dialogue 2 · possibilité · résultat",build(){return[
N("Partie 2. Li Wen invite Bai Jiayue à jouer au badminton avec le groupe."),
HC("家月，你跟我们一起打羽毛球吧？", "Jiayue, viens jouer au badminton avec nous.", .64),
HC("我好多年没打羽毛球了，几乎忘了怎么打了。", "Cela fait des années que je n'en ai pas fait ; j'ai presque oublié comment jouer.", .58),
HC("没关系，打不好没关系。", "Ce n'est pas grave si tu ne joues pas bien.", .7),
HC("这么多同学一起打，如果总接不住球，就太不好意思了。", "Avec tant de camarades, si je rate toujours le volant, je serai vraiment gênée.", .54),
HC("你想想，大家只是一起练习，不是比赛。", "Réfléchis : tout le monde s'entraîne simplement ensemble ; ce n'est pas une compétition.", .6),
HC("我先自己练练吧，下周再跟你们一起打。", "Je vais d'abord m'entraîner seule ; je jouerai avec vous la semaine prochaine.", .62),
HC("我在教天中打羽毛球，你可以过来跟我们一起练。", "J'apprends le badminton à Tianzhong ; tu peux venir t'entraîner avec nous.", .58),

N("Le complément potentiel insère 得 ou 不 entre le verbe et son résultat : 看得懂 comprendre en lisant ; 看不懂 ne pas réussir à comprendre."),
HC("这本书你看得懂吗？", "Arrives-tu à comprendre ce livre ?", .7),
HC("他说得太快，我听不懂。", "Il parle trop vite ; je n'arrive pas à comprendre.", .68),
HC("门太小，箱子拿不进去。", "La porte est trop étroite ; on ne peut pas faire entrer la valise.", .68),
HC("声音太小，我听不见。", "Le son est trop faible ; je n'entends pas.", .7),
N("Il ne s'agit pas simplement de vouloir ou savoir faire : la situation permet-elle d'atteindre le résultat ?"),
...h3drill("Le texte est facile : je peux le comprendre.", "这个课文我看得懂。", "J'arrive à comprendre ce texte."),
...h3drill("La balle va trop vite : je n'arrive pas à la rattraper.", "球太快了，我接不住。", "La balle va trop vite ; je n'arrive pas à la rattraper."),
...h3drill("Demandez si le devoir peut être terminé en trente minutes.", "半个小时做得完作业吗？", "Peut-on terminer le devoir en une demi-heure ?"),
N("Fin de la partie 2. Vous pouvez parler d'un résultat possible sans décourager le débutant."),
];}},

{num:3,hanzi:"会还是做得到",title:"Partie 3 · Focus intermédiaire sur la capacité",desc:"会 / 能 / complément potentiel",build(){return[
N("Focus intermédiaire. Trois formes françaises se traduisent souvent par « pouvoir », mais le chinois distingue leur logique."),
HC("我会打羽毛球。", "Je sais jouer au badminton.", .72),
N("会 exprime une compétence apprise."),
HC("我今天能打羽毛球。", "Je peux jouer au badminton aujourd'hui.", .72),
N("能 exprime une possibilité générale ou une disponibilité."),
HC("球太快，我接不住。", "La balle va trop vite ; je n'arrive pas à la rattraper.", .72),
N("Le complément potentiel vise le résultat concret dans cette situation."),

N("Vous avez appris la technique : je sais nager."),
...h3drill("Répondez.", "我会游泳。", "Je sais nager."),
N("Votre jambe va mieux : je peux nager aujourd'hui."),
...h3drill("Répondez.", "我的腿好多了，今天能游泳。", "Ma jambe va mieux ; je peux nager aujourd'hui."),
N("L'eau est trop froide : je n'arrive pas à entrer dedans."),
...h3drill("Répondez avec un résultat directionnel.", "水太冷了，我进不去。", "L'eau est trop froide ; je n'arrive pas à y entrer."),
N("Question alternative utile : l'entends-tu ou non ?"),
...h3drill("Posez la question.", "你听得见听不见？", "Est-ce que tu l'entends ou non ?"),
N("Fin du focus. 会 concerne l'apprentissage, 能 la possibilité, 得/不 le résultat atteignable."),
];}},

{num:4,hanzi:"越看越着急",title:"Partie 4 · Regarder un match",desc:"Dialogue 3 · influence · 越A越B",build(){return[
N("Partie 4. Trois amis regardent un match de football à la télévision."),
HC("足球比赛已经开始了，快过来看吧！", "Le match a déjà commencé ; viens vite regarder !", .62),
HC("你们先看，冰箱里有啤酒和饮料，我去拿一下。", "Regardez déjà. Il y a de la bière et des boissons au réfrigérateur ; je vais les chercher.", .58),
HC("今天怎么回事？总是踢不进去！", "Que se passe-t-il aujourd'hui ? Ils n'arrivent jamais à marquer !", .62),
HC("几个老球员生病了，新球员第一次参加这么重要的比赛，太紧张了。", "Plusieurs joueurs expérimentés sont malades. Les nouveaux participent pour la première fois à un match si important ; ils sont trop nerveux.", .54),
HC("是啊，主要的球员没参加比赛，所以大家也都受到影响了。", "Oui. Les joueurs principaux ne participent pas, donc toute l'équipe en subit l'influence.", .56),
HC("越看越着急。我不看了，你们告诉我得分吧。", "Plus je regarde, plus je m'inquiète. J'arrête ; dites-moi le score.", .6),

N("[[越 A 越 B|yuè A yuè B]] signifie que B évolue à mesure que A change. A et B peuvent être des verbes ou des adjectifs."),
HC("我越看越着急。", "Plus je regarde, plus je m'inquiète.", .72),
HC("妈妈越说，他越不高兴。", "Plus sa mère parle, moins il est content.", .68),
HC("这个比赛越看越有意思。", "Plus on regarde ce match, plus il devient intéressant.", .68),
HC("认识的中国朋友越多越好。", "Plus je connais d'amis chinois, mieux c'est.", .68),
...h3drill("Décrivez l'entraînement : plus je joue, mieux je joue.", "我越打越好。", "Plus je joue, mieux je joue."),
...h3drill("Décrivez un texte : plus je lis, mieux je comprends.", "我越看越懂。", "Plus je lis, mieux je comprends."),
...h3drill("Dites : plus il y a de participants, plus c'est intéressant.", "参加的人越多越有意思。", "Plus il y a de participants, plus c'est intéressant."),
N("Fin de la partie 4. Vous savez décrire deux évolutions liées, sans utiliser 越来越."),
];}},

{num:5,hanzi:"让世界认识中国",title:"Partie 5 · Présenter un athlète",desc:"Récit guidé · Jeux olympiques · impact",build(){return[
N("Partie 5. Li Wen prépare une courte présentation sur les Jeux olympiques et Liu Changchun."),
HC("我喜欢看体育比赛，最爱看的就是奥运会。", "J'aime regarder les compétitions sportives ; ce que je préfère, ce sont les Jeux olympiques.", .6),
HC("奥运会是世界上影响最大的体育比赛。", "Les Jeux olympiques sont la compétition sportive qui a le plus d'influence au monde.", .62),
HC("从一八九六年到二零二四年，每次奥运会都有非常多的运动员参加。", "De 1896 à 2024, chaque édition des Jeux a réuni un très grand nombre d'athlètes.", .56),
HC("第一位参加奥运会的中国运动员是刘长春。", "Le premier athlète chinois à participer aux Jeux olympiques fut Liu Changchun.", .6),
HC("他一九三二年参加了一百米和二百米短跑比赛。", "En 1932, il participa aux courses du 100 et du 200 mètres.", .58),
HC("虽然他没有得到好成绩，但是他让世界认识了中国。", "Même s'il n'obtint pas de bon résultat, il fit connaître la Chine au monde.", .58),

N("Compréhension. À quelles épreuves Liu Changchun a-t-il participé ?"),
TH(),HC("他参加了一百米和二百米短跑比赛。", "Il a participé aux courses du 100 et du 200 mètres.", .68),HOLD(),
N("Pourquoi son parcours reste-t-il important malgré le résultat ?"),
TH(),HC("因为他让世界认识了中国。", "Parce qu'il a fait connaître la Chine au monde.", .7),HOLD(),

N("Mission orale. Présentez une sportive ou un sportif que vous connaissez : sport, entraînement, résultat et influence. Modèle bref :"),
TH(),HC("她是一位网球运动员。为了得到好成绩，她每天练习。她让越来越多的人喜欢上了网球。", "C'est une joueuse de tennis. Pour obtenir de bons résultats, elle s'entraîne chaque jour et donne envie à de plus en plus de personnes d'aimer le tennis.", .58),HOLD("Répète ce modèle ou crée ta propre présentation, puis ▶"),
N("Fin de la partie 5. Vous savez présenter une performance sans réduire sa valeur au seul score."),
];}},

{num:6,hanzi:"综合练习",title:"Partie 6 · Exercices créés",desc:"But · potentiel · évolution · commentaire",exercise:true,build(){return[
N("Exercices originaux de la leçon 9. Répondez avant la correction."),
N("Exercice 1. Pour préparer le match, nous nous entraînons chaque soir."),
TH(),HC("为了准备比赛，我们每天晚上都练习。", "Pour préparer le match, nous nous entraînons chaque soir.", .68),HOLD(),
N("Exercice 2. Le texte est trop difficile ; je n'arrive pas à le comprendre."),
TH(),HC("课文太难了，我看不懂。", "Le texte est trop difficile ; je n'arrive pas à le comprendre.", .72),HOLD(),
N("Exercice 3. Demandez si la valise peut entrer."),
TH(),HC("这个行李箱拿得进去吗？", "Peut-on faire entrer cette valise ?", .7),HOLD(),
N("Exercice 4. Encouragez : ce n'est pas grave si tu ne joues pas bien."),
TH(),HC("打不好没关系，慢慢练。", "Ce n'est pas grave si tu ne joues pas bien ; entraîne-toi progressivement.", .72),HOLD(),
N("Exercice 5. Plus elle s'entraîne, plus elle progresse."),
TH(),HC("她越练习，进步越快。", "Plus elle s'entraîne, plus elle progresse vite.", .7),HOLD(),
N("Exercice 6. Plus le match avance, plus je suis nerveux."),
TH(),HC("比赛越往后，我越紧张。", "Plus le match avance, plus je suis nerveux.", .7),HOLD(),
N("Exercice 7. Expliquez pourquoi l'équipe joue mal : les joueurs principaux sont absents."),
TH(),HC("因为主要的球员没参加比赛，大家都受到了影响。", "Comme les joueurs principaux ne participent pas, toute l'équipe est affectée.", .66),HOLD(),
N("Exercice 8. Mini-dialogue : invitez une débutante ; elle craint de rater la balle ; rassurez-la."),
TH(),HC("跟我们一起打羽毛球吧。", "Viens jouer au badminton avec nous.", .72),
HC("我怕接不住球。", "J'ai peur de ne pas réussir à rattraper le volant.", .72),
HC("没关系，我们只是练习，我可以教你。", "Ce n'est pas grave ; nous nous entraînons seulement et je peux t'apprendre.", .68),HOLD(),
N("Bilan des leçons 7 à 9. Vous savez comparer, parler de santé, décrire une possibilité concrète et commenter une évolution."),
HC("为了进步，别怕说不好，越说越自然。", "Pour progresser, n'ayez pas peur de mal parler : plus vous parlerez, plus ce sera naturel.", .68),
HC("再见！", "Au revoir !", .74),
];}}
]});
