/* Nouveau HSK 3.0 · Leçon 10 — 你明天再把书还给我
   Source : « 新HSK教程 3 », leçon 10. Exercices audio originaux. */
registerChapter({group:"hsk3",id:"hsk3-10",badge:10,
  hanzi:"你明天再把书还给我",title:"Leçon 10 · Méthodes de travail et examens",
  desc:"6 cours · 把 et déplacement · 在…上/中/下 · transfert avec 给",
  intro:"Cette leçon vous fait parler de vos méthodes de travail, demander de l'aide après un examen et comprendre le système scolaire chinois. Deux ateliers construisent progressivement les premières phrases avec 把, d'abord pour déplacer un objet, puis pour le transmettre à quelqu'un.",lessons:[

  {num:1,hanzi:"把题记在本子上",title:"Partie 1 · Prendre de bonnes notes",desc:"Dialogue 1 · méthode · 把 + lieu",build(){return[
  N("Partie 1. Une camarade demande à Xiaoxue pourquoi ses résultats en mathématiques progressent."),
  HC("你的数学越来越好，能不能介绍一下学习方法？", "Tu progresses de plus en plus en mathématiques. Peux-tu présenter ta méthode ?", .58),
  HC("没有什么特别的方法，认真听课，认真记笔记。", "Il n'y a pas de méthode particulière : j'écoute attentivement et je prends des notes sérieusement.", .58),
  HC("我看过你的笔记，记得非常清楚。", "J'ai vu tes notes ; elles sont très claires.", .62),
  HC("老师写在黑板上的题都很重要，所以我会把这些题都记在本子上。", "Tous les exercices écrits au tableau sont importants ; je les note donc dans mon cahier.", .52),
  HC("你说得对。我没有记笔记的习惯。", "Tu as raison. Je n'ai pas l'habitude de prendre des notes.", .62),
  HC("复习挺重要的，写作业以前，我都要看一遍笔记。", "Réviser est assez important. Avant mes devoirs, je relis toujours mes notes une fois.", .56),
  HC("这个方法真好！我以后也要认真记笔记，提高成绩。", "Cette méthode est excellente ! Désormais, je prendrai moi aussi des notes sérieusement pour améliorer mes résultats.", .54),

  N("Une première phrase en 把 met en avant un objet défini puis décrit ce qu'on lui fait. Pour un changement de place : sujet + 把 + objet + verbe + 在/到 + lieu."),
  HC("我把这些题记在本子上。", "Je note ces exercices dans mon cahier.", .7),
  HC("老师把作业本放到桌子上了。", "Le professeur a posé les cahiers de devoirs sur la table.", .68),
  HC("我把校园卡放在包里了。", "J'ai mis la carte de campus dans mon sac.", .7),
  N("L'objet doit être identifiable : 这些题, 作业本, 校园卡. La phrase insiste sur le résultat obtenu sur cet objet."),
  ...h3drill("Rangez le livre : je mets ce livre sur le bureau.", "我把这本书放在桌子上。", "Je pose ce livre sur le bureau."),
  ...h3drill("Déplacez les notes : j'ai mis mes notes dans mon sac.", "我把笔记放到包里了。", "J'ai mis mes notes dans mon sac."),
  ...h3drill("Interdiction : tu ne peux pas écrire ton nom ici.", "你不能把名字写在这里。", "Tu ne peux pas écrire ton nom ici."),
  N("Observez l'ordre : 不能 vient avant 把, jamais entre 把 et l'objet."),
  N("Fin de la partie 1. Vous savez dire où vous placez un objet matériel ou une information écrite."),
  ];}},

  {num:2,hanzi:"考试以后问老师",title:"Partie 2 · Après l'examen",desc:"Dialogue 2 · difficulté · domaines avec 在…上",build(){return[
  N("Partie 2. Deux élèves comparent leurs résultats et décident de demander de l'aide."),
  HC("昨天的考试，你考得怎么样？", "Comment s'est passé l'examen d'hier ?", .64),
  HC("我觉得历史有点儿难，你呢？", "J'ai trouvé l'histoire un peu difficile. Et toi ?", .64),
  HC("数学考试我没看清楚要求，做错了好几个题，考得挺差的。", "En mathématiques, je n'ai pas bien lu les consignes ; j'ai raté plusieurs exercices et obtenu un assez mauvais résultat.", .52),
  HC("明天还有考试吗？", "Y a-t-il encore un examen demain ?", .68),
  HC("当然，还有外语考试。别说这么多了，先复习外语吧。", "Bien sûr, il reste l'épreuve de langue étrangère. Arrêtons de parler et révisons-la d'abord.", .56),
  HC("外语作业里有几个问题，我可以问问你吗？", "J'ai quelques problèmes dans le devoir de langue. Puis-je te poser des questions ?", .58),
  HC("当然可以。在学习上，遇到什么问题都可以问我。", "Bien sûr. Pour les études, tu peux me demander tout ce qui te pose problème.", .58),
  HC("不好意思，这几个题我也不会。咱们还是一起去办公室问问李老师吧。", "Désolée, je ne sais pas non plus faire ces exercices. Allons plutôt demander à la professeure Li.", .54),

  N("[[在…上|zài…shàng]] peut délimiter un domaine abstrait : 在学习上 dans les études, 在工作上 au travail, 在生活上 dans la vie quotidienne."),
  HC("在学习上，她常常帮助我。", "Elle m'aide souvent dans mes études.", .7),
  HC("在工作上，他给了我很多帮助。", "Il m'a beaucoup aidé dans mon travail.", .68),
  N("[[在…中|zài…zhōng]] situe une action dans une expérience ou un cadre : 在比赛中, 在旅行中."),
  HC("在比赛中，他得分最高。", "Pendant le match, c'est lui qui a obtenu le meilleur score.", .68),
  HC("在旅行中，我认识了几个新朋友。", "Pendant le voyage, j'ai rencontré quelques nouveaux amis.", .68),
  N("[[在…下|zài…xià]] indique une condition ou une influence : 在老师的帮助下."),
  HC("在老师的帮助下，我的成绩提高得很快。", "Grâce à l'aide du professeur, mes résultats ont vite progressé.", .66),
  ...h3drill("Domaine : dans la vie quotidienne, nous nous aidons.", "在生活上，我们互相帮助。", "Dans la vie quotidienne, nous nous aidons mutuellement."),
  ...h3drill("Cadre : pendant l'examen, j'ai mal lu la consigne.", "在考试中，我没看清楚要求。", "Pendant l'examen, je n'ai pas bien lu la consigne."),
  ...h3drill("Condition : grâce à son influence, je me suis intéressé à l'histoire.", "在她的影响下，我对历史感兴趣了。", "Sous son influence, je me suis intéressé à l'histoire."),
  N("Fin de la partie 2. Vous savez situer un problème dans un domaine, un cadre ou une condition."),
  ];}},

  {num:3,hanzi:"把字句怎么造",title:"Partie 3 · Atelier intermédiaire sur 把",desc:"Objet défini · résultat · négation · ordre",build(){return[
  N("Atelier intermédiaire. Une phrase en 把 répond souvent à « qu'avez-vous fait de cet objet ? ». Trois conditions doivent être réunies."),
  N("Premièrement, l'objet est déjà identifié."),
  HC("请把这本书放在桌子上。", "Mets ce livre sur la table, s'il te plaît.", .7),
  N("Deuxièmement, l'action produit un résultat ou un changement clair."),
  HC("我把门关上了。", "J'ai fermé la porte.", .72),
  N("Troisièmement, le verbe n'est généralement pas laissé seul : il reçoit un lieu, un résultat, une quantité ou un autre complément."),
  HC("我把作业写完了。", "J'ai terminé mes devoirs.", .72),

  N("Ordre des modaux et négations : sujet + 不/没/要/想/能 + 把 + objet + action."),
  HC("我没把护照放在包里。", "Je n'ai pas mis le passeport dans le sac.", .7),
  HC("你要把名字写在这里。", "Tu dois écrire ton nom ici.", .7),
  HC("你不能把车停在门口。", "Tu ne peux pas garer la voiture devant l'entrée.", .7),

  N("Transformation guidée. Phrase neutre : 我放书. Précisez d'abord le livre, puis le résultat et le lieu."),
  ...h3drill("Produisez : j'ai posé ce livre sur la table.", "我把这本书放在桌子上了。", "J'ai posé ce livre sur la table."),
  N("Ajoutez une négation passée avant 把."),
  ...h3drill("Produisez : je n'ai pas mis cette carte dans mon sac.", "我没把这张卡放在包里。", "Je n'ai pas mis cette carte dans mon sac."),
  N("Ajoutez un modal avant 把."),
  ...h3drill("Produisez : peux-tu écrire cette phrase au tableau ?", "你能把这个句子写在黑板上吗？", "Peux-tu écrire cette phrase au tableau ?"),
  N("Quand vous hésitez, vérifiez : objet connu, traitement, résultat. Si le résultat manque, ne forcez pas 把."),
  N("Fin de l'atelier. L'ordre de 把 devient une construction logique, pas une formule à mémoriser isolément."),
  ];}},

  {num:4,hanzi:"把书还给我",title:"Partie 4 · Demander une explication",desc:"Dialogue 3 · transfert · 把…给…",build(){return[
  N("Partie 4. Dans le bureau de la professeure Li, les élèves demandent une nouvelle explication."),
  HC("李老师，书上有几个问题，我们想问问您。", "Professeure Li, nous avons quelques questions sur le livre.", .6),
  HC("书上第五页的这个对话我看不懂，小雪也不明白。", "Je n'arrive pas à comprendre le dialogue de la page cinq ; Xiaoxue non plus.", .58),
  HC("我课上讲过这几句话，再给你们讲一遍。", "J'ai déjà expliqué ces phrases en cours ; je vais vous les réexpliquer une fois.", .58),
  N("La professeure explique les exercices."),
  HC("我终于懂了，这些句子一点儿也不难。", "J'ai enfin compris ; ces phrases ne sont pas du tout difficiles.", .62),
  HC("我也明白了，谢谢您，李老师。", "Moi aussi, j'ai compris. Merci, professeure Li.", .64),
  HC("这本书你们拿回去练习，回家也做一做，明天再把书还给我。", "Emportez ce livre pour vous entraîner chez vous, puis rendez-le-moi demain.", .54),

  N("Avec 把 + objet + verbe + 给 + personne, l'objet identifié est transféré à quelqu'un."),
  HC("你明天再把书还给我。", "Rends-moi le livre demain.", .7),
  HC("我把礼物送给她了。", "Je lui ai offert le cadeau.", .7),
  HC("请把这本书带给老师。", "Apporte ce livre au professeur, s'il te plaît.", .7),
  ...h3drill("Rendez la carte à votre camarade.", "我把校园卡还给同学了。", "J'ai rendu la carte de campus à mon camarade."),
  ...h3drill("Transmettez les notes au professeur.", "请把这些笔记交给老师。", "Remettez ces notes au professeur, s'il vous plaît."),
  ...h3drill("Promesse : je t'enverrai les photos ce soir.", "我晚上把照片发给你。", "Je t'enverrai les photos ce soir."),

  N("Rejouez les rôles. L'élève explique qu'il ne comprend pas une phrase."),
  ...h3drill("Demandez de l'aide.", "这个句子我看不懂，您能再讲一遍吗？", "Je n'arrive pas à comprendre cette phrase ; pouvez-vous la réexpliquer ?"),
  N("Le professeur prête le livre avec une consigne."),
  HC("你先拿回去看，明天再把书还给我。", "Emporte-le d'abord pour le lire et rends-le-moi demain.", .66),
  N("Fin de la partie 4. Vous savez demander une explication et organiser le transfert d'un objet."),
  ];}},

  {num:5,hanzi:"中国的升学体系",title:"Partie 5 · Le parcours scolaire",desc:"Courriel guidé · cause et objectif · comparaison personnelle",build(){return[
  N("Partie 5. Xiaoxue écrit à Bai Jiayue et présente son parcours scolaire."),
  HC("家月姐姐，最近怎么样？忙不忙？", "Grande sœur Jiayue, comment vas-tu ? Es-tu très occupée ?", .64),
  HC("我现在上初中二年级，后年就要考高中了。", "Je suis actuellement en deuxième année de collège et je passerai l'examen d'entrée au lycée dans deux ans.", .58),
  HC("中国一般是小学六年、初中三年、高中三年。", "En Chine, le parcours comprend généralement six ans d'école primaire, trois ans de collège et trois ans de lycée.", .58),
  HC("妈妈说，想考上好大学，就得上一个好高中。", "Maman dit que pour entrer dans une bonne université, il faut fréquenter un bon lycée.", .58),
  HC("为了考上好高中，初中就得有一个不错的成绩，所以我现在非常努力。", "Pour entrer dans un bon lycée, il faut déjà avoir de bons résultats au collège ; je travaille donc beaucoup.", .54),
  HC("在你的影响下，我也开始喜欢拍照了。", "Sous ton influence, j'ai moi aussi commencé à aimer la photographie.", .62),
  HC("下次你再来北京，我给你看看我照的照片。", "La prochaine fois que tu viendras à Pékin, je te montrerai mes photos.", .6),

  N("Compréhension. Combien d'années durent normalement le collège et le lycée en Chine ?"),
  TH(),HC("初中三年，高中三年。", "Trois ans de collège et trois ans de lycée.", .72),HOLD(),
  N("Pourquoi Xiaoxue travaille-t-elle beaucoup maintenant ?"),
  TH(),HC("因为她想考上一个好高中。", "Parce qu'elle veut entrer dans un bon lycée.", .7),HOLD(),

  N("Mission personnelle. Décrivez brièvement votre propre parcours scolaire, puis comparez-le au modèle chinois. Exemple :"),
  TH(),HC("我们国家的学校制度跟中国的不太一样，但是考试也很重要。", "Dans mon pays, le système scolaire est assez différent de celui de la Chine, mais les examens sont également importants.", .62),HOLD("Répète ce modèle ou donne ta propre comparaison, puis ▶"),
  N("Fin de la partie 5. Vous pouvez comprendre un parcours scolaire et relier objectifs, efforts et résultats."),
  ];}},

  {num:6,hanzi:"综合练习",title:"Partie 6 · Exercices créés",desc:"把 · domaines · méthodes d'apprentissage",exercise:true,build(){return[
  N("Exercices originaux de la leçon 10. Répondez avant la correction."),
  N("Exercice 1. Mettez le cahier dans le sac avec 把."),
  TH(),HC("请把本子放在包里。", "Mets le cahier dans le sac, s'il te plaît.", .72),HOLD(),
  N("Exercice 2. Négation : je n'ai pas écrit mon nom ici."),
  TH(),HC("我没把名字写在这里。", "Je n'ai pas écrit mon nom ici.", .72),HOLD(),
  N("Exercice 3. Modal : tu dois poser les devoirs sur le bureau."),
  TH(),HC("你要把作业本放到桌子上。", "Tu dois poser les cahiers de devoirs sur le bureau.", .7),HOLD(),
  N("Exercice 4. Transfert : donnez ce cadeau à votre mère."),
  TH(),HC("请把这个礼物送给你妈妈。", "Offre ce cadeau à ta mère, s'il te plaît.", .7),HOLD(),
  N("Exercice 5. Domaine : dans les études, les notes sont très importantes."),
  TH(),HC("在学习上，笔记非常重要。", "Dans les études, les notes sont très importantes.", .72),HOLD(),
  N("Exercice 6. Cadre : pendant l'examen, lisez clairement les consignes."),
  TH(),HC("在考试中，要看清楚要求。", "Pendant l'examen, il faut bien lire les consignes.", .7),HOLD(),
  N("Exercice 7. Demandez au professeur de réexpliquer une fois."),
  TH(),HC("老师，我没听明白，请您再讲一遍。", "Professeur, je n'ai pas compris ; réexpliquez une fois, s'il vous plaît.", .68),HOLD(),
  N("Exercice 8. Expliquez une méthode complète : notes, révision, devoirs."),
  TH(),HC("我把重要的题记在本子上，写作业以前先复习一遍。", "Je note les exercices importants dans mon cahier et je révise une fois avant mes devoirs.", .66),
  HC("这个方法不但能提高成绩，而且能帮助我记住新知识。", "Cette méthode améliore non seulement mes résultats, mais m'aide aussi à retenir les nouvelles connaissances.", .64),HOLD(),
  N("Bravo. Vous avez construit 把 autour d'un objet défini et d'un résultat clair."),
  HC("把学过的内容用起来，才能真正记住。", "C'est en utilisant ce que l'on a appris qu'on le retient vraiment.", .68),
  HC("再见！", "Au revoir !", .74),
  ];}}
]});
