/* Nouveau HSK 3.0 · Leçon 11 — 看来我没办法解决这个问题
   Source : « 新HSK教程 3 », leçon 11. Exercices audio originaux. */
registerChapter({group:"hsk3",id:"hsk3-11",badge:11,hanzi:"看来我没办法解决这个问题",
title:"Leçon 11 · Réunions, problèmes et choix professionnels",desc:"6 cours · 还是/或者 · 看来 · 把 + résultat · 对…来说",
intro:"Vous allez organiser une réunion, diagnostiquer un problème technique, répartir du travail et réfléchir à un choix professionnel. La grammaire sert ici à choisir, déduire, obtenir un résultat et exprimer un point de vue personnel.",lessons:[

{num:1,hanzi:"还是或者",title:"Partie 1 · Organiser une réunion",desc:"Dialogue 1 · horaire et lieu · choix",build(){return[
N("Partie 1. Wang Yixue et Yang Tongle modifient une réunion parce que le directeur est absent."),
HC("今天下午的会议准备好了吗？", "La réunion de cet après-midi est-elle prête ?", .66),
HC("今天下午经理不在，不开会了。", "Le directeur est absent cet après-midi ; la réunion est annulée.", .68),
HC("那什么时候开会？", "Alors, quand aura-t-elle lieu ?", .7),
HC("后天上午十点，会议地点换到第一会议室。我正要给大家发邮件。", "Après-demain à dix heures. Le lieu est déplacé dans la première salle de réunion. J'allais justement envoyer un courriel à tout le monde.", .54),
HC("开会的时候，我们用会议室的电脑还是自己的笔记本电脑？", "Pendant la réunion, utilisons-nous l'ordinateur de la salle ou notre propre portable ?", .54),
HC("会议室的电脑或者自己的电脑都可以。", "L'ordinateur de la salle ou le vôtre : les deux conviennent.", .62),
HC("那到时候咱们早点儿过去，你帮我把电脑接好吧。", "Alors, allons-y un peu plus tôt ; aide-moi à bien brancher l'ordinateur.", .58),

N("[[还是|háishi]] présente des choix dans une question. [[或者|huòzhě]] relie des possibilités dans une affirmation."),
HC("你坐地铁还是打车？", "Tu prends le métro ou un taxi ?", .72),
HC("你可以坐地铁或者打车。", "Tu peux prendre le métro ou un taxi.", .72),
HC("我们今天、明天还是后天开会？", "Faisons-nous la réunion aujourd'hui, demain ou après-demain ?", .7),
HC("今天或者明天都可以。", "Aujourd'hui ou demain, les deux me conviennent.", .72),
...h3drill("Question : utilisez-vous mon ordinateur ou le vôtre ?", "你用我的电脑还是自己的电脑？", "Utilisez-vous mon ordinateur ou le vôtre ?"),
...h3drill("Réponse ouverte : l'un ou l'autre convient.", "你的电脑或者我的电脑都可以。", "Ton ordinateur ou le mien, les deux conviennent."),
N("Fin de la partie 1. Vous savez demander un choix puis accepter plusieurs options."),
];}},

{num:2,hanzi:"看来没办法",title:"Partie 2 · Un problème technique",desc:"Dialogue 2 · diagnostic · 看来",build(){return[
N("Partie 2. Avant la réunion, l'ordinateur est branché mais ne fonctionne pas correctement."),
HC("电脑接好了吗？", "L'ordinateur est-il bien branché ?", .72),
HC("已经接好了，您开机看看有没有问题。", "Oui, allumez-le pour voir s'il y a un problème.", .66),
HC("现在什么都看不见。", "Pour l'instant, on ne voit rien du tout.", .7),
HC("我检查一下哪里出问题了。您再试一下。", "Je vais vérifier d'où vient le problème. Essayez encore une fois.", .64),
HC("看见了，但是听不见声音。", "L'image apparaît, mais on n'entend aucun son.", .7),
HC("现在呢？", "Et maintenant ?", .76),
HC("听得见声音，但是声音有点儿小，听不清楚。", "On entend, mais le son est un peu faible et manque de clarté.", .64),
HC("看来我没办法解决这个问题，只能找别人来帮帮忙了。", "Apparemment, je n'arrive pas à résoudre ce problème ; il ne reste qu'à demander de l'aide.", .56),

N("[[看来|kànlái]] introduit une conclusion tirée d'indices observés : apparemment, il semble que. Ce n'est pas une simple impression visuelle comme 看起来."),
HC("这么晚了，看来他今天不会来了。", "Il est si tard ; apparemment, il ne viendra pas aujourd'hui.", .68),
HC("外面天阴得很，看来要下雨了。", "Le ciel est très couvert ; on dirait qu'il va pleuvoir.", .68),
HC("电梯坏了，看来我们只能走上去了。", "L'ascenseur est en panne ; apparemment, nous devons monter à pied.", .68),
...h3drill("Vous appelez sans réponse : apparemment, il est occupé.", "他一直没接电话，看来很忙。", "Il ne répond pas ; apparemment, il est très occupé."),
...h3drill("L'écran fonctionne mais pas le son : apparemment, le problème vient des haut-parleurs.", "画面没问题，看来是声音出了问题。", "L'image fonctionne ; apparemment, le problème vient du son."),

N("Mission pratique. Expliquez que vous entendez le son, mais pas clairement."),
...h3drill("Signalez le problème.", "我听得见声音，但是听不清楚。", "J'entends le son, mais pas clairement."),
N("Fin de la partie 2. Vous savez distinguer l'observation, le diagnostic et la conclusion."),
];}},

{num:3,hanzi:"看起来还是看来",title:"Partie 3 · Focus intermédiaire sur l'inférence",desc:"看起来 · 看来 · 好像 · conclusion",build(){return[
N("Focus intermédiaire. Trois expressions françaises ressemblent à « il semble », mais leur point de départ diffère."),
HC("他看起来很累。", "Il a l'air fatigué.", .72),
N("看起来 décrit une apparence perceptible."),
HC("他好像很累。", "Il semble fatigué.", .72),
N("好像 indique une impression incertaine, sans nécessairement expliciter le raisonnement."),
HC("他一直在打哈欠，看来很累。", "Il bâille sans arrêt ; il est donc manifestement fatigué.", .7),
N("看来 conclut à partir d'un indice ou d'une analyse."),

N("Choisissez l'apparence : cette candidate a l'air très jeune."),
...h3drill("Répondez.", "这位应聘者看起来很年轻。", "Cette candidate a l'air très jeune."),
N("Choisissez l'incertitude : il me semble que la réunion est demain."),
...h3drill("Répondez.", "会议好像是明天。", "Il me semble que la réunion est demain."),
N("Choisissez la conclusion : toutes les salles sont occupées ; apparemment, il faut reporter."),
...h3drill("Répondez.", "会议室都有人，看来只能改时间了。", "Toutes les salles sont occupées ; apparemment, il faut changer l'horaire."),
N("Ajoutez une solution : essayons d'abord, puis demandons de l'aide si cela ne marche pas."),
...h3drill("Formulez le plan.", "我们先试一下，如果解决不了，就找同事帮忙。", "Essayons d'abord ; si nous ne pouvons pas résoudre le problème, demandons de l'aide à un collègue."),
N("Fin du focus. 看来 transforme des indices en conclusion explicite."),
];}},

{num:4,hanzi:"把工作做完",title:"Partie 4 · Répartir le travail",desc:"Dialogue 3 · congés · 把 + résultat",build(){return[
N("Partie 4. Plusieurs collègues sont absents et Wang Yixue craint de ne pas finir à temps."),
HC("同乐，你看见老张了吗？", "Tongle, as-tu vu Lao Zhang ?", .68),
HC("老张请假了，他说家里有点儿事。", "Lao Zhang a pris congé ; il a quelque chose à régler chez lui.", .66),
HC("好几个同事都休假了，开会前这么多工作我怕干不完。", "Plusieurs collègues sont en congé ; j'ai peur de ne pas terminer tout ce travail avant la réunion.", .56),
HC("十二点多了，咱们先去吃饭吧。吃完饭，我跟您一起把这些工作做完。", "Il est plus de midi. Allons d'abord manger ; après, je finirai ce travail avec vous.", .54),
HC("你先去吃，我想再干一会儿。明天开会前要发到公司的邮箱里。", "Va manger d'abord ; je veux travailler encore un peu. Il faut tout envoyer à la boîte de l'entreprise avant la réunion de demain.", .52),
HC("你没看到邮件吗？经理还没回来呢，下周才能开会。", "Tu n'as pas vu le courriel ? Le directeur n'est pas encore revenu ; la réunion n'aura lieu que la semaine prochaine.", .56),
HC("那不着急了。走，吃饭去。", "Alors, ce n'est plus urgent. Allons manger.", .68),

N("把 + objet + verbe + complément de résultat indique l'effet obtenu sur un objet défini."),
HC("我们把这些工作做完。", "Nous terminons ce travail.", .72),
HC("妈妈把衣服洗干净了。", "Maman a lavé les vêtements jusqu'à ce qu'ils soient propres.", .7),
HC("他还没把笔记本电脑接好。", "Il n'a pas encore correctement branché l'ordinateur portable.", .68),
...h3drill("Résultat 完 : j'ai fini d'écrire le courriel.", "我把邮件写完了。", "J'ai terminé le courriel."),
...h3drill("Résultat 好 : branchez l'ordinateur avant la réunion.", "开会前请把电脑接好。", "Branchez correctement l'ordinateur avant la réunion."),
...h3drill("Résultat 清楚 : expliquez clairement ce problème.", "请把这个问题讲清楚。", "Expliquez clairement ce problème, s'il vous plaît."),
N("Fin de la partie 4. Vous savez préciser non seulement l'action, mais le résultat attendu."),
];}},

{num:5,hanzi:"对我来说",title:"Partie 5 · Travail ou vie familiale",desc:"Journal guidé · choix de carrière · point de vue",build(){return[
N("Partie 5. Wang Yixue réfléchit à une proposition de travail à Shanghai."),
HC("前几天，上海的同事来北京了。", "Il y a quelques jours, des collègues de Shanghai sont venus à Pékin.", .66),
HC("一起吃饭时，他们说最近有不少同事去上海工作了，问我愿意不愿意也去上海。", "Pendant le repas, ils m'ont dit que beaucoup de collègues partaient travailler à Shanghai et m'ont demandé si j'accepterais d'y aller.", .5),
HC("现在丈夫和孩子都在北京，刘明的工作很忙，小雪和小明也还小。", "Mon mari et mes enfants vivent à Pékin ; Liu Ming travaille beaucoup et les enfants sont encore jeunes.", .54),
HC("我去别的城市工作就要离开他们。", "Si je vais travailler dans une autre ville, je devrai les quitter.", .62),
HC("虽然去上海可能会有更好的机会，但是对我来说，生活也很重要。", "Même si Shanghai offre peut-être de meilleures possibilités, ma vie personnelle est également très importante pour moi.", .56),
HC("我不愿意为工作或者学习离开家人。", "Je ne souhaite pas quitter ma famille pour le travail ou les études.", .62),

N("[[对…来说|duì…láishuō]] attribue un point de vue ou une situation à une personne ou un groupe."),
HC("对我来说，家人比工作更重要。", "Pour moi, la famille est plus importante que le travail.", .7),
HC("对孩子来说，玩儿也是一种学习。", "Pour les enfants, jouer est aussi une forme d'apprentissage.", .68),
HC("对年轻人来说，工作机会很重要。", "Pour les jeunes, les possibilités professionnelles sont importantes.", .68),

N("Compréhension. Quel avantage Shanghai pourrait-il offrir ?"),
TH(),HC("去上海可能会有更好的工作机会。", "Shanghai pourrait offrir de meilleures possibilités professionnelles.", .68),HOLD(),
N("Pourquoi Wang Yixue ne veut-elle pas partir ?"),
TH(),HC("因为对她来说，家人和生活也很重要。", "Parce que, pour elle, la famille et la vie personnelle sont également importantes.", .68),HOLD(),
N("Réponse personnelle. Quel aspect compte le plus pour choisir un travail ? Modèle :"),
TH(),HC("对我来说，同事、时间和工作内容都很重要。", "Pour moi, les collègues, les horaires et le contenu du travail sont tous importants.", .68),HOLD("Répète ce modèle ou donne tes propres critères, puis ▶"),
N("Fin de la partie 5. Vous savez exprimer une préférence professionnelle sans présenter votre avis comme universel."),
];}},

{num:6,hanzi:"综合练习",title:"Partie 6 · Exercices créés",desc:"Choix · diagnostic · résultat · opinion",exercise:true,build(){return[
N("Exercices originaux de la leçon 11. Répondez avant la correction."),
N("Exercice 1. Question : réunion aujourd'hui ou demain ?"),
TH(),HC("会议今天开还是明天开？", "La réunion a-t-elle lieu aujourd'hui ou demain ?", .72),HOLD(),
N("Exercice 2. Affirmation : aujourd'hui ou demain, les deux conviennent."),
TH(),HC("今天或者明天都可以。", "Aujourd'hui ou demain, les deux conviennent.", .72),HOLD(),
N("Exercice 3. Il est très tard ; apparemment, le directeur ne viendra pas."),
TH(),HC("已经很晚了，看来经理不会来了。", "Il est très tard ; apparemment, le directeur ne viendra pas.", .7),HOLD(),
N("Exercice 4. Finissez le rapport avec 把 et 完."),
TH(),HC("请把这个报告写完。", "Terminez ce rapport, s'il vous plaît.", .72),HOLD(),
N("Exercice 5. Dites que vous n'avez pas encore correctement branché l'ordinateur."),
TH(),HC("我还没把电脑接好。", "Je n'ai pas encore correctement branché l'ordinateur.", .72),HOLD(),
N("Exercice 6. Pour moi, le temps libre est plus important que le salaire."),
TH(),HC("对我来说，休息时间比工资更重要。", "Pour moi, le temps libre est plus important que le salaire.", .7),HOLD(),
N("Exercice 7. Diagnostiquez : l'image fonctionne mais il n'y a pas de son ; il faut demander de l'aide."),
TH(),HC("画面看得见，但是听不见声音。看来只能找别人帮忙了。", "L'image apparaît mais il n'y a pas de son ; apparemment, il faut demander de l'aide.", .64),HOLD(),
N("Exercice 8. Refusez poliment un poste dans une autre ville et donnez votre raison."),
TH(),HC("谢谢您给我这个机会，但是我不愿意离开家人。对我来说，生活也很重要。", "Merci pour cette proposition, mais je ne souhaite pas quitter ma famille. Ma vie personnelle compte aussi pour moi.", .6),HOLD(),
N("Bravo. Vous pouvez organiser, diagnostiquer, collaborer et expliquer une décision professionnelle."),
HC("解决不了的问题，可以一起想办法。", "Pour un problème qu'on ne peut pas résoudre seul, on peut chercher une solution ensemble.", .68),
HC("再见！", "Au revoir !", .74),
];}}
]});
