/* Nouveau HSK 3.0 · Leçon 12 — 这个季节天气变化很快
   Source : « 新HSK教程 3 », leçon 12. Exercices audio originaux. */
registerChapter({group:"hsk3",id:"hsk3-12",badge:12,hanzi:"这个季节天气变化很快",
title:"Leçon 12 · Météo, climat et saisons",desc:"6 cours · 或者…或者… · 起来 · 就 restrictif · 下来",
intro:"Cette leçon vous fait organiser une sortie selon la météo, réagir à un changement soudain et décrire le climat d'une ville. Les ateliers distinguent plusieurs emplois de 就 et trois compléments directionnels employés au sens abstrait.",lessons:[

{num:1,hanzi:"或者明天或者后天",title:"Partie 1 · Choisir le jour d'une sortie",desc:"Dialogue 1 · parc · alternative",build(){return[
N("Partie 1. Les arbres fleurissent et deux amies veulent aller au parc."),
HC("王老师，您看，这条街上的树都开花了。", "Professeure Wang, regardez : les arbres de cette rue sont tous en fleurs.", .58),
HC("上个星期就可以去公园坐船了，公园里的花也开了。", "Depuis la semaine dernière, on peut faire du bateau dans le parc ; les fleurs y sont aussi ouvertes.", .56),
HC("天气这么好，下午我也想去公园坐船。", "Il fait si beau que j'aimerais moi aussi aller faire du bateau cet après-midi.", .6),
HC("去吧！今天是工作日，人应该不多。", "Vas-y ! C'est un jour de semaine ; il ne devrait pas y avoir trop de monde.", .62),
HC("您有时间吗？我想跟您一起去。", "Avez-vous le temps ? J'aimerais y aller avec vous.", .64),
HC("我今天下午有课，不能去太远的地方。", "J'ai cours cet après-midi ; je ne peux pas aller trop loin.", .62),
HC("那咱们换一天去？", "Alors, si nous changions de jour ?", .7),
HC("或者明天去，或者后天去，我给你打电话。", "Nous irons demain ou après-demain ; je t'appellerai.", .64),

N("La structure [[或者…或者…|huòzhě…huòzhě…]] énumère plusieurs options possibles dans une affirmation ou une réflexion."),
HC("我们或者今天去，或者明天去。", "Nous irons soit aujourd'hui, soit demain.", .7),
HC("晚饭或者吃中国菜，或者吃日本菜。", "Pour le dîner, nous mangerons soit chinois, soit japonais.", .68),
N("Pour demander à l'interlocuteur de choisir, 还是 reste plus naturel : 今天去还是明天去？"),
...h3drill("Demandez : allons-nous au parc ou au musée ?", "我们去公园还是去博物馆？", "Allons-nous au parc ou au musée ?"),
...h3drill("Présentez vos deux possibilités : soit le parc, soit le musée.", "我们或者去公园，或者去博物馆。", "Nous irons soit au parc, soit au musée."),
N("Fin de la partie 1. Vous savez distinguer une question à choix d'une liste de possibilités."),
];}},

{num:2,hanzi:"雨下起来了",title:"Partie 2 · Le temps change soudainement",desc:"Dialogue 2 · pluie · début avec 起来",build(){return[
N("Partie 2. Pendant la promenade, le beau temps disparaît très vite."),
HC("刚才还是大晴天呢，怎么突然就刮起风来了？", "Il y a un instant, le ciel était encore parfaitement dégagé. Pourquoi le vent s'est-il soudain levé ?", .56),
HC("好像新闻里说今天有雨。", "Il me semble que la météo annonçait de la pluie aujourd'hui.", .66),
HC("啊？我每天书包里都放着雨伞，就今天没带。", "Ah bon ? J'ai un parapluie dans mon sac tous les jours ; aujourd'hui est justement le seul jour où je ne l'ai pas.", .58),
HC("我可以借给你，我车里有一把伞和一件雨衣。", "Je peux t'en prêter un. J'ai un parapluie et un imperméable dans la voiture.", .6),
HC("谢谢，希望下午天气能变好。", "Merci. J'espère que le temps s'améliorera cet après-midi.", .64),
HC("这个季节天气变化很快。", "À cette saison, le temps change très vite.", .68),
HC("雨已经下起来了，咱们快点儿走吧。", "La pluie a commencé ; marchons plus vite.", .64),

N("Le complément [[起来|qǐlái]] marque le début d'une action ou l'entrée dans un nouvel état."),
HC("雨下起来了。", "Il s'est mis à pleuvoir.", .74),
HC("最近天气热起来了。", "Ces derniers temps, le temps s'est mis à se réchauffer.", .7),
HC("突然刮起风来了。", "Le vent s'est soudain levé.", .72),
HC("大家听了都笑起来了。", "En entendant cela, tout le monde s'est mis à rire.", .7),
N("Avec un objet, celui-ci s'insère souvent entre 起 et 来 : 刮起风来."),
...h3drill("Début d'un état : le ciel s'est assombri.", "天暗起来了。", "Le ciel s'est assombri."),
...h3drill("Début d'une action : les enfants se sont mis à chanter.", "孩子们唱起来了。", "Les enfants se sont mis à chanter."),
...h3drill("Avec un objet : il s'est mis à neiger.", "下起雪来了。", "Il s'est mis à neiger."),
N("Fin de la partie 2. Vous savez annoncer le moment précis où une situation commence à changer."),
];}},

{num:3,hanzi:"就的三个意思",title:"Partie 3 · Focus intermédiaire sur 就",desc:"Rapidité · conséquence · quantité faible / exception",build(){return[
N("Focus intermédiaire. Vous avez déjà entendu 就 dans plusieurs constructions. Comparons trois raisonnements."),
N("Premier sens : tôt, vite ou facilement."),
HC("走路十分钟就到了。", "Dix minutes à pied ont suffi pour arriver.", .72),
N("Deuxième sens : conséquence d'une condition."),
HC("如果下雨，我们就不去公园。", "S'il pleut, nous n'irons pas au parc.", .7),
N("Troisième sens : restriction jugée faible, ou exception unique."),
HC("今年就下了一次雪。", "Il n'a neigé qu'une fois cette année.", .72),
HC("我每天都带雨伞，就今天没带。", "J'emporte un parapluie tous les jours, sauf aujourd'hui.", .7),

N("Quantité faible : il n'a lu que dix minutes hier."),
...h3drill("Répondez.", "他昨天就看了十分钟书。", "Il n'a lu que dix minutes hier."),
N("Exception : tout le monde a réussi, sauf moi."),
...h3drill("Répondez.", "大家都考得很好，就我没考好。", "Tout le monde a réussi, sauf moi."),
N("Rapidité : il est arrivé dès huit heures."),
...h3drill("Répondez.", "他八点就到了。", "Il est arrivé dès huit heures."),
N("Condition : s'il fait beau, nous irons faire du bateau."),
...h3drill("Répondez.", "如果天气好，我们就去坐船。", "S'il fait beau, nous irons faire du bateau."),
N("Fin du focus. Le contexte indique si 就 réduit une quantité, accélère un moment ou introduit une conséquence."),
];}},

{num:4,hanzi:"今年就下了一次",title:"Partie 4 · S'habituer au climat",desc:"Dialogue 3 · hiver · 就 restrictif",build(){return[
N("Partie 4. Les deux amies s'abritent de la pluie et parlent du climat local."),
HC("您来这里已经一年多了，习惯了吧？", "Vous vivez ici depuis plus d'un an ; vous vous êtes habituée, n'est-ce pas ?", .6),
HC("别的早就习惯了，就是天气我还不太习惯。", "Je me suis habituée à tout le reste depuis longtemps ; seul le climat me pose encore problème.", .58),
HC("为什么？您不喜欢这里的天气？", "Pourquoi ? Vous n'aimez pas le climat d'ici ?", .64),
HC("我觉得冬天太冷了。", "Je trouve l'hiver trop froid.", .7),
HC("冬天虽然冷，但是下雪的时候特别漂亮。", "Même si l'hiver est froid, c'est particulièrement beau lorsqu'il neige.", .62),
HC("我也喜欢雪。北京常常下雪，但听说今年就下了一次。", "J'aime aussi la neige. Il neige souvent à Pékin, mais il paraît que cette année, il n'a neigé qu'une seule fois.", .58),
HC("新闻里说，今年冬天很多地方雪下得都少了。", "Les informations disent que cet hiver, il a moins neigé dans beaucoup de régions.", .6),

N("[[就是|jiùshì]] dans 别的都习惯了，就是天气… is proche de « seulement, sauf que ». Il isole le point qui résiste."),
...h3drill("Dites : je me suis habitué à tout, sauf à l'hiver.", "别的我都习惯了，就是冬天还不习惯。", "Je me suis habitué à tout, sauf à l'hiver."),
N("Compréhension. À quoi Wang Yifei ne s'est-elle pas encore habituée ?"),
TH(),HC("她还不太习惯这里的天气。", "Elle ne s'est pas encore habituée au climat local.", .7),HOLD(),
N("Pourquoi Bai Jiayue aime-t-elle l'hiver ?"),
TH(),HC("因为下雪的时候特别漂亮。", "Parce que c'est particulièrement beau lorsqu'il neige.", .7),HOLD(),

N("Variation. Parlez d'un climat que vous connaissez : il pleut souvent, mais cette année, seulement deux fois."),
...h3drill("Construisez la phrase.", "这里常常下雨，但是今年就下了两次。", "Il pleut souvent ici, mais cette année, il n'a plu que deux fois."),
N("Fin de la partie 4. Vous pouvez opposer une habitude climatique à une exception mesurée."),
];}},

{num:5,hanzi:"四季住下来",title:"Partie 5 · Décrire les quatre saisons",desc:"Journal · 不A不B · accomplissement avec 下来",build(){return[
N("Partie 5. Après plus d'un an ailleurs, Wang Yifei compare les saisons à celles de Pékin."),
HC("我离开北京到这里工作一年多了。", "Cela fait plus d'un an que j'ai quitté Pékin pour travailler ici.", .62),
HC("这一年多住下来，我还是更喜欢北京的四季。", "Après avoir vécu ici plus d'un an, je préfère toujours les quatre saisons de Pékin.", .6),
HC("北京的春天最舒服，天气不冷不热。", "Le printemps pékinois est le plus agréable : il ne fait ni froid ni chaud.", .64),
HC("夏天白天很热，但是晚上比较凉快。", "En été, les journées sont très chaudes, mais les soirées plutôt fraîches.", .62),
HC("秋天叶子变成了红色、黄色，非常漂亮。", "En automne, les feuilles deviennent rouges et jaunes ; c'est très beau.", .62),
HC("冬天不但冷，而且风很大，我最不喜欢冬天。", "L'hiver est non seulement froid, mais aussi très venteux ; c'est la saison que j'aime le moins.", .58),

N("[[不 A 不 B|bù A bù B]] place une qualité entre deux extrêmes : 不冷不热, ni froid ni chaud ; 不大不小, ni grand ni petit, juste comme il faut."),
HC("今天不冷不热，很舒服。", "Aujourd'hui, il ne fait ni froid ni chaud ; c'est agréable.", .7),
HC("这个房间不大不小，很合适。", "Cette pièce n'est ni grande ni petite ; sa taille convient.", .7),

N("Le complément [[下来|xiàlái]] peut présenter l'accomplissement d'une action longue ou difficile, avec le bilan obtenu après coup."),
HC("这一年住下来，我已经习惯了。", "Après avoir vécu ici un an, je me suis habitué.", .68),
HC("这半年练下来，他的水平提高了不少。", "Après six mois d'entraînement soutenu, son niveau a beaucoup progressé.", .66),
HC("五千米的比赛，我终于跑下来了。", "J'ai finalement réussi à aller au bout de la course de cinq kilomètres.", .68),
...h3drill("Bilan d'effort : après un mois de lecture, j'ai enfin terminé ce livre.", "这本书我读了一个月，终于读下来了。", "Après un mois, j'ai finalement réussi à terminer ce livre."),

N("Réponse personnelle. Décrivez votre saison préférée avec deux caractéristiques. Modèle :"),
TH(),HC("我最喜欢秋天，因为天气不冷不热，树叶也很漂亮。", "Je préfère l'automne parce qu'il ne fait ni froid ni chaud et que les feuilles sont belles.", .64),HOLD("Répète ce modèle ou décris ta saison préférée, puis ▶"),
N("Fin de la partie 5. Vous savez présenter un climat, une préférence et le bilan d'une longue expérience."),
];}},

{num:6,hanzi:"综合练习",title:"Partie 6 · Exercices créés",desc:"Alternatives · changements · portée de 就 · climat",exercise:true,build(){return[
N("Exercices originaux de la leçon 12. Répondez avant la correction."),
N("Exercice 1. Proposez deux possibilités : soit demain, soit après-demain."),
TH(),HC("我们或者明天去，或者后天去。", "Nous irons soit demain, soit après-demain.", .72),HOLD(),
N("Exercice 2. Le vent s'est soudain levé."),
TH(),HC("突然刮起风来了。", "Le vent s'est soudain levé.", .72),HOLD(),
N("Exercice 3. Le temps commence à se réchauffer."),
TH(),HC("天气开始热起来了。", "Le temps commence à se réchauffer.", .72),HOLD(),
N("Exercice 4. Quantité faible : ce mois-ci, il n'a plu qu'une fois."),
TH(),HC("这个月就下了一次雨。", "Il n'a plu qu'une fois ce mois-ci.", .72),HOLD(),
N("Exercice 5. Exception : j'ai mon téléphone tous les jours, sauf aujourd'hui."),
TH(),HC("我每天都带手机，就今天没带。", "J'emporte mon téléphone tous les jours, sauf aujourd'hui.", .72),HOLD(),
N("Exercice 6. Température modérée : il ne fait ni chaud ni froid."),
TH(),HC("天气不冷不热，很舒服。", "Il ne fait ni chaud ni froid ; c'est agréable.", .72),HOLD(),
N("Exercice 7. Après deux ans de vie ici, vous vous êtes habitué au climat."),
TH(),HC("这两年住下来，我已经习惯这里的天气了。", "Après deux ans ici, je me suis habitué au climat.", .68),HOLD(),
N("Exercice 8. Mini-bulletin : le ciel s'assombrit, le vent se lève ; prenez un parapluie."),
TH(),HC("天暗起来了，也刮起风来了，看来要下雨。出门别忘了带伞。", "Le ciel s'assombrit et le vent se lève ; il va apparemment pleuvoir. N'oubliez pas votre parapluie.", .62),HOLD(),
N("Bilan des leçons 10 à 12. Vous savez structurer 把, déduire avec 看来 et parler d'un climat changeant."),
HC("天气变化得快，表达也要选得准。", "Le temps change vite ; il faut aussi choisir ses expressions avec précision.", .7),
HC("再见！", "Au revoir !", .74),
];}}
]});
