/* Nouveau HSK 3.0 · Leçon 13 — 我的新邻居来自英国
   Source : « 新HSK教程 3 », leçon 13. Exercices audio originaux. */
registerChapter({group:"hsk3",id:"hsk3-13",badge:13,hanzi:"我的新邻居来自英国",
title:"Leçon 13 · Inviter, recevoir et découvrir ses voisins",desc:"6 cours · …的话就… · 把 + direction/état · 一边…一边…",
intro:"Vous allez inviter des collègues, préparer une réception, offrir un cadeau et comparer des habitudes culturelles. Les mises en situation insistent sur les formules réellement utiles quand on reçoit ou quand on est invité.",lessons:[

{num:1,hanzi:"有时间的话就来",title:"Partie 1 · Inviter à dîner",desc:"Dialogue 1 · spécialités régionales · condition orale",build(){return[
N("Partie 1. Yang Tongle invite ses collègues dans un restaurant de cuisine du Sud."),
HC("今天我请客，你们想吃什么就点什么！", "Aujourd'hui, c'est moi qui invite ; commandez ce que vous voulez !", .62),
HC("那我就不客气了。听说这家饭馆的鱼做得很特别？", "Alors, je ne vais pas me gêner. Il paraît que ce restaurant prépare le poisson d'une façon particulière ?", .58),
HC("对，南方菜跟你们北方菜的做法不同。除了鱼，你们还想吃什么？", "Oui, la cuisine du Sud se prépare différemment de celle du Nord. À part le poisson, que souhaitez-vous ?", .54),
HC("我不常吃南方菜，还是你决定吧。", "Je mange rarement de la cuisine du Sud ; décide plutôt toi-même.", .64),
HC("好，那再加一道鸡肉。", "D'accord, ajoutons aussi un plat de poulet.", .68),
HC("咱们就三个人，别点那么多。", "Nous ne sommes que trois ; n'en commande pas autant.", .68),
HC("对了，下周我儿子过生日。你们有时间的话，就来我家做客，我给你们做北京菜。", "Au fait, mon fils fête son anniversaire la semaine prochaine. Si vous avez le temps, venez chez moi ; je vous préparerai des plats pékinois.", .52),

N("À l'oral, condition + [[的话|dehuà]], 就 + résultat signifie « si…, alors… ». 的话 vient à la fin de toute la condition."),
HC("你有时间的话，就来我家做客。", "Si tu as le temps, viens chez moi.", .7),
HC("你觉得满意的话，咱们就买。", "Si cela te convient, nous l'achetons.", .7),
HC("明天天气好的话，我就去爬山。", "S'il fait beau demain, j'irai en randonnée.", .68),
...h3drill("Invitez : si tu es libre samedi, viens dîner chez moi.", "星期六有时间的话，就来我家吃饭吧。", "Si tu es libre samedi, viens dîner chez moi."),
...h3drill("Décidez : si tout le monde aime le poisson, nous en commandons.", "大家喜欢吃鱼的话，我们就点一道鱼。", "Si tout le monde aime le poisson, nous en commandons un."),

N("Formules sociales : [[我请客|wǒ qǐngkè]], c'est moi qui invite ; [[不客气|bú kèqi]], de rien ; [[我就不客气了|wǒ jiù bú kèqi le]], alors j'accepte volontiers."),
...h3drill("Acceptez naturellement l'invitation.", "好啊，那我就不客气了。", "Avec plaisir ; alors j'accepte volontiers."),
N("Fin de la partie 1. Vous savez inviter, accepter et poser une condition de façon orale."),
];}},

{num:2,hanzi:"把饮料放进冰箱",title:"Partie 2 · Préparer l'arrivée des invités",desc:"Dialogue 2 · rangement · 把 + direction/état",build(){return[
N("Partie 2. Wang Yixue et Liu Ming vérifient les derniers préparatifs."),
HC("第一次请新邻居来做客，总是担心有什么没准备好。", "C'est la première fois que nous recevons les nouveaux voisins ; j'ai toujours peur d'avoir oublié quelque chose.", .56),
HC("放心吧，我帮你看了，都已经准备好了。", "Rassure-toi, j'ai vérifié ; tout est prêt.", .62),
HC("我记得刚才已经把饮料拿出来了，怎么不见了？", "Je me souviens avoir sorti les boissons ; où sont-elles passées ?", .58),
HC("我把饮料和酒都放进冰箱里了，客人来了再拿出来。", "J'ai remis les boissons et l'alcool dans le réfrigérateur ; nous les sortirons à l'arrivée des invités.", .56),
HC("你把声音开得太大了，我去调小一点儿。", "Tu as mis le son trop fort ; je vais le baisser un peu.", .6),
HC("好，那我们就等客人来吧。", "D'accord ; attendons les invités.", .68),

N("Avec 把, un complément directionnel indique le déplacement obtenu : 拿出来 sortir, 放进去 mettre à l'intérieur, 带过来 apporter ici."),
HC("我把饮料拿出来了。", "J'ai sorti les boissons.", .72),
HC("我把酒放进冰箱里了。", "J'ai mis l'alcool dans le réfrigérateur.", .72),
HC("请把盘子拿过来。", "Apportez les assiettes ici, s'il vous plaît.", .72),
N("Un complément d'état indique le nouvel état : 把声音开得太大, 把字写得太小."),
HC("你把声音开得太大了。", "Tu as mis le son trop fort.", .72),
HC("你把字写得太小了。", "Tu as écrit les caractères trop petits.", .72),
...h3drill("Déplacement : mettez les fruits sur la table.", "请把水果放到桌子上。", "Mettez les fruits sur la table, s'il vous plaît."),
...h3drill("Direction : sortez le gâteau du réfrigérateur.", "请把蛋糕从冰箱里拿出来。", "Sortez le gâteau du réfrigérateur, s'il vous plaît."),
...h3drill("État : vous avez réglé la musique trop bas.", "你把音乐开得太小了。", "Tu as mis la musique trop bas."),
N("Fin de la partie 2. Vous savez décrire le déplacement ou le changement d'état provoqué sur un objet."),
];}},

{num:3,hanzi:"怎么说才礼貌",title:"Partie 3 · Focus intermédiaire de politesse",desc:"Inviter · remercier · complimenter · répondre",build(){return[
N("Focus intermédiaire. Une réception réussie repose autant sur les formules que sur la grammaire."),
N("L'hôte accueille et souhaite une bonne soirée."),
HC("欢迎来我家，希望大家今晚玩儿得开心。", "Bienvenue chez moi ; j'espère que vous passerez une excellente soirée.", .66),
N("L'invité remercie sans exagérer."),
HC("谢谢你们请我来做客。", "Merci de m'avoir invité chez vous.", .7),
N("Pour offrir un cadeau, dites ce que vous avez préparé et formulez un souhait."),
HC("我准备了一个小礼物，希望你喜欢。", "J'ai préparé un petit cadeau ; j'espère qu'il te plaira.", .68),
N("Pour recevoir un compliment, 别客气 ou 谢谢 suffit ; évitez une longue auto-dépréciation traduite du français."),
HC("你做的菜特别好吃。", "Les plats que tu as préparés sont délicieux.", .72),
HC("谢谢，喜欢的话就多吃一点儿。", "Merci ; si cela te plaît, reprends-en un peu.", .7),

N("Situation 1. Vous arrivez avec un cadeau."),
...h3drill("Souhaitez un joyeux anniversaire et offrez-le.", "生日快乐！这是给你准备的小礼物。", "Joyeux anniversaire ! Voici un petit cadeau pour toi."),
N("Situation 2. L'hôte vous sert un plat inconnu."),
...h3drill("Complimentez après l'avoir goûté.", "这个菜做得很特别，也很好吃。", "Ce plat est préparé d'une façon particulière et il est délicieux."),
N("Situation 3. Vous partez après une bonne soirée."),
...h3drill("Remerciez naturellement.", "谢谢你们，今天晚上我玩儿得很开心。", "Merci ; j'ai passé une excellente soirée."),
N("Fin du focus. Vous disposez d'un petit répertoire social immédiatement réutilisable."),
];}},

{num:4,hanzi:"一边吃一边聊",title:"Partie 4 · L'anniversaire",desc:"Dialogue 3 · cadeau · actions simultanées",build(){return[
N("Partie 4. La fête commence et Yang Tongle offre un cadeau à Xiaoming."),
HC("谢谢你们来参加我儿子的生日晚会，希望大家今晚玩儿得开心。", "Merci d'être venus à l'anniversaire de mon fils ; j'espère que vous passerez une bonne soirée.", .56),
HC("小明，生日快乐！我准备了一个小礼物，希望你喜欢！", "Xiaoming, joyeux anniversaire ! J'ai préparé un petit cadeau ; j'espère qu'il te plaira.", .6),
HC("谢谢您，我可以打开吗？", "Merci beaucoup. Puis-je l'ouvrir ?", .7),
HC("当然可以。你妈妈说你跟姐姐一样，都喜欢画画，对吗？", "Bien sûr. Ta mère m'a dit que, comme ta sœur, tu aimais dessiner. C'est vrai ?", .58),
HC("对，我想做一名画家。啊！画板和画笔，这正是我需要的，我太喜欢了。", "Oui, je voudrais devenir peintre. Oh, une planche et des pinceaux ! C'est exactement ce dont j'avais besoin ; j'adore.", .54),
HC("我去把盘子拿过来，咱们一边吃蛋糕，一边聊天儿吧。", "Je vais apporter les assiettes ; mangeons le gâteau tout en discutant.", .58),

N("[[一边 A，一边 B|yìbiān A, yìbiān B]] relie deux actions réellement simultanées. À l'oral, on peut raccourcir en 边 A 边 B."),
HC("我们一边吃蛋糕，一边聊天儿。", "Nous discutons tout en mangeant le gâteau.", .7),
HC("我一边散步，一边听音乐。", "J'écoute de la musique en me promenant.", .7),
HC("你不应该边开车边打电话。", "Tu ne devrais pas téléphoner en conduisant.", .68),
...h3drill("Décrivez la fête : nous buvons du thé en discutant.", "我们一边喝茶，一边聊天儿。", "Nous discutons en buvant du thé."),
...h3drill("Décrivez un apprentissage : j'écoute en prenant des notes.", "我一边听，一边记笔记。", "J'écoute tout en prenant des notes."),

N("Les suffixes indiquent parfois une profession : 球员 joueur, 服务员 serveur ; 画家 peintre, 音乐家 musicien. 家 suggère une expertise reconnue, pas n'importe quel amateur."),
...h3drill("Dites que Xiaoming veut devenir peintre.", "小明想做一名画家。", "Xiaoming veut devenir peintre."),
N("Fin de la partie 4. Vous savez raconter deux actions simultanées et parler d'une vocation."),
];}},

{num:5,hanzi:"来自英国的夫妻",title:"Partie 5 · Des voisins britanniques",desc:"Journal guidé · habitudes culturelles · récit personnel",build(){return[
N("Partie 5. Wang Yixue raconte sa rencontre avec les nouveaux voisins."),
HC("我的新邻居是来自英国的夫妻。", "Mes nouveaux voisins sont un couple britannique.", .68),
HC("上周我去他们家做客了。他们做了很多好吃的，还准备了英国红茶。", "La semaine dernière, je suis allée chez eux. Ils avaient préparé beaucoup de bonnes choses et du thé noir britannique.", .58),
HC("那天我跟他们一边喝红茶，一边聊天儿，直到十二点多才回家。", "Ce jour-là, nous avons bu du thé en discutant ; je ne suis rentrée qu'après minuit.", .56),
HC("他们年轻的时候喜欢旅游，家里有一张世界地图。", "Quand ils étaient jeunes, ils aimaient voyager ; ils ont une carte du monde chez eux.", .6),
HC("地图上每一个红点都是他们去过的地方。", "Chaque point rouge sur la carte représente un endroit qu'ils ont visité.", .64),
HC("后来，他们感到东方文化很特别，就开始学习中文。", "Plus tard, ils ont trouvé les cultures d'Orient particulières et ont commencé à apprendre le chinois.", .6),
HC("今天是小明的生日，我请他们来我家看看，也尝尝中国菜。", "Aujourd'hui, c'est l'anniversaire de Xiaoming ; je les invite chez moi pour découvrir un foyer chinois et goûter la cuisine.", .56),

N("Compréhension. Qu'avaient préparé les voisins ?"),
TH(),HC("他们准备了很多吃的和英国红茶。", "Ils avaient préparé beaucoup de nourriture et du thé noir britannique.", .7),HOLD(),
N("Pourquoi apprennent-ils le chinois ?"),
TH(),HC("因为他们对东方文化很感兴趣。", "Parce qu'ils s'intéressent beaucoup aux cultures orientales.", .7),HOLD(),

N("Mission interculturelle. Décrivez une habitude quand on est invité chez quelqu'un dans votre région. Modèle :"),
TH(),HC("在我的家乡，去朋友家做客的话，一般会带一点儿吃的或者一瓶酒。", "Dans ma région, lorsqu'on est invité chez un ami, on apporte généralement quelque chose à manger ou une bouteille de vin.", .6),HOLD("Répète ce modèle ou décris ta propre habitude, puis ▶"),
N("Fin de la partie 5. Vous savez comparer des usages sans les présenter comme des règles absolues."),
];}},

{num:6,hanzi:"综合练习",title:"Partie 6 · Exercices créés",desc:"Invitation · préparation · politesse · simultanéité",exercise:true,build(){return[
N("Exercices originaux de la leçon 13. Répondez avant la correction."),
N("Exercice 1. Invitez : si vous avez le temps, venez prendre le thé."),
TH(),HC("你们有时间的话，就来我家喝茶吧。", "Si vous avez le temps, venez prendre le thé chez moi.", .7),HOLD(),
N("Exercice 2. Mettez les boissons dans le réfrigérateur."),
TH(),HC("请把饮料放进冰箱里。", "Mettez les boissons dans le réfrigérateur, s'il vous plaît.", .72),HOLD(),
N("Exercice 3. Apportez les assiettes ici."),
TH(),HC("请把盘子拿过来。", "Apportez les assiettes ici, s'il vous plaît.", .72),HOLD(),
N("Exercice 4. Le son est trop fort : baissez-le un peu."),
TH(),HC("声音太大了，请调小一点儿。", "Le son est trop fort ; baissez-le un peu, s'il vous plaît.", .72),HOLD(),
N("Exercice 5. Offrez un cadeau et exprimez votre souhait."),
TH(),HC("这是我给你准备的礼物，希望你喜欢。", "Voici le cadeau que j'ai préparé pour toi ; j'espère qu'il te plaira.", .68),HOLD(),
N("Exercice 6. Nous mangeons tout en discutant."),
TH(),HC("我们一边吃饭，一边聊天儿。", "Nous discutons tout en mangeant.", .72),HOLD(),
N("Exercice 7. Remerciez l'hôte et complimentez son plat."),
TH(),HC("谢谢你请我来做客，你做的菜特别好吃。", "Merci de m'avoir invité ; les plats que tu as préparés sont délicieux.", .68),HOLD(),
N("Exercice 8. Présentez vos nouveaux voisins : origine, centre d'intérêt et invitation."),
TH(),HC("我的新邻居来自英国，他们对中国文化很感兴趣。周末有时间的话，我就请他们来家里吃饭。", "Mes nouveaux voisins viennent du Royaume-Uni et s'intéressent à la culture chinoise. S'ils sont libres ce week-end, je les inviterai à dîner.", .6),HOLD(),
N("Bravo. Vous pouvez recevoir des invités avec des phrases pratiques, polies et culturellement nuancées."),
HC("一边交流，一边了解不同的生活习惯。", "Échangeons tout en découvrant différentes habitudes de vie.", .7),
HC("再见！", "Au revoir !", .74),
];}}
]});
