/* Nouveau HSK 3.0 · Leçon 15 — 我是半个南京人
   Source : « 新HSK教程 3 », leçon 15. Exercices audio originaux. */
registerChapter({group:"hsk3",id:"hsk3-15",badge:15,hanzi:"我是半个南京人",
title:"Leçon 15 · Présenter une ville et un paysage",desc:"6 cours · 根据 · répétition quantitative · 在…看来 · 不一会儿",
intro:"Cette leçon vous apprend à décrire un quartier, présenter Nankin, expliquer l'importance du fleuve Jaune et raconter un lieu personnel. Vous apprendrez surtout à distinguer une source objective avec 根据 d'un point de vue avec 在…看来.",lessons:[

{num:1,hanzi:"根据他们的需要",title:"Partie 1 · Un quartier adapté à ses habitants",desc:"Dialogue 1 · environnement · 根据",build(){return[
N("Partie 1. Yang Tongle demande à Wang Yixue ce qu'elle pense de sa nouvelle résidence."),
HC("您搬到蓝天小区一段时间了，觉得怎么样？", "Cela fait quelque temps que vous avez emménagé dans la résidence Lantian. Qu'en pensez-vous ?", .58),
HC("小区环境挺好的，附近买东西也很方便，过马路就是超市。", "L'environnement est agréable et les achats sont faciles : le supermarché est juste de l'autre côté de la rue.", .56),
HC("小区里有很多树，孩子们放学后就在树下做游戏。", "Il y a beaucoup d'arbres ; après l'école, les enfants jouent dessous.", .6),
HC("你想买房子吗？", "Vous voulez acheter un logement ?", .7),
HC("是。我想买一个大点儿的房子，让我爸妈过来跟我一起住。", "Oui. Je voudrais un logement plus grand pour que mes parents viennent vivre avec moi.", .56),
HC("蓝天小区的老人挺多的。这几年，小区根据他们的需要，有了很多变化。", "Il y a beaucoup de personnes âgées à Lantian. Ces dernières années, la résidence a évolué selon leurs besoins.", .54),
HC("真不错！过几天我去蓝天小区看看。", "C'est très bien ! J'irai visiter la résidence dans quelques jours.", .62),

N("[[根据|gēnjù]] introduit la base objective d'une décision : selon les besoins, les règles, les résultats ou les informations disponibles."),
HC("小区根据老人的需要有了变化。", "La résidence a évolué selon les besoins des personnes âgées.", .68),
HC("根据要求，我们必须参加会议。", "Selon les consignes, nous devons participer à la réunion.", .68),
HC("老师根据学生的兴趣选择了不同的书。", "Le professeur a choisi différents livres selon les centres d'intérêt des élèves.", .66),
...h3drill("Choisissez selon la météo : selon les prévisions, prenez un imperméable.", "根据天气预报，出门要带雨衣。", "Selon les prévisions, il faut emporter un imperméable."),
...h3drill("Adaptez un cours : le professeur choisit les exercices selon notre niveau.", "老师根据我们的水平选择练习。", "Le professeur choisit les exercices selon notre niveau."),

N("Mission logement. Donnez deux avantages du quartier, puis un besoin personnel."),
...h3drill("Répondez.", "这里环境挺好的，买东西也方便，但是我需要一个大点儿的房子。", "L'environnement est agréable et les achats faciles, mais j'ai besoin d'un logement plus grand."),
N("Fin de la partie 1. Vous savez fonder une décision sur un critère explicite."),
];}},

{num:2,hanzi:"半个南京人",title:"Partie 2 · Faire découvrir Nankin",desc:"Dialogue 2 · histoire · progression point par point",build(){return[
N("Partie 2. Wang Yixue veut visiter Nankin et découvre que Yang Tongle y connaît beaucoup de choses."),
HC("假期我想去南京旅游，但是我不太了解那里。", "J'aimerais visiter Nankin pendant les vacances, mais je connais mal la ville.", .62),
HC("我虽然不是南京人，可是我是在南京上的大学，可以说是半个南京人。", "Je ne suis pas originaire de Nankin, mais j'y ai fait mes études ; on peut dire que je suis à moitié Nankinois.", .56),
HC("太好了！你快给我介绍一下南京吧。", "Génial ! Présente-moi vite Nankin.", .66),
HC("南京有两千年以上的历史，有老城、老街，还有很多有名的景点。", "Nankin a plus de deux mille ans d'histoire, une vieille ville, de vieilles rues et beaucoup de sites célèbres.", .56),
HC("每年去旅游的游客特别多。", "Chaque année, les touristes y sont très nombreux.", .68),
HC("除了这些以外，你再告诉我一些外地人不知道的地方。", "À part cela, parle-moi aussi de lieux que les visiteurs connaissent peu.", .58),
HC("没问题，我得一点儿一点儿给您讲。", "Pas de problème ; je vais devoir vous les présenter petit à petit.", .64),
HC("行，下班后我请你吃晚饭，咱们边吃边聊。", "D'accord. Je t'invite à dîner après le travail ; nous en parlerons en mangeant.", .62),

N("Une séquence numérique répétée décrit une progression distribuée : 一点儿一点儿 petit à petit ; 一天一天 jour après jour ; 两个两个 par groupes de deux."),
HC("我一点儿一点儿给你讲。", "Je vais te l'expliquer petit à petit.", .72),
HC("她的中文水平一天一天地提高。", "Son niveau de chinois progresse jour après jour.", .68),
HC("学生们两个两个地走进去。", "Les élèves entrent deux par deux.", .68),
...h3drill("Traitez les exercices un par un.", "这些练习要一个一个地做。", "Il faut faire ces exercices un par un."),
...h3drill("Regardez les photos une par une.", "我们一张一张地看照片。", "Nous regardons les photos une par une."),
...h3drill("Progressez petit à petit.", "别着急，一点儿一点儿学。", "Ne vous pressez pas ; apprenez petit à petit."),
N("Fin de la partie 2. Vous savez présenter beaucoup d'informations sans tout donner d'un bloc."),
];}},

{num:3,hanzi:"根据还是在看来",title:"Partie 3 · Focus intermédiaire : fait ou point de vue",desc:"根据 · 对…来说 · 在…看来",build(){return[
N("Focus intermédiaire. Trois structures attribuent une information, mais pas au même type de source."),
HC("根据新闻，明天会下雨。", "D'après les informations, il pleuvra demain.", .72),
N("根据 cite une base, un document ou un critère."),
HC("对我来说，春天最舒服。", "Pour moi, le printemps est la saison la plus agréable.", .72),
N("对…来说 indique à qui une situation s'applique."),
HC("在我看来，春天最舒服。", "À mon avis, le printemps est la saison la plus agréable.", .72),
N("在…看来 attribue explicitement un jugement ou une lecture de la situation."),

N("Une règle écrite impose la présence."),
...h3drill("Utilisez 根据.", "根据学校的要求，我们都要参加。", "Selon les exigences de l'école, nous devons tous participer."),
N("Vous exprimez votre jugement sur Nankin."),
...h3drill("Utilisez 在我看来.", "在我看来，南京是一座很有意思的城市。", "À mon avis, Nankin est une ville très intéressante."),
N("Vous décrivez la difficulté pour un enfant."),
...h3drill("Utilisez 对孩子来说.", "对孩子来说，这本书有点儿难。", "Pour un enfant, ce livre est un peu difficile."),
N("Vous rapportez le jugement des habitants."),
...h3drill("Utilisez 在当地人看来.", "在当地人看来，这条老街最值得去。", "Selon les habitants, cette vieille rue mérite le plus la visite."),
N("Fin du focus. Une source n'est pas une opinion, et une opinion n'est pas une règle."),
];}},

{num:4,hanzi:"黄河像妈妈一样",title:"Partie 4 · Présenter le fleuve Jaune",desc:"Dialogue 3 · histoire · point de vue collectif",build(){return[
N("Partie 4. Wang Yixue questionne Xiaoming sur un grand fleuve chinois."),
HC("小明，中国有一条大河，它的名字跟颜色有关系，你知道是什么河吗？", "Xiaoming, un grand fleuve chinois porte un nom lié à une couleur. Sais-tu lequel ?", .54),
HC("我知道，是黄河！", "Je sais : le fleuve Jaune !", .72),
HC("你知道它为什么叫黄河吗？", "Sais-tu pourquoi il s'appelle ainsi ?", .68),
HC("因为河水看起来是黄色的，所以叫这个名字。黄河是中国最长的河吗？", "Parce que l'eau paraît jaune. Est-ce le plus long fleuve de Chine ?", .58),
HC("不是。黄河虽然不是最长的河，可是在历史上很重要。", "Non. Même s'il n'est pas le plus long, il est historiquement très important.", .6),
HC("这个我知道。很久以前，很多中国人都住在黄河边上。", "Cela, je le sais. Autrefois, beaucoup de Chinois vivaient sur ses rives.", .58),
HC("对。在中国人看来，黄河像妈妈一样，养了我们几千年。", "Oui. Pour les Chinois, le fleuve Jaune est comme une mère qui nourrit le peuple depuis des millénaires.", .56),

N("[[在…看来|zài…kànlái]] peut porter un avis individuel ou collectif."),
HC("在同事们看来，她工作非常认真。", "Selon ses collègues, elle travaille très sérieusement.", .68),
HC("在我看来，每天读书是一个好习惯。", "À mon avis, lire chaque jour est une bonne habitude.", .68),
...h3drill("Point de vue collectif : pour les habitants, ce fleuve est très important.", "在当地人看来，这条河非常重要。", "Pour les habitants, ce fleuve est très important."),

N("Compréhension. Le fleuve Jaune est-il le plus long de Chine ?"),
TH(),HC("不是，但是它在历史上非常重要。", "Non, mais il est historiquement très important.", .7),HOLD(),
N("Pourquoi est-il comparé à une mère ?"),
TH(),HC("因为几千年来，很多中国人都生活在黄河边。", "Parce que, depuis des millénaires, beaucoup de Chinois vivent sur ses rives.", .68),HOLD(),
N("Fin de la partie 4. Vous savez présenter un fait géographique et le sens culturel qui lui est attribué."),
];}},

{num:5,hanzi:"不一会儿就忘了",title:"Partie 5 · Un lieu lié aux souvenirs",desc:"Journal guidé · paysage · 不一会儿",build(){return[
N("Partie 5. Wang Yixue décrit le lieu préféré de son enfance."),
HC("我小时候住在北京的西北边，有一条非常有名的河经过那里。", "Enfant, je vivais au nord-ouest de Pékin, où passait une rivière très connue.", .56),
HC("我家就住在河边，那里有高高的大树和绿绿的草地。", "Notre maison était au bord de l'eau, avec de grands arbres et des prairies bien vertes.", .6),
HC("春天，河边的花都开了，看起来特别漂亮。", "Au printemps, toutes les fleurs s'ouvraient ; c'était très beau.", .6),
HC("一到夏天，我就去河里游泳。", "Dès l'arrivée de l'été, j'allais nager dans la rivière.", .68),
HC("长大以后，遇到不开心的事情，我就去河边的树下坐着。", "Adulte, lorsqu'une chose me rendait triste, j'allais m'asseoir sous un arbre au bord de l'eau.", .6),
HC("我听听鸟叫，看看河水，跟遇见的朋友聊聊天儿，难过的事情不一会儿就忘了。", "J'écoutais les oiseaux, regardais l'eau et discutais avec les amis rencontrés ; ma tristesse disparaissait rapidement.", .54),
HC("那是我最喜欢的地方。", "C'était mon endroit préféré.", .72),

N("[[不一会儿|bù yíhuìr]] signifie qu'un court moment suffit. Il se combine souvent avec 就."),
HC("难过的事情不一会儿就忘了。", "La tristesse s'oublie rapidement.", .72),
HC("不一会儿，张校长就来了。", "Peu après, le directeur Zhang est arrivé.", .72),
HC("两个小时看起来很长，但是不一会儿就过去了。", "Deux heures paraissent longues, mais elles passent vite.", .68),
...h3drill("Le taxi arrive peu après.", "我们等了一会儿，出租车不一会儿就来了。", "Nous avons attendu un peu ; le taxi est vite arrivé."),
...h3drill("Après avoir discuté, elle se sent vite mieux.", "聊了一会儿，她不一会儿就开心起来了。", "Après un moment de discussion, elle s'est vite sentie mieux."),

N("Mission personnelle. Décrivez un lieu important : position, paysage, activité et sensation. Modèle :"),
TH(),HC("我最喜欢的地方在城外，那里有一条小河。我常常去散步，不一会儿就觉得轻松多了。", "Mon endroit préféré se trouve hors de la ville, près d'une petite rivière. J'y marche souvent et je me sens vite plus détendu.", .6),HOLD("Répète ce modèle ou décris ton propre lieu, puis ▶"),
N("Fin de la partie 5. Vous savez relier une description géographique à une expérience personnelle."),
];}},

{num:6,hanzi:"综合练习",title:"Partie 6 · Exercices créés",desc:"Critères · progression · avis · description",exercise:true,build(){return[
N("Exercices originaux de la leçon 15. Répondez avant la correction."),
N("Exercice 1. Selon les besoins des habitants, le quartier a changé."),
TH(),HC("小区根据居民的需要有了变化。", "Le quartier a évolué selon les besoins des habitants.", .7),HOLD(),
N("Exercice 2. Faites les exercices un par un."),
TH(),HC("这些题要一个一个地做。", "Il faut faire ces exercices un par un.", .72),HOLD(),
N("Exercice 3. Son niveau progresse jour après jour."),
TH(),HC("他的水平一天一天地提高。", "Son niveau progresse jour après jour.", .72),HOLD(),
N("Exercice 4. Pour moi, vivre près d'une rivière est très agréable."),
TH(),HC("在我看来，住在河边很舒服。", "À mon avis, vivre près d'une rivière est très agréable.", .72),HOLD(),
N("Exercice 5. Selon les touristes, cette vieille rue est très intéressante."),
TH(),HC("在游客看来，这条老街很有意思。", "Selon les touristes, cette vieille rue est très intéressante.", .72),HOLD(),
N("Exercice 6. Le directeur arrive peu après."),
TH(),HC("不一会儿，校长就来了。", "Peu après, le directeur est arrivé.", .74),HOLD(),
N("Exercice 7. Présentez Nankin en deux faits : histoire et sites."),
TH(),HC("南京有两千多年的历史，还有很多有名的景点。", "Nankin a plus de deux mille ans d'histoire et beaucoup de sites célèbres.", .7),HOLD(),
N("Exercice 8. Présentez un quartier selon trois critères : environnement, commerces et habitants."),
TH(),HC("这个小区环境挺好的，过马路就是超市。小区还根据老人和孩子的需要建了一个公园。", "Cette résidence est agréable et le supermarché est juste en face. Elle a aussi aménagé un parc selon les besoins des personnes âgées et des enfants.", .62),HOLD(),
N("Bilan des leçons 13 à 15. Vous savez recevoir, employer 被, présenter une ville et attribuer clairement une opinion."),
HC("根据事实来介绍，再说说自己的看法。", "Présentez d'après les faits, puis donnez votre propre point de vue.", .72),
HC("再见！", "Au revoir !", .74),
];}}
]});
