/* Nouveau HSK 3.0 · Leçon 16 — 我听说有的熊猫出国了
   Source : « 新HSK教程 3 », leçon 16. Exercices audio originaux. */
registerChapter({group:"hsk3",id:"hsk3-16",badge:16,hanzi:"我听说有的熊猫出国了",
title:"Leçon 16 · Animaux, soins et pandas",desc:"6 cours · 一会儿…一会儿… · 关于 · 一般来说 · écarts chiffrés",
intro:"Vous allez décrire un animal, parler de ses habitudes, poser des questions sur les pandas et préparer une visite au zoo. Un atelier spécial vous apprend à comparer des quantités et des horaires avec un écart précis.",lessons:[

{num:1,hanzi:"一会儿睡一会儿爬",title:"Partie 1 · Adopter ou non un animal",desc:"Dialogue 1 · soins · alternance",build(){return[
N("Partie 1. Dans un refuge, une famille observe un chat recueilli depuis plus d'un an."),
HC("这只小猫你们养了多久了？", "Depuis combien de temps vous occupez-vous de ce chat ?", .66),
HC("已经一年多了。第一天看见它的时候，它又脏又小。", "Depuis plus d'un an. Le premier jour, il était sale et tout petit.", .6),
HC("现在它变得又干净又漂亮了。", "Maintenant, il est devenu propre et beau.", .68),
HC("是啊。它还特别可爱，一会儿在你脚边睡觉，一会儿在你身上爬。", "Oui, et il est adorable : tantôt il dort à vos pieds, tantôt il grimpe sur vous.", .56),
HC("你们把它照顾得真好。", "Vous vous en occupez vraiment bien.", .7),
HC("它就好像我们的孩子。我们照顾它，它也认得我们了。", "Il est comme notre enfant. Nous prenons soin de lui et il nous reconnaît maintenant.", .6),
HC("妈妈，我们家也养一只小猫吧。", "Maman, adoptons nous aussi un chat.", .68),
HC("咱们没时间照顾，还是别养了。我周末带你们去动物园看动物吧。", "Nous n'avons pas le temps de nous en occuper ; mieux vaut ne pas en adopter. Je vous emmènerai au zoo ce week-end.", .54),

N("[[一会儿 A，一会儿 B|yíhuìr A, yíhuìr B]] décrit deux actions ou états qui alternent sur une courte période."),
HC("小猫一会儿睡觉，一会儿到处爬。", "Le chat tantôt dort, tantôt grimpe partout.", .68),
HC("他一会儿进来，一会儿出去，忙得很。", "Il entre puis ressort sans arrêt ; il est très occupé.", .68),
HC("最近一会儿冷，一会儿热。", "Ces derniers temps, il fait tantôt froid, tantôt chaud.", .7),
N("Ne confondez pas avec 一边…一边…, où deux actions sont simultanées. Ici, elles alternent."),
...h3drill("Décrivez un chien agité : tantôt il court, tantôt il saute.", "这只狗一会儿跑，一会儿跳。", "Ce chien tantôt court, tantôt saute."),
...h3drill("Décrivez une météo changeante : tantôt il pleut, tantôt le ciel se dégage.", "天气一会儿下雨，一会儿又晴了。", "Tantôt il pleut, tantôt le ciel se dégage à nouveau."),

N("Réponse responsable. Expliquez qu'aimer un animal ne suffit pas : il faut avoir le temps de s'en occuper."),
...h3drill("Dites la raison.", "喜欢小动物还不够，还要有时间照顾它。", "Aimer un animal ne suffit pas ; il faut aussi avoir le temps de s'en occuper."),
N("Fin de la partie 1. Vous savez décrire un comportement changeant et réfléchir aux soins nécessaires."),
];}},

{num:2,hanzi:"关于大熊猫",title:"Partie 2 · Poser des questions sur les pandas",desc:"Dialogue 2 · sujet avec 关于 · connaissances",build(){return[
N("Partie 2. Au zoo, Xiaoming enchaîne les questions sur les pandas géants."),
HC("大熊猫这个名字很奇怪，它们跟猫有什么关系？", "Le nom « grand chat-ours » est étrange. Quel rapport ont-ils avec les chats ?", .6),
HC("这个问题问得好。它们跟猫没什么关系，其实应该叫大猫熊。", "Bonne question. Ils n'ont pas vraiment de lien avec les chats ; le nom logique serait plutôt grand ours-chat.", .56),
HC("它们为什么只吃竹子，不吃肉？", "Pourquoi mangent-ils uniquement du bambou et pas de viande ?", .66),
HC("大熊猫为什么是中国的国宝？", "Pourquoi le panda géant est-il un trésor national chinois ?", .66),
HC("全世界只有中国有野生大熊猫，中国是大熊猫的家。", "La Chine est le seul pays au monde où vivent des pandas géants sauvages ; c'est leur terre d'origine.", .6),
HC("我听说有的熊猫出国了，它们去哪儿了？", "J'ai entendu dire que certains pandas étaient partis à l'étranger. Où sont-ils allés ?", .62),
HC("关于这个问题，我得慢慢给你讲。", "Pour cette question, je vais devoir t'expliquer progressivement.", .68),
HC("弟弟，你真是十万个为什么。", "Petit frère, tu es vraiment un « cent mille pourquoi » !", .68),

N("[[关于|guānyú]] + nom introduit le sujet dont on va parler : à propos de, concernant. Placez souvent le groupe au début, suivi d'une pause."),
HC("关于这个问题，我还有一些话要说。", "À propos de cette question, j'ai encore quelques éléments à ajouter.", .68),
HC("关于比赛时间，我明天告诉大家。", "Concernant l'heure du match, j'informerai tout le monde demain.", .68),
HC("关于怎么学习中文，老师给了我很多建议。", "Concernant la manière d'apprendre le chinois, le professeur m'a donné beaucoup de conseils.", .66),
...h3drill("Introduisez votre sujet : j'ai une question sur les pandas.", "关于大熊猫，我有一个问题。", "J'ai une question au sujet des pandas géants."),
...h3drill("Annoncez une décision différée : nous déciderons après la réunion.", "关于这件事，我们开会以后再决定。", "Concernant cette affaire, nous déciderons après la réunion."),
N("Fin de la partie 2. Vous savez annoncer clairement le thème avant de développer une réponse."),
];}},

{num:3,hanzi:"一般和例外",title:"Partie 3 · Focus intermédiaire",desc:"一般来说 · 有的 · 只有 · généralisation prudente",build(){return[
N("Focus intermédiaire. Pour parler des animaux avec précision, séparez la tendance générale, certains cas et l'unique condition."),
HC("一般来说，熊猫每天要睡很多次觉。", "En général, les pandas dorment plusieurs fois par jour.", .68),
N("一般来说 annonce une tendance, pas une règle sans exception."),
HC("有的熊猫出国了。", "Certains pandas sont partis à l'étranger.", .72),
N("有的 + nom ou 有的 tout seul sélectionne certains membres d'un groupe."),
HC("全世界只有中国有野生大熊猫。", "La Chine est le seul pays au monde où vivent des pandas sauvages.", .68),
N("只有 limite la condition ou l'élément à un seul cas."),

N("Tendance : apprendre une langue exige généralement beaucoup de pratique."),
...h3drill("Répondez.", "一般来说，学习外语需要多练习。", "En général, apprendre une langue exige beaucoup de pratique."),
N("Variété : certains chats aiment dormir, d'autres aiment courir."),
...h3drill("Répondez.", "有的猫喜欢睡觉，有的喜欢跑来跑去。", "Certains chats aiment dormir, d'autres courir partout."),
N("Restriction : seuls les visiteurs munis d'un billet peuvent entrer."),
...h3drill("Répondez.", "只有买了票的游客才能进去。", "Seuls les visiteurs qui ont un billet peuvent entrer."),
N("Fin du focus. Une généralisation pédagogique reste prudente et explicite ses exceptions."),
];}},

{num:4,hanzi:"熊猫的一天",title:"Partie 4 · Observer les pandas",desc:"Dialogue 3 · comportement · généralisation",build(){return[
N("Partie 4. Dans l'espace des pandas, les enfants décrivent ce qu'ils voient."),
HC("这只大熊猫一会儿爬上去，一会儿跳下来，可爱极了！", "Ce panda grimpe puis redescend en sautant ; il est adorable !", .6),
HC("它好像还没吃饱，站起来张着嘴找吃的呢。", "Il ne semble pas rassasié ; il se lève et cherche à manger, la bouche ouverte.", .6),
HC("那只大熊猫怎么一直不动，是不是在睡觉呢？", "Pourquoi l'autre panda ne bouge-t-il pas ? Il dort ?", .62),
HC("它可能是累了。一般来说，熊猫每天要睡很多次觉。", "Il est peut-être fatigué. En général, les pandas dorment plusieurs fois par jour.", .6),
HC("除了睡觉以外，很多时间它们都在吃东西。", "En dehors du sommeil, ils passent une grande partie de leur temps à manger.", .64),
HC("这也叫生活？", "On appelle cela une vie ?", .74),
HC("妈妈，帮我跟大熊猫照一张照片吧。", "Maman, prends-moi en photo avec le panda.", .68),

N("Compréhension. Pourquoi pense-t-on que le premier panda n'est pas rassasié ?"),
TH(),HC("因为它站起来张着嘴找吃的。", "Parce qu'il se lève et cherche à manger, la bouche ouverte.", .68),HOLD(),
N("Que font généralement les pandas pendant une grande partie de la journée ?"),
TH(),HC("它们一般睡觉或者吃东西。", "En général, ils dorment ou mangent.", .7),HOLD(),

N("Jeu d'observation. Décrivez un animal sans donner son nom : apparence, mouvement, alimentation."),
TH(),HC("它的耳朵很长，一会儿跑，一会儿停下来吃草。", "Il a de longues oreilles ; tantôt il court, tantôt il s'arrête pour manger de l'herbe.", .66),
N("Réponse :"),HC("是兔子。", "C'est un lapin.", .76),HOLD(),
N("Fin de la partie 4. Vous savez distinguer ce que vous observez de ce que vous généralisez."),
];}},

{num:5,hanzi:"早关门一个小时",title:"Partie 5 · Préparer une visite au zoo",desc:"Récit · horaires · différence chiffrée",build(){return[
N("Partie 5. Wang Yixue résume la visite du zoo de Pékin."),
HC("今天我带小雪和小明去动物园玩了。", "Aujourd'hui, j'ai emmené Xiaoxue et Xiaoming au zoo.", .66),
HC("北京动物园是中国很有名的动物园，里面有非常多的动物。", "Le zoo de Pékin est très connu en Chine et abrite de nombreux animaux.", .58),
HC("大人和孩子最喜爱的还是大熊猫。", "Les pandas restent les animaux préférés des adultes comme des enfants.", .64),
HC("每天有很多游客带着相机去熊猫馆拍照。", "Chaque jour, de nombreux visiteurs vont prendre des photos dans l'espace des pandas.", .62),
HC("动物园早上七点半开门，晚上七点关门。", "Le zoo ouvre à sept heures trente et ferme à dix-neuf heures.", .64),
HC("冬天比夏天游客少，所以也比平时早关门一个小时。", "Il y a moins de visiteurs en hiver ; le zoo ferme donc une heure plus tôt que d'habitude.", .58),
HC("如果第一次来北京旅游，跟家人一起去北京动物园是个不错的选择。", "Pour une première visite de Pékin, aller au zoo en famille est un bon choix.", .56),

N("Pour chiffrer un écart de quantité ou de temps : A 比 B + 多/少/早/晚 + verbe + quantité."),
HC("冬天比夏天早关门一个小时。", "En hiver, le zoo ferme une heure plus tôt qu'en été.", .68),
HC("姐姐比弟弟多吃了三个饺子。", "La grande sœur a mangé trois raviolis de plus que son frère.", .68),
HC("我比他晚到了十分钟。", "Je suis arrivé dix minutes après lui.", .7),
HC("今天比昨天少来了二十个游客。", "Il est venu vingt visiteurs de moins qu'hier.", .68),
...h3drill("Comparez les horaires : l'été, le zoo ferme une heure plus tard.", "夏天比冬天晚关门一个小时。", "En été, le zoo ferme une heure plus tard qu'en hiver."),
...h3drill("Comparez une consommation : le panda mange cinq kilos de plus aujourd'hui.", "这只熊猫今天比昨天多吃了五公斤竹子。", "Ce panda a mangé cinq kilos de bambou de plus qu'hier."),
...h3drill("Comparez deux arrivées : je suis arrivé vingt minutes plus tôt que lui.", "我比他早到了二十分钟。", "Je suis arrivé vingt minutes avant lui."),

N("Réponse personnelle. Présentez un animal en trois phrases : habitat, comportement général, fait particulier. Modèle :"),
TH(),HC("这种动物生活在山里。一般来说，它白天睡觉，晚上出来找吃的。有的也生活在城市附近。", "Cet animal vit dans les montagnes. En général, il dort le jour et cherche sa nourriture la nuit ; certains vivent aussi près des villes.", .58),HOLD("Répète ce modèle ou présente un autre animal, puis ▶"),
N("Fin de la partie 5. Vous savez donner des informations pratiques et comparer un écart exact."),
];}},

{num:6,hanzi:"综合练习",title:"Partie 6 · Exercices créés",desc:"Habitudes · sujet · alternance · comparaison",exercise:true,build(){return[
N("Exercices originaux de la leçon 16. Répondez avant la correction."),
N("Exercice 1. Le chat tantôt dort, tantôt joue."),
TH(),HC("小猫一会儿睡觉，一会儿玩儿。", "Le chat tantôt dort, tantôt joue.", .72),HOLD(),
N("Exercice 2. Introduisez le sujet : j'ai deux questions sur cet animal."),
TH(),HC("关于这种动物，我有两个问题。", "J'ai deux questions au sujet de cet animal.", .72),HOLD(),
N("Exercice 3. En général, ce type d'oiseau vit près de l'eau."),
TH(),HC("一般来说，这种鸟生活在水边。", "En général, cet oiseau vit près de l'eau.", .72),HOLD(),
N("Exercice 4. Certains aiment les chats, d'autres les chiens."),
TH(),HC("有的人喜欢猫，有的人喜欢狗。", "Certaines personnes aiment les chats, d'autres les chiens.", .72),HOLD(),
N("Exercice 5. Le zoo ouvre trente minutes plus tôt en été."),
TH(),HC("动物园夏天比冬天早开门半个小时。", "Le zoo ouvre une demi-heure plus tôt en été.", .7),HOLD(),
N("Exercice 6. J'ai pris dix photos de plus que mon frère."),
TH(),HC("我比弟弟多照了十张照片。", "J'ai pris dix photos de plus que mon frère.", .7),HOLD(),
N("Exercice 7. Expliquez pourquoi la famille n'adopte pas de chat."),
TH(),HC("因为他们没有时间照顾小猫。", "Parce qu'ils n'ont pas le temps de s'occuper d'un chat.", .72),HOLD(),
N("Exercice 8. Conseillez une visite : horaires, saison et activité."),
TH(),HC("动物园早上七点半开门。冬天早关门一个小时，所以最好早点儿去。可以带相机给熊猫拍照。", "Le zoo ouvre à sept heures trente. En hiver, il ferme une heure plus tôt ; mieux vaut donc y aller tôt. Vous pouvez apporter un appareil photo pour photographier les pandas.", .6),HOLD(),
N("Bravo. Vous pouvez présenter un animal sans confondre observation, tendance générale et exception."),
HC("一般来说，了解得越多，问题也会越多。", "En général, plus on apprend, plus les questions se multiplient.", .7),
HC("再见！", "Au revoir !", .74),
];}}
]});
