/* Nouveau HSK 3.0 · Leçon 17 — 我要多向认真的人学习
   Source : « 新HSK教程 3 », leçon 17. Exercices audio originaux. */
registerChapter({group:"hsk3",id:"hsk3-17",badge:17,hanzi:"我要多向认真的人学习",
title:"Leçon 17 · Émotions, orientation et décisions",desc:"6 cours · 向 · 不是…吗 · 更 progressif · 只有…才…",
intro:"Cette leçon vous aide à exprimer la peur, l'incompréhension et l'hésitation, puis à chercher une orientation d'études. Vous apprendrez à rappeler une information avec 不是…吗 et à distinguer une condition ordinaire d'une condition indispensable avec 只有…才….",lessons:[

{num:1,hanzi:"向认真的人学习",title:"Partie 1 · Apprendre de ses erreurs",desc:"Dialogue 1 · peur · direction avec 向",build(){return[
N("Partie 1. Une élève a peur de rencontrer sa professeure après plusieurs erreurs."),
HC("别再向前走了，李老师的办公室已经到了。", "N'avance plus ; nous sommes arrivées au bureau de la professeure Li.", .62),
HC("你进去吧，我在楼梯那儿等你。我害怕见李老师。", "Entre sans moi ; je t'attends près de l'escalier. J'ai peur de voir la professeure Li.", .58),
HC("最近我做错了好几件事，我怕李老师生气。", "J'ai fait plusieurs erreurs récemment et je crains qu'elle se fâche.", .6),
HC("你说什么呢？做错事情是很常见的。", "Qu'est-ce que tu racontes ? Faire des erreurs est très courant.", .62),
HC("可是我把简单的事情做错了，李老师一定觉得我不认真。", "Mais j'ai raté des choses simples ; elle va sûrement me trouver peu sérieuse.", .56),
HC("有的人虽然很聪明，但是觉得事情简单，就不会认真去做了。", "Certaines personnes sont intelligentes, mais dès qu'une tâche paraît simple, elles ne la font plus soigneusement.", .56),
HC("你说得对，以后我要多向认真的人学习。", "Tu as raison ; désormais, je prendrai davantage exemple sur les personnes consciencieuses.", .6),

N("[[向|xiàng]] introduit une direction physique ou la cible d'une action."),
HC("别再向前走了。", "N'avance plus.", .74),
HC("孩子向妈妈跑过去了。", "L'enfant a couru vers sa mère.", .72),
HC("我要向认真的人学习。", "Je veux prendre exemple sur les personnes consciencieuses.", .72),
...h3drill("Direction : tournez vers la droite.", "请向右转。", "Tournez à droite, s'il vous plaît."),
...h3drill("Cible : demandez de l'aide au professeur.", "有问题可以向老师求助。", "En cas de problème, vous pouvez demander de l'aide au professeur."),
...h3drill("Apprentissage : je veux apprendre de mes collègues expérimentés.", "我要多向有经验的同事学习。", "Je veux davantage apprendre de mes collègues expérimentés."),

N("Réponse personnelle. Citez une erreur simple et ce que vous en avez appris. Modèle :"),
TH(),HC("我有一次忘了带护照。以后出门前，我要认真检查。", "Une fois, j'ai oublié mon passeport. Désormais, je vérifierai attentivement avant de sortir.", .64),HOLD("Répète ce modèle ou raconte ta propre expérience, puis ▶"),
N("Fin de la partie 1. Vous savez exprimer une peur, la relativiser et en tirer une décision."),
];}},

{num:2,hanzi:"你不是喜欢电脑吗",title:"Partie 2 · Chercher sa voie",desc:"Dialogue 2 · études · question rhétorique",build(){return[
N("Partie 2. Bai Jiayue s'étonne de voir Chen Tianzhong travailler à la bibliothèque."),
HC("太阳从西边出来了？这几天怎么总是在图书馆看见你？", "Le soleil se lèverait-il à l'ouest ? Pourquoi est-ce que je te vois toujours à la bibliothèque ces jours-ci ?", .56),
HC("这有什么奇怪的？我是来学习的。", "Qu'y a-t-il d'étrange ? Je viens étudier.", .64),
HC("你怎么还在图书馆学习？同学们都在到处找工作呢。", "Pourquoi étudies-tu encore à la bibliothèque ? Tous les autres cherchent du travail partout.", .58),
HC("我不想现在就工作，还想继续学习，我爸妈也同意。", "Je ne veux pas travailler tout de suite ; je souhaite poursuivre mes études et mes parents sont d'accord.", .58),
HC("可我还没想好学什么，所以来图书馆看看。", "Mais je n'ai pas encore choisi quoi étudier, alors je viens chercher des idées.", .62),
HC("你不是喜欢玩儿电脑吗？你可以看看跟电脑有关系的书。", "Tu n'aimes pas l'informatique ? Tu pourrais consulter des livres en rapport avec ce domaine.", .58),
HC("你说得对。我记得那个屋子里有一些跟电脑有关的书，我去找找。", "Tu as raison. Je me souviens qu'il y a des livres sur l'informatique dans cette salle ; je vais chercher.", .56),

N("La question rhétorique [[不是…吗|bú shì…ma]] rappelle un fait que l'on considère connu. Selon le ton, elle peut exprimer surprise, incompréhension, rappel ou mécontentement."),
HC("你不是喜欢电脑吗？", "Mais tu aimes l'informatique, non ?", .72),
HC("你不是说今天有事吗？为什么来了？", "Tu n'avais pas dit être occupé aujourd'hui ? Pourquoi es-tu venu ?", .68),
HC("考试不是下个月吗？你怎么今天就开始复习了？", "L'examen n'est-il pas le mois prochain ? Pourquoi révises-tu déjà ?", .66),
N("La forme est négative, mais le présupposé est positif : je pense que tu aimes l'informatique."),
...h3drill("Rappelez une promesse : tu n'avais pas dit que tu viendrais demain ?", "你不是说好明天来吗？", "Tu n'avais pas dit que tu viendrais demain ?"),
...h3drill("Exprimez votre surprise : aujourd'hui n'est-il pas dimanche ?", "今天不是星期天吗？", "Aujourd'hui n'est-il pas dimanche ?"),
N("Fin de la partie 2. Vous savez rappeler une information sans transformer la phrase en simple question neutre."),
];}},

{num:3,hanzi:"如果还是只有",title:"Partie 3 · Focus intermédiaire sur les conditions",desc:"如果…就… · …的话就… · 只有…才…",build(){return[
N("Focus intermédiaire. 如果 et …的话 décrivent une condition possible. 只有…才… présente la seule condition permettant le résultat."),
HC("如果有时间，我就去图书馆。", "Si j'ai le temps, j'irai à la bibliothèque.", .7),
HC("有时间的话，我就去图书馆。", "Si j'ai le temps, j'irai à la bibliothèque.", .7),
N("Ces deux conditions sont ouvertes : d'autres situations restent envisageables."),
HC("只有认真准备，才能考好。", "Ce n'est qu'en se préparant sérieusement qu'on peut réussir l'examen.", .7),
N("Ici, 认真准备 est présenté comme indispensable."),

N("Condition possible : s'il pleut, je resterai chez moi."),
...h3drill("Utilisez 如果.", "如果下雨，我就待在家里。", "S'il pleut, je resterai chez moi."),
N("Condition indispensable : seul un entraînement quotidien permet de progresser."),
...h3drill("Utilisez 只有…才…", "只有每天练习，才能进步。", "Ce n'est qu'en s'entraînant chaque jour qu'on progresse."),
N("Place du sujet : lorsque le résultat a un sujet, celui-ci vient avant 才."),
HC("只有多听、多说、多看，你的中文水平才能提高。", "Ce n'est qu'en écoutant, parlant et lisant beaucoup que ton chinois peut progresser.", .68),
...h3drill("Construisez : seul un repos suffisant permettra à ta santé de s'améliorer.", "只有好好休息，你的身体才能好起来。", "Ce n'est qu'en te reposant bien que ton état peut s'améliorer."),
N("Fin du focus. N'employez 只有 que si vous assumez l'idée de condition nécessaire."),
];}},

{num:4,hanzi:"更没想好去哪儿",title:"Partie 4 · Envisager des études à l'étranger",desc:"Dialogue 3 · suggestions · progression avec 更",build(){return[
N("Partie 4. Li Wen apprend que Chen Tianzhong veut poursuivre ses études."),
HC("天中，你的手机怎么关机了？", "Tianzhong, pourquoi ton téléphone est-il éteint ?", .66),
HC("我的手机没电了。你找我有事吗？", "Il n'a plus de batterie. Tu me cherchais pour quelque chose ?", .66),
HC("前天我看见家月了，她告诉我你打算继续留学。", "Avant-hier, j'ai vu Jiayue ; elle m'a dit que tu comptais poursuivre tes études à l'étranger.", .58),
HC("是，可是我还没想好学什么，更没想好去哪个国家。", "Oui, mais je n'ai pas encore choisi quoi étudier, et encore moins dans quel pays aller.", .58),
HC("你可以去中国学中文。比如北京、上海这样的大城市，那里有很多好大学，也有很多留学生。", "Tu pourrais étudier le chinois en Chine, par exemple dans une grande ville comme Pékin ou Shanghai, où il y a de bonnes universités et beaucoup d'étudiants étrangers.", .52),
HC("好，那我上网查一查。", "D'accord, je vais faire des recherches en ligne.", .68),
HC("我给你介绍几个有用的网站。", "Je vais te recommander quelques sites utiles.", .68),

N("Dans deux propositions progressives, [[更|gèng]] renforce la seconde : je n'ai pas choisi le domaine, encore moins le pays."),
HC("我还没想好学什么，更没想好去哪儿。", "Je n'ai pas encore choisi quoi étudier, encore moins où aller.", .7),
HC("提高中文要多听多看，更要多说多练。", "Pour améliorer son chinois, il faut beaucoup écouter et lire, et surtout parler et pratiquer davantage.", .68),
HC("学习中文让我会说中文，更让我了解中国文化。", "Apprendre le chinois m'a permis de parler, mais surtout de mieux comprendre la culture chinoise.", .66),
...h3drill("Progression négative : je n'ai pas choisi la ville, encore moins l'université.", "我还没选好城市，更没选好大学。", "Je n'ai pas encore choisi la ville, encore moins l'université."),
...h3drill("Progression positive : il faut travailler, et surtout savoir se reposer.", "我们要认真工作，更要学会休息。", "Nous devons travailler sérieusement, et surtout apprendre à nous reposer."),
N("Fin de la partie 4. Vous savez hiérarchiser deux difficultés ou deux priorités."),
];}},

{num:5,hanzi:"真正喜欢什么",title:"Partie 5 · Faire un choix personnel",desc:"Journal guidé · orientations · condition nécessaire",build(){return[
N("Partie 5. La fin de l'université approche et Chen Tianzhong réfléchit à son avenir."),
HC("大学生活马上就要结束了，我最近经常被问到一个问题：你以后想做什么？", "Mes études vont bientôt se terminer et l'on me pose souvent cette question : que veux-tu faire plus tard ?", .54),
HC("这个问题真不容易回答。", "Cette question n'est vraiment pas facile.", .7),
HC("我问了几个同学，大家选择的方向都不同。", "J'ai interrogé plusieurs camarades ; chacun choisit une direction différente.", .62),
HC("有的想继续在学校学习，有的打算出国留学，还有的决定先找工作。", "Certains veulent continuer à étudier, d'autres partir à l'étranger, d'autres encore chercher d'abord un emploi.", .56),
HC("我认为只有想清楚自己真正喜欢什么，才能做出最合适的选择。", "Je pense qu'il faut comprendre ce que l'on aime réellement pour faire le choix le plus adapté.", .56),
HC("对我来说，想清楚真正喜欢什么是个难题。", "Pour moi, comprendre ce que j'aime réellement reste une question difficile.", .62),

N("Compréhension. Quelles sont les trois grandes options des camarades ?"),
TH(),HC("继续学习、出国留学或者先找工作。", "Continuer les études, partir étudier à l'étranger ou chercher d'abord un emploi.", .68),HOLD(),
N("Chen Tianzhong a-t-il déjà trouvé sa réponse ?"),
TH(),HC("还没有，他还不知道自己真正喜欢什么。", "Pas encore ; il ne sait toujours pas ce qu'il aime réellement.", .68),HOLD(),

N("Mission personnelle. Présentez une option, un critère indispensable et une prochaine étape. Modèle :"),
TH(),HC("我想继续学习。对我来说，只有找到真正感兴趣的方向，才能选好学校，所以我要先查一些资料。", "Je veux poursuivre mes études. Pour moi, il faut trouver un domaine réellement intéressant avant de choisir une école ; je vais donc commencer par faire des recherches.", .58),HOLD("Répète ce modèle ou formule ton propre projet, puis ▶"),
N("Fin de la partie 5. Vous pouvez parler d'un avenir incertain sans inventer une certitude."),
];}},

{num:6,hanzi:"综合练习",title:"Partie 6 · Exercices créés",desc:"Direction · rappel · priorité · choix",exercise:true,build(){return[
N("Exercices originaux de la leçon 17. Répondez avant la correction."),
N("Exercice 1. Demandez conseil à une personne expérimentée."),
TH(),HC("我想向有经验的人请教。", "Je voudrais demander conseil à une personne expérimentée.", .72),HOLD(),
N("Exercice 2. Rappelez : tu ne voulais pas continuer tes études ?"),
TH(),HC("你不是想继续学习吗？", "Tu ne voulais pas poursuivre tes études ?", .72),HOLD(),
N("Exercice 3. Seul un travail sérieux permet d'éviter ces erreurs."),
TH(),HC("只有认真做，才不会出这些错。", "Ce n'est qu'en travaillant sérieusement qu'on peut éviter ces erreurs.", .7),HOLD(),
N("Exercice 4. Je n'ai pas choisi le pays, encore moins la ville."),
TH(),HC("我还没选好国家，更没选好城市。", "Je n'ai pas encore choisi le pays, encore moins la ville.", .7),HOLD(),
N("Exercice 5. Indiquez une direction : l'enfant court vers son père."),
TH(),HC("孩子向爸爸跑过去了。", "L'enfant a couru vers son père.", .72),HOLD(),
N("Exercice 6. Condition ordinaire : si tes parents sont d'accord, pars étudier."),
TH(),HC("你父母同意的话，就去留学吧。", "Si tes parents sont d'accord, pars étudier à l'étranger.", .7),HOLD(),
N("Exercice 7. Condition indispensable : ce n'est qu'après recherche que l'on peut décider."),
TH(),HC("只有查清楚学校的情况，才能做决定。", "Ce n'est qu'après avoir vérifié les informations sur l'école qu'on peut décider.", .68),HOLD(),
N("Exercice 8. Mini-dialogue : exprimez votre peur de vous tromper ; votre ami rappelle vos qualités et propose une méthode."),
TH(),HC("我怕选错方向，不知道怎么办。", "J'ai peur de choisir la mauvaise voie et je ne sais pas quoi faire.", .72),
HC("你不是很喜欢电脑吗？先查一查有关的专业，再向老师请教。", "Tu aimes l'informatique, non ? Cherche d'abord les filières correspondantes, puis demande conseil à un professeur.", .66),HOLD(),
N("Bravo. Vous savez transformer l'hésitation en critères, recherches et prochaines étapes."),
HC("只有认真了解自己，才能做出合适的选择。", "Ce n'est qu'en se connaissant sérieusement que l'on peut faire un choix adapté.", .7),
HC("再见！", "Au revoir !", .74),
];}}
]});
